/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AlternativeDistributionPackageCreateRequestDataRelationshipsAppStoreVersionData
 */
export interface AlternativeDistributionPackageCreateRequestDataRelationshipsAppStoreVersionData {
    /**
     * 
     * @type {string}
     * @memberof AlternativeDistributionPackageCreateRequestDataRelationshipsAppStoreVersionData
     */
    type: AlternativeDistributionPackageCreateRequestDataRelationshipsAppStoreVersionDataTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AlternativeDistributionPackageCreateRequestDataRelationshipsAppStoreVersionData
     */
    id: string;
}


/**
 * @export
 */
export const AlternativeDistributionPackageCreateRequestDataRelationshipsAppStoreVersionDataTypeEnum = {
    AppStoreVersions: 'appStoreVersions'
} as const;
export type AlternativeDistributionPackageCreateRequestDataRelationshipsAppStoreVersionDataTypeEnum = typeof AlternativeDistributionPackageCreateRequestDataRelationshipsAppStoreVersionDataTypeEnum[keyof typeof AlternativeDistributionPackageCreateRequestDataRelationshipsAppStoreVersionDataTypeEnum];


/**
 * Check if a given object implements the AlternativeDistributionPackageCreateRequestDataRelationshipsAppStoreVersionData interface.
 */
export function instanceOfAlternativeDistributionPackageCreateRequestDataRelationshipsAppStoreVersionData(value: object): value is AlternativeDistributionPackageCreateRequestDataRelationshipsAppStoreVersionData {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function AlternativeDistributionPackageCreateRequestDataRelationshipsAppStoreVersionDataFromJSON(json: any): AlternativeDistributionPackageCreateRequestDataRelationshipsAppStoreVersionData {
    return AlternativeDistributionPackageCreateRequestDataRelationshipsAppStoreVersionDataFromJSONTyped(json, false);
}

export function AlternativeDistributionPackageCreateRequestDataRelationshipsAppStoreVersionDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlternativeDistributionPackageCreateRequestDataRelationshipsAppStoreVersionData {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
    };
}

export function AlternativeDistributionPackageCreateRequestDataRelationshipsAppStoreVersionDataToJSON(json: any): AlternativeDistributionPackageCreateRequestDataRelationshipsAppStoreVersionData {
    return AlternativeDistributionPackageCreateRequestDataRelationshipsAppStoreVersionDataToJSONTyped(json, false);
}

export function AlternativeDistributionPackageCreateRequestDataRelationshipsAppStoreVersionDataToJSONTyped(value?: AlternativeDistributionPackageCreateRequestDataRelationshipsAppStoreVersionData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
    };
}

