/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AlternativeDistributionDomain } from './AlternativeDistributionDomain';
import {
    AlternativeDistributionDomainFromJSON,
    AlternativeDistributionDomainFromJSONTyped,
    AlternativeDistributionDomainToJSON,
    AlternativeDistributionDomainToJSONTyped,
} from './AlternativeDistributionDomain';
import type { DocumentLinks } from './DocumentLinks';
import {
    DocumentLinksFromJSON,
    DocumentLinksFromJSONTyped,
    DocumentLinksToJSON,
    DocumentLinksToJSONTyped,
} from './DocumentLinks';

/**
 * 
 * @export
 * @interface AlternativeDistributionDomainResponse
 */
export interface AlternativeDistributionDomainResponse {
    /**
     * 
     * @type {AlternativeDistributionDomain}
     * @memberof AlternativeDistributionDomainResponse
     */
    data: AlternativeDistributionDomain;
    /**
     * 
     * @type {DocumentLinks}
     * @memberof AlternativeDistributionDomainResponse
     */
    links: DocumentLinks;
}

/**
 * Check if a given object implements the AlternativeDistributionDomainResponse interface.
 */
export function instanceOfAlternativeDistributionDomainResponse(value: object): value is AlternativeDistributionDomainResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('links' in value) || value['links'] === undefined) return false;
    return true;
}

export function AlternativeDistributionDomainResponseFromJSON(json: any): AlternativeDistributionDomainResponse {
    return AlternativeDistributionDomainResponseFromJSONTyped(json, false);
}

export function AlternativeDistributionDomainResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlternativeDistributionDomainResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': AlternativeDistributionDomainFromJSON(json['data']),
        'links': DocumentLinksFromJSON(json['links']),
    };
}

export function AlternativeDistributionDomainResponseToJSON(json: any): AlternativeDistributionDomainResponse {
    return AlternativeDistributionDomainResponseToJSONTyped(json, false);
}

export function AlternativeDistributionDomainResponseToJSONTyped(value?: AlternativeDistributionDomainResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': AlternativeDistributionDomainToJSON(value['data']),
        'links': DocumentLinksToJSON(value['links']),
    };
}

