/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PagingInformation } from './PagingInformation';
import {
    PagingInformationFromJSON,
    PagingInformationFromJSONTyped,
    PagingInformationToJSON,
    PagingInformationToJSONTyped,
} from './PagingInformation';
import type { RelationshipLinks } from './RelationshipLinks';
import {
    RelationshipLinksFromJSON,
    RelationshipLinksFromJSONTyped,
    RelationshipLinksToJSON,
    RelationshipLinksToJSONTyped,
} from './RelationshipLinks';
import type { AlternativeDistributionPackageVersionRelationshipsDeltasDataInner } from './AlternativeDistributionPackageVersionRelationshipsDeltasDataInner';
import {
    AlternativeDistributionPackageVersionRelationshipsDeltasDataInnerFromJSON,
    AlternativeDistributionPackageVersionRelationshipsDeltasDataInnerFromJSONTyped,
    AlternativeDistributionPackageVersionRelationshipsDeltasDataInnerToJSON,
    AlternativeDistributionPackageVersionRelationshipsDeltasDataInnerToJSONTyped,
} from './AlternativeDistributionPackageVersionRelationshipsDeltasDataInner';

/**
 * 
 * @export
 * @interface AlternativeDistributionPackageVersionRelationshipsDeltas
 */
export interface AlternativeDistributionPackageVersionRelationshipsDeltas {
    /**
     * 
     * @type {RelationshipLinks}
     * @memberof AlternativeDistributionPackageVersionRelationshipsDeltas
     */
    links?: RelationshipLinks;
    /**
     * 
     * @type {PagingInformation}
     * @memberof AlternativeDistributionPackageVersionRelationshipsDeltas
     */
    meta?: PagingInformation;
    /**
     * 
     * @type {Array<AlternativeDistributionPackageVersionRelationshipsDeltasDataInner>}
     * @memberof AlternativeDistributionPackageVersionRelationshipsDeltas
     */
    data?: Array<AlternativeDistributionPackageVersionRelationshipsDeltasDataInner>;
}

/**
 * Check if a given object implements the AlternativeDistributionPackageVersionRelationshipsDeltas interface.
 */
export function instanceOfAlternativeDistributionPackageVersionRelationshipsDeltas(value: object): value is AlternativeDistributionPackageVersionRelationshipsDeltas {
    return true;
}

export function AlternativeDistributionPackageVersionRelationshipsDeltasFromJSON(json: any): AlternativeDistributionPackageVersionRelationshipsDeltas {
    return AlternativeDistributionPackageVersionRelationshipsDeltasFromJSONTyped(json, false);
}

export function AlternativeDistributionPackageVersionRelationshipsDeltasFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlternativeDistributionPackageVersionRelationshipsDeltas {
    if (json == null) {
        return json;
    }
    return {
        
        'links': json['links'] == null ? undefined : RelationshipLinksFromJSON(json['links']),
        'meta': json['meta'] == null ? undefined : PagingInformationFromJSON(json['meta']),
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(AlternativeDistributionPackageVersionRelationshipsDeltasDataInnerFromJSON)),
    };
}

export function AlternativeDistributionPackageVersionRelationshipsDeltasToJSON(json: any): AlternativeDistributionPackageVersionRelationshipsDeltas {
    return AlternativeDistributionPackageVersionRelationshipsDeltasToJSONTyped(json, false);
}

export function AlternativeDistributionPackageVersionRelationshipsDeltasToJSONTyped(value?: AlternativeDistributionPackageVersionRelationshipsDeltas | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'links': RelationshipLinksToJSON(value['links']),
        'meta': PagingInformationToJSON(value['meta']),
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(AlternativeDistributionPackageVersionRelationshipsDeltasDataInnerToJSON)),
    };
}

