
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AnalyticsReportInstanceRelationshipsSegments } from './AnalyticsReportInstanceRelationshipsSegments';
import {
    AnalyticsReportInstanceRelationshipsSegmentsFromJSON,
    AnalyticsReportInstanceRelationshipsSegmentsFromJSONTyped,
    AnalyticsReportInstanceRelationshipsSegmentsToJSON,
    AnalyticsReportInstanceRelationshipsSegmentsToJSONTyped,
} from './AnalyticsReportInstanceRelationshipsSegments';

/**
 * 
 * @export
 * @interface AnalyticsReportRelationships
 */
export interface AnalyticsReportRelationships {
    /**
     * 
     * @type {AnalyticsReportInstanceRelationshipsSegments}
     * @memberof AnalyticsReportRelationships
     */
    instances?: AnalyticsReportInstanceRelationshipsSegments;
}

/**
 * Check if a given object implements the AnalyticsReportRelationships interface.
 */
export function instanceOfAnalyticsReportRelationships(value: object): value is AnalyticsReportRelationships {
    return true;
}

export function AnalyticsReportRelationshipsFromJSON(json: any): AnalyticsReportRelationships {
    return AnalyticsReportRelationshipsFromJSONTyped(json, false);
}

export function AnalyticsReportRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsReportRelationships {
    if (json == null) {
        return json;
    }
    return {
        
        'instances': json['instances'] == null ? undefined : AnalyticsReportInstanceRelationshipsSegmentsFromJSON(json['instances']),
    };
}

export function AnalyticsReportRelationshipsToJSON(json: any): AnalyticsReportRelationships {
    return AnalyticsReportRelationshipsToJSONTyped(json, false);
}

export function AnalyticsReportRelationshipsToJSONTyped(value?: AnalyticsReportRelationships | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'instances': AnalyticsReportInstanceRelationshipsSegmentsToJSON(value['instances']),
    };
}

