
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AnalyticsReportRequestCreateRequestData } from './AnalyticsReportRequestCreateRequestData';
import {
    AnalyticsReportRequestCreateRequestDataFromJSON,
    AnalyticsReportRequestCreateRequestDataFromJSONTyped,
    AnalyticsReportRequestCreateRequestDataToJSON,
    AnalyticsReportRequestCreateRequestDataToJSONTyped,
} from './AnalyticsReportRequestCreateRequestData';

/**
 * 
 * @export
 * @interface AnalyticsReportRequestCreateRequest
 */
export interface AnalyticsReportRequestCreateRequest {
    /**
     * 
     * @type {AnalyticsReportRequestCreateRequestData}
     * @memberof AnalyticsReportRequestCreateRequest
     */
    data: AnalyticsReportRequestCreateRequestData;
}

/**
 * Check if a given object implements the AnalyticsReportRequestCreateRequest interface.
 */
export function instanceOfAnalyticsReportRequestCreateRequest(value: object): value is AnalyticsReportRequestCreateRequest {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AnalyticsReportRequestCreateRequestFromJSON(json: any): AnalyticsReportRequestCreateRequest {
    return AnalyticsReportRequestCreateRequestFromJSONTyped(json, false);
}

export function AnalyticsReportRequestCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsReportRequestCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'data': AnalyticsReportRequestCreateRequestDataFromJSON(json['data']),
    };
}

export function AnalyticsReportRequestCreateRequestToJSON(json: any): AnalyticsReportRequestCreateRequest {
    return AnalyticsReportRequestCreateRequestToJSONTyped(json, false);
}

export function AnalyticsReportRequestCreateRequestToJSONTyped(value?: AnalyticsReportRequestCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': AnalyticsReportRequestCreateRequestDataToJSON(value['data']),
    };
}

