
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnalyticsReportRequestAttributes
 */
export interface AnalyticsReportRequestAttributes {
    /**
     * 
     * @type {string}
     * @memberof AnalyticsReportRequestAttributes
     */
    accessType?: AnalyticsReportRequestAttributesAccessTypeEnum;
    /**
     * 
     * @type {boolean}
     * @memberof AnalyticsReportRequestAttributes
     */
    stoppedDueToInactivity?: boolean;
}


/**
 * @export
 */
export const AnalyticsReportRequestAttributesAccessTypeEnum = {
    OneTimeSnapshot: 'ONE_TIME_SNAPSHOT',
    Ongoing: 'ONGOING'
} as const;
export type AnalyticsReportRequestAttributesAccessTypeEnum = typeof AnalyticsReportRequestAttributesAccessTypeEnum[keyof typeof AnalyticsReportRequestAttributesAccessTypeEnum];


/**
 * Check if a given object implements the AnalyticsReportRequestAttributes interface.
 */
export function instanceOfAnalyticsReportRequestAttributes(value: object): value is AnalyticsReportRequestAttributes {
    return true;
}

export function AnalyticsReportRequestAttributesFromJSON(json: any): AnalyticsReportRequestAttributes {
    return AnalyticsReportRequestAttributesFromJSONTyped(json, false);
}

export function AnalyticsReportRequestAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsReportRequestAttributes {
    if (json == null) {
        return json;
    }
    return {
        
        'accessType': json['accessType'] == null ? undefined : json['accessType'],
        'stoppedDueToInactivity': json['stoppedDueToInactivity'] == null ? undefined : json['stoppedDueToInactivity'],
    };
}

export function AnalyticsReportRequestAttributesToJSON(json: any): AnalyticsReportRequestAttributes {
    return AnalyticsReportRequestAttributesToJSONTyped(json, false);
}

export function AnalyticsReportRequestAttributesToJSONTyped(value?: AnalyticsReportRequestAttributes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accessType': value['accessType'],
        'stoppedDueToInactivity': value['stoppedDueToInactivity'],
    };
}

