
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppCustomProductPageLocalizationUpdateRequestDataAttributes } from './AppCustomProductPageLocalizationUpdateRequestDataAttributes';
import {
    AppCustomProductPageLocalizationUpdateRequestDataAttributesFromJSON,
    AppCustomProductPageLocalizationUpdateRequestDataAttributesFromJSONTyped,
    AppCustomProductPageLocalizationUpdateRequestDataAttributesToJSON,
    AppCustomProductPageLocalizationUpdateRequestDataAttributesToJSONTyped,
} from './AppCustomProductPageLocalizationUpdateRequestDataAttributes';

/**
 * 
 * @export
 * @interface AppCustomProductPageLocalizationUpdateRequestData
 */
export interface AppCustomProductPageLocalizationUpdateRequestData {
    /**
     * 
     * @type {string}
     * @memberof AppCustomProductPageLocalizationUpdateRequestData
     */
    type: AppCustomProductPageLocalizationUpdateRequestDataTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AppCustomProductPageLocalizationUpdateRequestData
     */
    id: string;
    /**
     * 
     * @type {AppCustomProductPageLocalizationUpdateRequestDataAttributes}
     * @memberof AppCustomProductPageLocalizationUpdateRequestData
     */
    attributes?: AppCustomProductPageLocalizationUpdateRequestDataAttributes;
}


/**
 * @export
 */
export const AppCustomProductPageLocalizationUpdateRequestDataTypeEnum = {
    AppCustomProductPageLocalizations: 'appCustomProductPageLocalizations'
} as const;
export type AppCustomProductPageLocalizationUpdateRequestDataTypeEnum = typeof AppCustomProductPageLocalizationUpdateRequestDataTypeEnum[keyof typeof AppCustomProductPageLocalizationUpdateRequestDataTypeEnum];


/**
 * Check if a given object implements the AppCustomProductPageLocalizationUpdateRequestData interface.
 */
export function instanceOfAppCustomProductPageLocalizationUpdateRequestData(value: object): value is AppCustomProductPageLocalizationUpdateRequestData {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function AppCustomProductPageLocalizationUpdateRequestDataFromJSON(json: any): AppCustomProductPageLocalizationUpdateRequestData {
    return AppCustomProductPageLocalizationUpdateRequestDataFromJSONTyped(json, false);
}

export function AppCustomProductPageLocalizationUpdateRequestDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppCustomProductPageLocalizationUpdateRequestData {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': json['attributes'] == null ? undefined : AppCustomProductPageLocalizationUpdateRequestDataAttributesFromJSON(json['attributes']),
    };
}

export function AppCustomProductPageLocalizationUpdateRequestDataToJSON(json: any): AppCustomProductPageLocalizationUpdateRequestData {
    return AppCustomProductPageLocalizationUpdateRequestDataToJSONTyped(json, false);
}

export function AppCustomProductPageLocalizationUpdateRequestDataToJSONTyped(value?: AppCustomProductPageLocalizationUpdateRequestData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
        'attributes': AppCustomProductPageLocalizationUpdateRequestDataAttributesToJSON(value['attributes']),
    };
}

