/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppClipAdvancedExperienceAttributes } from './AppClipAdvancedExperienceAttributes';
import {
    AppClipAdvancedExperienceAttributesFromJSON,
    AppClipAdvancedExperienceAttributesFromJSONTyped,
    AppClipAdvancedExperienceAttributesToJSON,
    AppClipAdvancedExperienceAttributesToJSONTyped,
} from './AppClipAdvancedExperienceAttributes';
import type { ResourceLinks } from './ResourceLinks';
import {
    ResourceLinksFromJSON,
    ResourceLinksFromJSONTyped,
    ResourceLinksToJSON,
    ResourceLinksToJSONTyped,
} from './ResourceLinks';
import type { AppClipAdvancedExperienceRelationships } from './AppClipAdvancedExperienceRelationships';
import {
    AppClipAdvancedExperienceRelationshipsFromJSON,
    AppClipAdvancedExperienceRelationshipsFromJSONTyped,
    AppClipAdvancedExperienceRelationshipsToJSON,
    AppClipAdvancedExperienceRelationshipsToJSONTyped,
} from './AppClipAdvancedExperienceRelationships';

/**
 * 
 * @export
 * @interface AppClipAdvancedExperience
 */
export interface AppClipAdvancedExperience {
    /**
     * 
     * @type {string}
     * @memberof AppClipAdvancedExperience
     */
    type: AppClipAdvancedExperienceTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AppClipAdvancedExperience
     */
    id: string;
    /**
     * 
     * @type {AppClipAdvancedExperienceAttributes}
     * @memberof AppClipAdvancedExperience
     */
    attributes?: AppClipAdvancedExperienceAttributes;
    /**
     * 
     * @type {AppClipAdvancedExperienceRelationships}
     * @memberof AppClipAdvancedExperience
     */
    relationships?: AppClipAdvancedExperienceRelationships;
    /**
     * 
     * @type {ResourceLinks}
     * @memberof AppClipAdvancedExperience
     */
    links?: ResourceLinks;
}


/**
 * @export
 */
export const AppClipAdvancedExperienceTypeEnum = {
    AppClipAdvancedExperiences: 'appClipAdvancedExperiences'
} as const;
export type AppClipAdvancedExperienceTypeEnum = typeof AppClipAdvancedExperienceTypeEnum[keyof typeof AppClipAdvancedExperienceTypeEnum];


/**
 * Check if a given object implements the AppClipAdvancedExperience interface.
 */
export function instanceOfAppClipAdvancedExperience(value: object): value is AppClipAdvancedExperience {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function AppClipAdvancedExperienceFromJSON(json: any): AppClipAdvancedExperience {
    return AppClipAdvancedExperienceFromJSONTyped(json, false);
}

export function AppClipAdvancedExperienceFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppClipAdvancedExperience {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': json['attributes'] == null ? undefined : AppClipAdvancedExperienceAttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : AppClipAdvancedExperienceRelationshipsFromJSON(json['relationships']),
        'links': json['links'] == null ? undefined : ResourceLinksFromJSON(json['links']),
    };
}

export function AppClipAdvancedExperienceToJSON(json: any): AppClipAdvancedExperience {
    return AppClipAdvancedExperienceToJSONTyped(json, false);
}

export function AppClipAdvancedExperienceToJSONTyped(value?: AppClipAdvancedExperience | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
        'attributes': AppClipAdvancedExperienceAttributesToJSON(value['attributes']),
        'relationships': AppClipAdvancedExperienceRelationshipsToJSON(value['relationships']),
        'links': ResourceLinksToJSON(value['links']),
    };
}

