
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppClipAdvancedExperienceAttributesPlacePhoneNumber
 */
export interface AppClipAdvancedExperienceAttributesPlacePhoneNumber {
    /**
     * 
     * @type {string}
     * @memberof AppClipAdvancedExperienceAttributesPlacePhoneNumber
     */
    number?: string;
    /**
     * 
     * @type {string}
     * @memberof AppClipAdvancedExperienceAttributesPlacePhoneNumber
     */
    type?: AppClipAdvancedExperienceAttributesPlacePhoneNumberTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AppClipAdvancedExperienceAttributesPlacePhoneNumber
     */
    intent?: string;
}


/**
 * @export
 */
export const AppClipAdvancedExperienceAttributesPlacePhoneNumberTypeEnum = {
    Fax: 'FAX',
    Landline: 'LANDLINE',
    Mobile: 'MOBILE',
    Tollfree: 'TOLLFREE'
} as const;
export type AppClipAdvancedExperienceAttributesPlacePhoneNumberTypeEnum = typeof AppClipAdvancedExperienceAttributesPlacePhoneNumberTypeEnum[keyof typeof AppClipAdvancedExperienceAttributesPlacePhoneNumberTypeEnum];


/**
 * Check if a given object implements the AppClipAdvancedExperienceAttributesPlacePhoneNumber interface.
 */
export function instanceOfAppClipAdvancedExperienceAttributesPlacePhoneNumber(value: object): value is AppClipAdvancedExperienceAttributesPlacePhoneNumber {
    return true;
}

export function AppClipAdvancedExperienceAttributesPlacePhoneNumberFromJSON(json: any): AppClipAdvancedExperienceAttributesPlacePhoneNumber {
    return AppClipAdvancedExperienceAttributesPlacePhoneNumberFromJSONTyped(json, false);
}

export function AppClipAdvancedExperienceAttributesPlacePhoneNumberFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppClipAdvancedExperienceAttributesPlacePhoneNumber {
    if (json == null) {
        return json;
    }
    return {
        
        'number': json['number'] == null ? undefined : json['number'],
        'type': json['type'] == null ? undefined : json['type'],
        'intent': json['intent'] == null ? undefined : json['intent'],
    };
}

export function AppClipAdvancedExperienceAttributesPlacePhoneNumberToJSON(json: any): AppClipAdvancedExperienceAttributesPlacePhoneNumber {
    return AppClipAdvancedExperienceAttributesPlacePhoneNumberToJSONTyped(json, false);
}

export function AppClipAdvancedExperienceAttributesPlacePhoneNumberToJSONTyped(value?: AppClipAdvancedExperienceAttributesPlacePhoneNumber | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'number': value['number'],
        'type': value['type'],
        'intent': value['intent'],
    };
}

