
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppEventScreenshotRelationshipsAppEventLocalizationData } from './AppEventScreenshotRelationshipsAppEventLocalizationData';
import {
    AppEventScreenshotRelationshipsAppEventLocalizationDataFromJSON,
    AppEventScreenshotRelationshipsAppEventLocalizationDataFromJSONTyped,
    AppEventScreenshotRelationshipsAppEventLocalizationDataToJSON,
    AppEventScreenshotRelationshipsAppEventLocalizationDataToJSONTyped,
} from './AppEventScreenshotRelationshipsAppEventLocalizationData';

/**
 * 
 * @export
 * @interface AppEventScreenshotRelationshipsAppEventLocalization
 */
export interface AppEventScreenshotRelationshipsAppEventLocalization {
    /**
     * 
     * @type {AppEventScreenshotRelationshipsAppEventLocalizationData}
     * @memberof AppEventScreenshotRelationshipsAppEventLocalization
     */
    data?: AppEventScreenshotRelationshipsAppEventLocalizationData;
}

/**
 * Check if a given object implements the AppEventScreenshotRelationshipsAppEventLocalization interface.
 */
export function instanceOfAppEventScreenshotRelationshipsAppEventLocalization(value: object): value is AppEventScreenshotRelationshipsAppEventLocalization {
    return true;
}

export function AppEventScreenshotRelationshipsAppEventLocalizationFromJSON(json: any): AppEventScreenshotRelationshipsAppEventLocalization {
    return AppEventScreenshotRelationshipsAppEventLocalizationFromJSONTyped(json, false);
}

export function AppEventScreenshotRelationshipsAppEventLocalizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppEventScreenshotRelationshipsAppEventLocalization {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : AppEventScreenshotRelationshipsAppEventLocalizationDataFromJSON(json['data']),
    };
}

export function AppEventScreenshotRelationshipsAppEventLocalizationToJSON(json: any): AppEventScreenshotRelationshipsAppEventLocalization {
    return AppEventScreenshotRelationshipsAppEventLocalizationToJSONTyped(json, false);
}

export function AppEventScreenshotRelationshipsAppEventLocalizationToJSONTyped(value?: AppEventScreenshotRelationshipsAppEventLocalization | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': AppEventScreenshotRelationshipsAppEventLocalizationDataToJSON(value['data']),
    };
}

