
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppEventCreateRequestData } from './AppEventCreateRequestData';
import {
    AppEventCreateRequestDataFromJSON,
    AppEventCreateRequestDataFromJSONTyped,
    AppEventCreateRequestDataToJSON,
    AppEventCreateRequestDataToJSONTyped,
} from './AppEventCreateRequestData';

/**
 * 
 * @export
 * @interface AppEventCreateRequest
 */
export interface AppEventCreateRequest {
    /**
     * 
     * @type {AppEventCreateRequestData}
     * @memberof AppEventCreateRequest
     */
    data: AppEventCreateRequestData;
}

/**
 * Check if a given object implements the AppEventCreateRequest interface.
 */
export function instanceOfAppEventCreateRequest(value: object): value is AppEventCreateRequest {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AppEventCreateRequestFromJSON(json: any): AppEventCreateRequest {
    return AppEventCreateRequestFromJSONTyped(json, false);
}

export function AppEventCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppEventCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'data': AppEventCreateRequestDataFromJSON(json['data']),
    };
}

export function AppEventCreateRequestToJSON(json: any): AppEventCreateRequest {
    return AppEventCreateRequestToJSONTyped(json, false);
}

export function AppEventCreateRequestToJSONTyped(value?: AppEventCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': AppEventCreateRequestDataToJSON(value['data']),
    };
}

