
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppEncryptionDeclarationCreateRequestDataRelationships } from './AppEncryptionDeclarationCreateRequestDataRelationships';
import {
    AppEncryptionDeclarationCreateRequestDataRelationshipsFromJSON,
    AppEncryptionDeclarationCreateRequestDataRelationshipsFromJSONTyped,
    AppEncryptionDeclarationCreateRequestDataRelationshipsToJSON,
    AppEncryptionDeclarationCreateRequestDataRelationshipsToJSONTyped,
} from './AppEncryptionDeclarationCreateRequestDataRelationships';
import type { AppEncryptionDeclarationCreateRequestDataAttributes } from './AppEncryptionDeclarationCreateRequestDataAttributes';
import {
    AppEncryptionDeclarationCreateRequestDataAttributesFromJSON,
    AppEncryptionDeclarationCreateRequestDataAttributesFromJSONTyped,
    AppEncryptionDeclarationCreateRequestDataAttributesToJSON,
    AppEncryptionDeclarationCreateRequestDataAttributesToJSONTyped,
} from './AppEncryptionDeclarationCreateRequestDataAttributes';

/**
 * 
 * @export
 * @interface AppEncryptionDeclarationCreateRequestData
 */
export interface AppEncryptionDeclarationCreateRequestData {
    /**
     * 
     * @type {string}
     * @memberof AppEncryptionDeclarationCreateRequestData
     */
    type: AppEncryptionDeclarationCreateRequestDataTypeEnum;
    /**
     * 
     * @type {AppEncryptionDeclarationCreateRequestDataAttributes}
     * @memberof AppEncryptionDeclarationCreateRequestData
     */
    attributes: AppEncryptionDeclarationCreateRequestDataAttributes;
    /**
     * 
     * @type {AppEncryptionDeclarationCreateRequestDataRelationships}
     * @memberof AppEncryptionDeclarationCreateRequestData
     */
    relationships: AppEncryptionDeclarationCreateRequestDataRelationships;
}


/**
 * @export
 */
export const AppEncryptionDeclarationCreateRequestDataTypeEnum = {
    AppEncryptionDeclarations: 'appEncryptionDeclarations'
} as const;
export type AppEncryptionDeclarationCreateRequestDataTypeEnum = typeof AppEncryptionDeclarationCreateRequestDataTypeEnum[keyof typeof AppEncryptionDeclarationCreateRequestDataTypeEnum];


/**
 * Check if a given object implements the AppEncryptionDeclarationCreateRequestData interface.
 */
export function instanceOfAppEncryptionDeclarationCreateRequestData(value: object): value is AppEncryptionDeclarationCreateRequestData {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    if (!('relationships' in value) || value['relationships'] === undefined) return false;
    return true;
}

export function AppEncryptionDeclarationCreateRequestDataFromJSON(json: any): AppEncryptionDeclarationCreateRequestData {
    return AppEncryptionDeclarationCreateRequestDataFromJSONTyped(json, false);
}

export function AppEncryptionDeclarationCreateRequestDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppEncryptionDeclarationCreateRequestData {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'attributes': AppEncryptionDeclarationCreateRequestDataAttributesFromJSON(json['attributes']),
        'relationships': AppEncryptionDeclarationCreateRequestDataRelationshipsFromJSON(json['relationships']),
    };
}

export function AppEncryptionDeclarationCreateRequestDataToJSON(json: any): AppEncryptionDeclarationCreateRequestData {
    return AppEncryptionDeclarationCreateRequestDataToJSONTyped(json, false);
}

export function AppEncryptionDeclarationCreateRequestDataToJSONTyped(value?: AppEncryptionDeclarationCreateRequestData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'attributes': AppEncryptionDeclarationCreateRequestDataAttributesToJSON(value['attributes']),
        'relationships': AppEncryptionDeclarationCreateRequestDataRelationshipsToJSON(value['relationships']),
    };
}

