
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppEventScreenshotRelationshipsAppEventLocalization } from './AppEventScreenshotRelationshipsAppEventLocalization';
import {
    AppEventScreenshotRelationshipsAppEventLocalizationFromJSON,
    AppEventScreenshotRelationshipsAppEventLocalizationFromJSONTyped,
    AppEventScreenshotRelationshipsAppEventLocalizationToJSON,
    AppEventScreenshotRelationshipsAppEventLocalizationToJSONTyped,
} from './AppEventScreenshotRelationshipsAppEventLocalization';

/**
 * 
 * @export
 * @interface AppEventScreenshotRelationships
 */
export interface AppEventScreenshotRelationships {
    /**
     * 
     * @type {AppEventScreenshotRelationshipsAppEventLocalization}
     * @memberof AppEventScreenshotRelationships
     */
    appEventLocalization?: AppEventScreenshotRelationshipsAppEventLocalization;
}

/**
 * Check if a given object implements the AppEventScreenshotRelationships interface.
 */
export function instanceOfAppEventScreenshotRelationships(value: object): value is AppEventScreenshotRelationships {
    return true;
}

export function AppEventScreenshotRelationshipsFromJSON(json: any): AppEventScreenshotRelationships {
    return AppEventScreenshotRelationshipsFromJSONTyped(json, false);
}

export function AppEventScreenshotRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppEventScreenshotRelationships {
    if (json == null) {
        return json;
    }
    return {
        
        'appEventLocalization': json['appEventLocalization'] == null ? undefined : AppEventScreenshotRelationshipsAppEventLocalizationFromJSON(json['appEventLocalization']),
    };
}

export function AppEventScreenshotRelationshipsToJSON(json: any): AppEventScreenshotRelationships {
    return AppEventScreenshotRelationshipsToJSONTyped(json, false);
}

export function AppEventScreenshotRelationshipsToJSONTyped(value?: AppEventScreenshotRelationships | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'appEventLocalization': AppEventScreenshotRelationshipsAppEventLocalizationToJSON(value['appEventLocalization']),
    };
}

