
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppEncryptionDeclarationRelationshipsBuildsDataInner
 */
export interface AppEncryptionDeclarationRelationshipsBuildsDataInner {
    /**
     * 
     * @type {string}
     * @memberof AppEncryptionDeclarationRelationshipsBuildsDataInner
     */
    type: AppEncryptionDeclarationRelationshipsBuildsDataInnerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AppEncryptionDeclarationRelationshipsBuildsDataInner
     */
    id: string;
}


/**
 * @export
 */
export const AppEncryptionDeclarationRelationshipsBuildsDataInnerTypeEnum = {
    Builds: 'builds'
} as const;
export type AppEncryptionDeclarationRelationshipsBuildsDataInnerTypeEnum = typeof AppEncryptionDeclarationRelationshipsBuildsDataInnerTypeEnum[keyof typeof AppEncryptionDeclarationRelationshipsBuildsDataInnerTypeEnum];


/**
 * Check if a given object implements the AppEncryptionDeclarationRelationshipsBuildsDataInner interface.
 */
export function instanceOfAppEncryptionDeclarationRelationshipsBuildsDataInner(value: object): value is AppEncryptionDeclarationRelationshipsBuildsDataInner {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function AppEncryptionDeclarationRelationshipsBuildsDataInnerFromJSON(json: any): AppEncryptionDeclarationRelationshipsBuildsDataInner {
    return AppEncryptionDeclarationRelationshipsBuildsDataInnerFromJSONTyped(json, false);
}

export function AppEncryptionDeclarationRelationshipsBuildsDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppEncryptionDeclarationRelationshipsBuildsDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
    };
}

export function AppEncryptionDeclarationRelationshipsBuildsDataInnerToJSON(json: any): AppEncryptionDeclarationRelationshipsBuildsDataInner {
    return AppEncryptionDeclarationRelationshipsBuildsDataInnerToJSONTyped(json, false);
}

export function AppEncryptionDeclarationRelationshipsBuildsDataInnerToJSONTyped(value?: AppEncryptionDeclarationRelationshipsBuildsDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
    };
}

