
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RelationshipLinks } from './RelationshipLinks';
import {
    RelationshipLinksFromJSON,
    RelationshipLinksFromJSONTyped,
    RelationshipLinksToJSON,
    RelationshipLinksToJSONTyped,
} from './RelationshipLinks';
import type { AppInfoRelationshipsAgeRatingDeclarationData } from './AppInfoRelationshipsAgeRatingDeclarationData';
import {
    AppInfoRelationshipsAgeRatingDeclarationDataFromJSON,
    AppInfoRelationshipsAgeRatingDeclarationDataFromJSONTyped,
    AppInfoRelationshipsAgeRatingDeclarationDataToJSON,
    AppInfoRelationshipsAgeRatingDeclarationDataToJSONTyped,
} from './AppInfoRelationshipsAgeRatingDeclarationData';

/**
 * 
 * @export
 * @interface AppInfoRelationshipsAgeRatingDeclaration
 */
export interface AppInfoRelationshipsAgeRatingDeclaration {
    /**
     * 
     * @type {RelationshipLinks}
     * @memberof AppInfoRelationshipsAgeRatingDeclaration
     */
    links?: RelationshipLinks;
    /**
     * 
     * @type {AppInfoRelationshipsAgeRatingDeclarationData}
     * @memberof AppInfoRelationshipsAgeRatingDeclaration
     */
    data?: AppInfoRelationshipsAgeRatingDeclarationData;
}

/**
 * Check if a given object implements the AppInfoRelationshipsAgeRatingDeclaration interface.
 */
export function instanceOfAppInfoRelationshipsAgeRatingDeclaration(value: object): value is AppInfoRelationshipsAgeRatingDeclaration {
    return true;
}

export function AppInfoRelationshipsAgeRatingDeclarationFromJSON(json: any): AppInfoRelationshipsAgeRatingDeclaration {
    return AppInfoRelationshipsAgeRatingDeclarationFromJSONTyped(json, false);
}

export function AppInfoRelationshipsAgeRatingDeclarationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppInfoRelationshipsAgeRatingDeclaration {
    if (json == null) {
        return json;
    }
    return {
        
        'links': json['links'] == null ? undefined : RelationshipLinksFromJSON(json['links']),
        'data': json['data'] == null ? undefined : AppInfoRelationshipsAgeRatingDeclarationDataFromJSON(json['data']),
    };
}

export function AppInfoRelationshipsAgeRatingDeclarationToJSON(json: any): AppInfoRelationshipsAgeRatingDeclaration {
    return AppInfoRelationshipsAgeRatingDeclarationToJSONTyped(json, false);
}

export function AppInfoRelationshipsAgeRatingDeclarationToJSONTyped(value?: AppInfoRelationshipsAgeRatingDeclaration | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'links': RelationshipLinksToJSON(value['links']),
        'data': AppInfoRelationshipsAgeRatingDeclarationDataToJSON(value['data']),
    };
}

