
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppPreviewUpdateRequestDataAttributes } from './AppPreviewUpdateRequestDataAttributes';
import {
    AppPreviewUpdateRequestDataAttributesFromJSON,
    AppPreviewUpdateRequestDataAttributesFromJSONTyped,
    AppPreviewUpdateRequestDataAttributesToJSON,
    AppPreviewUpdateRequestDataAttributesToJSONTyped,
} from './AppPreviewUpdateRequestDataAttributes';

/**
 * 
 * @export
 * @interface AppPreviewUpdateRequestData
 */
export interface AppPreviewUpdateRequestData {
    /**
     * 
     * @type {string}
     * @memberof AppPreviewUpdateRequestData
     */
    type: AppPreviewUpdateRequestDataTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AppPreviewUpdateRequestData
     */
    id: string;
    /**
     * 
     * @type {AppPreviewUpdateRequestDataAttributes}
     * @memberof AppPreviewUpdateRequestData
     */
    attributes?: AppPreviewUpdateRequestDataAttributes;
}


/**
 * @export
 */
export const AppPreviewUpdateRequestDataTypeEnum = {
    AppPreviews: 'appPreviews'
} as const;
export type AppPreviewUpdateRequestDataTypeEnum = typeof AppPreviewUpdateRequestDataTypeEnum[keyof typeof AppPreviewUpdateRequestDataTypeEnum];


/**
 * Check if a given object implements the AppPreviewUpdateRequestData interface.
 */
export function instanceOfAppPreviewUpdateRequestData(value: object): value is AppPreviewUpdateRequestData {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function AppPreviewUpdateRequestDataFromJSON(json: any): AppPreviewUpdateRequestData {
    return AppPreviewUpdateRequestDataFromJSONTyped(json, false);
}

export function AppPreviewUpdateRequestDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppPreviewUpdateRequestData {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': json['attributes'] == null ? undefined : AppPreviewUpdateRequestDataAttributesFromJSON(json['attributes']),
    };
}

export function AppPreviewUpdateRequestDataToJSON(json: any): AppPreviewUpdateRequestData {
    return AppPreviewUpdateRequestDataToJSONTyped(json, false);
}

export function AppPreviewUpdateRequestDataToJSONTyped(value?: AppPreviewUpdateRequestData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
        'attributes': AppPreviewUpdateRequestDataAttributesToJSON(value['attributes']),
    };
}

