/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppRelationshipsPreReleaseVersionsDataInner
 */
export interface AppRelationshipsPreReleaseVersionsDataInner {
    /**
     * 
     * @type {string}
     * @memberof AppRelationshipsPreReleaseVersionsDataInner
     */
    type: AppRelationshipsPreReleaseVersionsDataInnerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AppRelationshipsPreReleaseVersionsDataInner
     */
    id: string;
}


/**
 * @export
 */
export const AppRelationshipsPreReleaseVersionsDataInnerTypeEnum = {
    PreReleaseVersions: 'preReleaseVersions'
} as const;
export type AppRelationshipsPreReleaseVersionsDataInnerTypeEnum = typeof AppRelationshipsPreReleaseVersionsDataInnerTypeEnum[keyof typeof AppRelationshipsPreReleaseVersionsDataInnerTypeEnum];


/**
 * Check if a given object implements the AppRelationshipsPreReleaseVersionsDataInner interface.
 */
export function instanceOfAppRelationshipsPreReleaseVersionsDataInner(value: object): value is AppRelationshipsPreReleaseVersionsDataInner {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function AppRelationshipsPreReleaseVersionsDataInnerFromJSON(json: any): AppRelationshipsPreReleaseVersionsDataInner {
    return AppRelationshipsPreReleaseVersionsDataInnerFromJSONTyped(json, false);
}

export function AppRelationshipsPreReleaseVersionsDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppRelationshipsPreReleaseVersionsDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
    };
}

export function AppRelationshipsPreReleaseVersionsDataInnerToJSON(json: any): AppRelationshipsPreReleaseVersionsDataInner {
    return AppRelationshipsPreReleaseVersionsDataInnerToJSONTyped(json, false);
}

export function AppRelationshipsPreReleaseVersionsDataInnerToJSONTyped(value?: AppRelationshipsPreReleaseVersionsDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
    };
}

