
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppStoreReviewDetailUpdateRequestData } from './AppStoreReviewDetailUpdateRequestData';
import {
    AppStoreReviewDetailUpdateRequestDataFromJSON,
    AppStoreReviewDetailUpdateRequestDataFromJSONTyped,
    AppStoreReviewDetailUpdateRequestDataToJSON,
    AppStoreReviewDetailUpdateRequestDataToJSONTyped,
} from './AppStoreReviewDetailUpdateRequestData';

/**
 * 
 * @export
 * @interface AppStoreReviewDetailUpdateRequest
 */
export interface AppStoreReviewDetailUpdateRequest {
    /**
     * 
     * @type {AppStoreReviewDetailUpdateRequestData}
     * @memberof AppStoreReviewDetailUpdateRequest
     */
    data: AppStoreReviewDetailUpdateRequestData;
}

/**
 * Check if a given object implements the AppStoreReviewDetailUpdateRequest interface.
 */
export function instanceOfAppStoreReviewDetailUpdateRequest(value: object): value is AppStoreReviewDetailUpdateRequest {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AppStoreReviewDetailUpdateRequestFromJSON(json: any): AppStoreReviewDetailUpdateRequest {
    return AppStoreReviewDetailUpdateRequestFromJSONTyped(json, false);
}

export function AppStoreReviewDetailUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppStoreReviewDetailUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'data': AppStoreReviewDetailUpdateRequestDataFromJSON(json['data']),
    };
}

export function AppStoreReviewDetailUpdateRequestToJSON(json: any): AppStoreReviewDetailUpdateRequest {
    return AppStoreReviewDetailUpdateRequestToJSONTyped(json, false);
}

export function AppStoreReviewDetailUpdateRequestToJSONTyped(value?: AppStoreReviewDetailUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': AppStoreReviewDetailUpdateRequestDataToJSON(value['data']),
    };
}

