/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppStoreVersionExperimentTreatmentLocalizationAttributes
 */
export interface AppStoreVersionExperimentTreatmentLocalizationAttributes {
    /**
     * 
     * @type {string}
     * @memberof AppStoreVersionExperimentTreatmentLocalizationAttributes
     */
    locale?: string;
}

/**
 * Check if a given object implements the AppStoreVersionExperimentTreatmentLocalizationAttributes interface.
 */
export function instanceOfAppStoreVersionExperimentTreatmentLocalizationAttributes(value: object): value is AppStoreVersionExperimentTreatmentLocalizationAttributes {
    return true;
}

export function AppStoreVersionExperimentTreatmentLocalizationAttributesFromJSON(json: any): AppStoreVersionExperimentTreatmentLocalizationAttributes {
    return AppStoreVersionExperimentTreatmentLocalizationAttributesFromJSONTyped(json, false);
}

export function AppStoreVersionExperimentTreatmentLocalizationAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppStoreVersionExperimentTreatmentLocalizationAttributes {
    if (json == null) {
        return json;
    }
    return {
        
        'locale': json['locale'] == null ? undefined : json['locale'],
    };
}

export function AppStoreVersionExperimentTreatmentLocalizationAttributesToJSON(json: any): AppStoreVersionExperimentTreatmentLocalizationAttributes {
    return AppStoreVersionExperimentTreatmentLocalizationAttributesToJSONTyped(json, false);
}

export function AppStoreVersionExperimentTreatmentLocalizationAttributesToJSONTyped(value?: AppStoreVersionExperimentTreatmentLocalizationAttributes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'locale': value['locale'],
    };
}

