
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AlternativeDistributionPackageCreateRequestDataRelationships } from './AlternativeDistributionPackageCreateRequestDataRelationships';
import {
    AlternativeDistributionPackageCreateRequestDataRelationshipsFromJSON,
    AlternativeDistributionPackageCreateRequestDataRelationshipsFromJSONTyped,
    AlternativeDistributionPackageCreateRequestDataRelationshipsToJSON,
    AlternativeDistributionPackageCreateRequestDataRelationshipsToJSONTyped,
} from './AlternativeDistributionPackageCreateRequestDataRelationships';

/**
 * 
 * @export
 * @interface AppStoreVersionReleaseRequestCreateRequestData
 */
export interface AppStoreVersionReleaseRequestCreateRequestData {
    /**
     * 
     * @type {string}
     * @memberof AppStoreVersionReleaseRequestCreateRequestData
     */
    type: AppStoreVersionReleaseRequestCreateRequestDataTypeEnum;
    /**
     * 
     * @type {AlternativeDistributionPackageCreateRequestDataRelationships}
     * @memberof AppStoreVersionReleaseRequestCreateRequestData
     */
    relationships: AlternativeDistributionPackageCreateRequestDataRelationships;
}


/**
 * @export
 */
export const AppStoreVersionReleaseRequestCreateRequestDataTypeEnum = {
    AppStoreVersionReleaseRequests: 'appStoreVersionReleaseRequests'
} as const;
export type AppStoreVersionReleaseRequestCreateRequestDataTypeEnum = typeof AppStoreVersionReleaseRequestCreateRequestDataTypeEnum[keyof typeof AppStoreVersionReleaseRequestCreateRequestDataTypeEnum];


/**
 * Check if a given object implements the AppStoreVersionReleaseRequestCreateRequestData interface.
 */
export function instanceOfAppStoreVersionReleaseRequestCreateRequestData(value: object): value is AppStoreVersionReleaseRequestCreateRequestData {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('relationships' in value) || value['relationships'] === undefined) return false;
    return true;
}

export function AppStoreVersionReleaseRequestCreateRequestDataFromJSON(json: any): AppStoreVersionReleaseRequestCreateRequestData {
    return AppStoreVersionReleaseRequestCreateRequestDataFromJSONTyped(json, false);
}

export function AppStoreVersionReleaseRequestCreateRequestDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppStoreVersionReleaseRequestCreateRequestData {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'relationships': AlternativeDistributionPackageCreateRequestDataRelationshipsFromJSON(json['relationships']),
    };
}

export function AppStoreVersionReleaseRequestCreateRequestDataToJSON(json: any): AppStoreVersionReleaseRequestCreateRequestData {
    return AppStoreVersionReleaseRequestCreateRequestDataToJSONTyped(json, false);
}

export function AppStoreVersionReleaseRequestCreateRequestDataToJSONTyped(value?: AppStoreVersionReleaseRequestCreateRequestData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'relationships': AlternativeDistributionPackageCreateRequestDataRelationshipsToJSON(value['relationships']),
    };
}

