/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks } from './AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks';
import {
    AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinksFromJSON,
    AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinksFromJSONTyped,
    AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinksToJSON,
    AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinksToJSONTyped,
} from './AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks';

/**
 * 
 * @export
 * @interface AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTesters
 */
export interface AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTesters {
    /**
     * 
     * @type {AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks}
     * @memberof AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTesters
     */
    links?: AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks;
    /**
     * 
     * @type {string}
     * @memberof AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTesters
     */
    data?: string;
}

/**
 * Check if a given object implements the AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTesters interface.
 */
export function instanceOfAppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTesters(value: object): value is AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTesters {
    return true;
}

export function AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersFromJSON(json: any): AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTesters {
    return AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersFromJSONTyped(json, false);
}

export function AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTesters {
    if (json == null) {
        return json;
    }
    return {
        
        'links': json['links'] == null ? undefined : AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinksFromJSON(json['links']),
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersToJSON(json: any): AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTesters {
    return AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersToJSONTyped(json, false);
}

export function AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersToJSONTyped(value?: AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTesters | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'links': AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinksToJSON(value['links']),
        'data': value['data'],
    };
}

