
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppStoreVersionExperimentTreatmentCreateRequestDataRelationships } from './AppStoreVersionExperimentTreatmentCreateRequestDataRelationships';
import {
    AppStoreVersionExperimentTreatmentCreateRequestDataRelationshipsFromJSON,
    AppStoreVersionExperimentTreatmentCreateRequestDataRelationshipsFromJSONTyped,
    AppStoreVersionExperimentTreatmentCreateRequestDataRelationshipsToJSON,
    AppStoreVersionExperimentTreatmentCreateRequestDataRelationshipsToJSONTyped,
} from './AppStoreVersionExperimentTreatmentCreateRequestDataRelationships';
import type { AppStoreVersionExperimentTreatmentCreateRequestDataAttributes } from './AppStoreVersionExperimentTreatmentCreateRequestDataAttributes';
import {
    AppStoreVersionExperimentTreatmentCreateRequestDataAttributesFromJSON,
    AppStoreVersionExperimentTreatmentCreateRequestDataAttributesFromJSONTyped,
    AppStoreVersionExperimentTreatmentCreateRequestDataAttributesToJSON,
    AppStoreVersionExperimentTreatmentCreateRequestDataAttributesToJSONTyped,
} from './AppStoreVersionExperimentTreatmentCreateRequestDataAttributes';

/**
 * 
 * @export
 * @interface AppStoreVersionExperimentTreatmentCreateRequestData
 */
export interface AppStoreVersionExperimentTreatmentCreateRequestData {
    /**
     * 
     * @type {string}
     * @memberof AppStoreVersionExperimentTreatmentCreateRequestData
     */
    type: AppStoreVersionExperimentTreatmentCreateRequestDataTypeEnum;
    /**
     * 
     * @type {AppStoreVersionExperimentTreatmentCreateRequestDataAttributes}
     * @memberof AppStoreVersionExperimentTreatmentCreateRequestData
     */
    attributes: AppStoreVersionExperimentTreatmentCreateRequestDataAttributes;
    /**
     * 
     * @type {AppStoreVersionExperimentTreatmentCreateRequestDataRelationships}
     * @memberof AppStoreVersionExperimentTreatmentCreateRequestData
     */
    relationships?: AppStoreVersionExperimentTreatmentCreateRequestDataRelationships;
}


/**
 * @export
 */
export const AppStoreVersionExperimentTreatmentCreateRequestDataTypeEnum = {
    AppStoreVersionExperimentTreatments: 'appStoreVersionExperimentTreatments'
} as const;
export type AppStoreVersionExperimentTreatmentCreateRequestDataTypeEnum = typeof AppStoreVersionExperimentTreatmentCreateRequestDataTypeEnum[keyof typeof AppStoreVersionExperimentTreatmentCreateRequestDataTypeEnum];


/**
 * Check if a given object implements the AppStoreVersionExperimentTreatmentCreateRequestData interface.
 */
export function instanceOfAppStoreVersionExperimentTreatmentCreateRequestData(value: object): value is AppStoreVersionExperimentTreatmentCreateRequestData {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    return true;
}

export function AppStoreVersionExperimentTreatmentCreateRequestDataFromJSON(json: any): AppStoreVersionExperimentTreatmentCreateRequestData {
    return AppStoreVersionExperimentTreatmentCreateRequestDataFromJSONTyped(json, false);
}

export function AppStoreVersionExperimentTreatmentCreateRequestDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppStoreVersionExperimentTreatmentCreateRequestData {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'attributes': AppStoreVersionExperimentTreatmentCreateRequestDataAttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : AppStoreVersionExperimentTreatmentCreateRequestDataRelationshipsFromJSON(json['relationships']),
    };
}

export function AppStoreVersionExperimentTreatmentCreateRequestDataToJSON(json: any): AppStoreVersionExperimentTreatmentCreateRequestData {
    return AppStoreVersionExperimentTreatmentCreateRequestDataToJSONTyped(json, false);
}

export function AppStoreVersionExperimentTreatmentCreateRequestDataToJSONTyped(value?: AppStoreVersionExperimentTreatmentCreateRequestData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'attributes': AppStoreVersionExperimentTreatmentCreateRequestDataAttributesToJSON(value['attributes']),
        'relationships': AppStoreVersionExperimentTreatmentCreateRequestDataRelationshipsToJSON(value['relationships']),
    };
}

