
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourceLinks } from './ResourceLinks';
import {
    ResourceLinksFromJSON,
    ResourceLinksFromJSONTyped,
    ResourceLinksToJSON,
    ResourceLinksToJSONTyped,
} from './ResourceLinks';
import type { AppScreenshotSetAttributes } from './AppScreenshotSetAttributes';
import {
    AppScreenshotSetAttributesFromJSON,
    AppScreenshotSetAttributesFromJSONTyped,
    AppScreenshotSetAttributesToJSON,
    AppScreenshotSetAttributesToJSONTyped,
} from './AppScreenshotSetAttributes';
import type { AppScreenshotSetRelationships } from './AppScreenshotSetRelationships';
import {
    AppScreenshotSetRelationshipsFromJSON,
    AppScreenshotSetRelationshipsFromJSONTyped,
    AppScreenshotSetRelationshipsToJSON,
    AppScreenshotSetRelationshipsToJSONTyped,
} from './AppScreenshotSetRelationships';

/**
 * 
 * @export
 * @interface AppScreenshotSet
 */
export interface AppScreenshotSet {
    /**
     * 
     * @type {string}
     * @memberof AppScreenshotSet
     */
    type: AppScreenshotSetTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AppScreenshotSet
     */
    id: string;
    /**
     * 
     * @type {AppScreenshotSetAttributes}
     * @memberof AppScreenshotSet
     */
    attributes?: AppScreenshotSetAttributes;
    /**
     * 
     * @type {AppScreenshotSetRelationships}
     * @memberof AppScreenshotSet
     */
    relationships?: AppScreenshotSetRelationships;
    /**
     * 
     * @type {ResourceLinks}
     * @memberof AppScreenshotSet
     */
    links?: ResourceLinks;
}


/**
 * @export
 */
export const AppScreenshotSetTypeEnum = {
    AppScreenshotSets: 'appScreenshotSets'
} as const;
export type AppScreenshotSetTypeEnum = typeof AppScreenshotSetTypeEnum[keyof typeof AppScreenshotSetTypeEnum];


/**
 * Check if a given object implements the AppScreenshotSet interface.
 */
export function instanceOfAppScreenshotSet(value: object): value is AppScreenshotSet {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function AppScreenshotSetFromJSON(json: any): AppScreenshotSet {
    return AppScreenshotSetFromJSONTyped(json, false);
}

export function AppScreenshotSetFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppScreenshotSet {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': json['attributes'] == null ? undefined : AppScreenshotSetAttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : AppScreenshotSetRelationshipsFromJSON(json['relationships']),
        'links': json['links'] == null ? undefined : ResourceLinksFromJSON(json['links']),
    };
}

export function AppScreenshotSetToJSON(json: any): AppScreenshotSet {
    return AppScreenshotSetToJSONTyped(json, false);
}

export function AppScreenshotSetToJSONTyped(value?: AppScreenshotSet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
        'attributes': AppScreenshotSetAttributesToJSON(value['attributes']),
        'relationships': AppScreenshotSetRelationshipsToJSON(value['relationships']),
        'links': ResourceLinksToJSON(value['links']),
    };
}

