
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppEncryptionDeclarationRelationshipsBuildsDataInner } from './AppEncryptionDeclarationRelationshipsBuildsDataInner';
import {
    AppEncryptionDeclarationRelationshipsBuildsDataInnerFromJSON,
    AppEncryptionDeclarationRelationshipsBuildsDataInnerFromJSONTyped,
    AppEncryptionDeclarationRelationshipsBuildsDataInnerToJSON,
    AppEncryptionDeclarationRelationshipsBuildsDataInnerToJSONTyped,
} from './AppEncryptionDeclarationRelationshipsBuildsDataInner';

/**
 * 
 * @export
 * @interface AppStoreVersionBuildLinkageRequest
 */
export interface AppStoreVersionBuildLinkageRequest {
    /**
     * 
     * @type {AppEncryptionDeclarationRelationshipsBuildsDataInner}
     * @memberof AppStoreVersionBuildLinkageRequest
     */
    data: AppEncryptionDeclarationRelationshipsBuildsDataInner;
}

/**
 * Check if a given object implements the AppStoreVersionBuildLinkageRequest interface.
 */
export function instanceOfAppStoreVersionBuildLinkageRequest(value: object): value is AppStoreVersionBuildLinkageRequest {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AppStoreVersionBuildLinkageRequestFromJSON(json: any): AppStoreVersionBuildLinkageRequest {
    return AppStoreVersionBuildLinkageRequestFromJSONTyped(json, false);
}

export function AppStoreVersionBuildLinkageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppStoreVersionBuildLinkageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'data': AppEncryptionDeclarationRelationshipsBuildsDataInnerFromJSON(json['data']),
    };
}

export function AppStoreVersionBuildLinkageRequestToJSON(json: any): AppStoreVersionBuildLinkageRequest {
    return AppStoreVersionBuildLinkageRequestToJSONTyped(json, false);
}

export function AppStoreVersionBuildLinkageRequestToJSONTyped(value?: AppStoreVersionBuildLinkageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': AppEncryptionDeclarationRelationshipsBuildsDataInnerToJSON(value['data']),
    };
}

