
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppStoreVersionRelationshipsRoutingAppCoverageData
 */
export interface AppStoreVersionRelationshipsRoutingAppCoverageData {
    /**
     * 
     * @type {string}
     * @memberof AppStoreVersionRelationshipsRoutingAppCoverageData
     */
    type: AppStoreVersionRelationshipsRoutingAppCoverageDataTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AppStoreVersionRelationshipsRoutingAppCoverageData
     */
    id: string;
}


/**
 * @export
 */
export const AppStoreVersionRelationshipsRoutingAppCoverageDataTypeEnum = {
    RoutingAppCoverages: 'routingAppCoverages'
} as const;
export type AppStoreVersionRelationshipsRoutingAppCoverageDataTypeEnum = typeof AppStoreVersionRelationshipsRoutingAppCoverageDataTypeEnum[keyof typeof AppStoreVersionRelationshipsRoutingAppCoverageDataTypeEnum];


/**
 * Check if a given object implements the AppStoreVersionRelationshipsRoutingAppCoverageData interface.
 */
export function instanceOfAppStoreVersionRelationshipsRoutingAppCoverageData(value: object): value is AppStoreVersionRelationshipsRoutingAppCoverageData {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function AppStoreVersionRelationshipsRoutingAppCoverageDataFromJSON(json: any): AppStoreVersionRelationshipsRoutingAppCoverageData {
    return AppStoreVersionRelationshipsRoutingAppCoverageDataFromJSONTyped(json, false);
}

export function AppStoreVersionRelationshipsRoutingAppCoverageDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppStoreVersionRelationshipsRoutingAppCoverageData {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
    };
}

export function AppStoreVersionRelationshipsRoutingAppCoverageDataToJSON(json: any): AppStoreVersionRelationshipsRoutingAppCoverageData {
    return AppStoreVersionRelationshipsRoutingAppCoverageDataToJSONTyped(json, false);
}

export function AppStoreVersionRelationshipsRoutingAppCoverageDataToJSONTyped(value?: AppStoreVersionRelationshipsRoutingAppCoverageData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
    };
}

