/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Build } from './Build';
import {
    BuildFromJSON,
    BuildFromJSONTyped,
    BuildToJSON,
    BuildToJSONTyped,
} from './Build';
import type { BetaBuildLocalization } from './BetaBuildLocalization';
import {
    BetaBuildLocalizationFromJSON,
    BetaBuildLocalizationFromJSONTyped,
    BetaBuildLocalizationToJSON,
    BetaBuildLocalizationToJSONTyped,
} from './BetaBuildLocalization';
import type { DocumentLinks } from './DocumentLinks';
import {
    DocumentLinksFromJSON,
    DocumentLinksFromJSONTyped,
    DocumentLinksToJSON,
    DocumentLinksToJSONTyped,
} from './DocumentLinks';

/**
 * 
 * @export
 * @interface BetaBuildLocalizationResponse
 */
export interface BetaBuildLocalizationResponse {
    /**
     * 
     * @type {BetaBuildLocalization}
     * @memberof BetaBuildLocalizationResponse
     */
    data: BetaBuildLocalization;
    /**
     * 
     * @type {Array<Build>}
     * @memberof BetaBuildLocalizationResponse
     */
    included?: Array<Build>;
    /**
     * 
     * @type {DocumentLinks}
     * @memberof BetaBuildLocalizationResponse
     */
    links: DocumentLinks;
}

/**
 * Check if a given object implements the BetaBuildLocalizationResponse interface.
 */
export function instanceOfBetaBuildLocalizationResponse(value: object): value is BetaBuildLocalizationResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('links' in value) || value['links'] === undefined) return false;
    return true;
}

export function BetaBuildLocalizationResponseFromJSON(json: any): BetaBuildLocalizationResponse {
    return BetaBuildLocalizationResponseFromJSONTyped(json, false);
}

export function BetaBuildLocalizationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetaBuildLocalizationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': BetaBuildLocalizationFromJSON(json['data']),
        'included': json['included'] == null ? undefined : ((json['included'] as Array<any>).map(BuildFromJSON)),
        'links': DocumentLinksFromJSON(json['links']),
    };
}

export function BetaBuildLocalizationResponseToJSON(json: any): BetaBuildLocalizationResponse {
    return BetaBuildLocalizationResponseToJSONTyped(json, false);
}

export function BetaBuildLocalizationResponseToJSONTyped(value?: BetaBuildLocalizationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': BetaBuildLocalizationToJSON(value['data']),
        'included': value['included'] == null ? undefined : ((value['included'] as Array<any>).map(BuildToJSON)),
        'links': DocumentLinksToJSON(value['links']),
    };
}

