/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BetaAppLocalizationRelationshipsApp } from './BetaAppLocalizationRelationshipsApp';
import {
    BetaAppLocalizationRelationshipsAppFromJSON,
    BetaAppLocalizationRelationshipsAppFromJSONTyped,
    BetaAppLocalizationRelationshipsAppToJSON,
    BetaAppLocalizationRelationshipsAppToJSONTyped,
} from './BetaAppLocalizationRelationshipsApp';

/**
 * 
 * @export
 * @interface BetaAppLocalizationRelationships
 */
export interface BetaAppLocalizationRelationships {
    /**
     * 
     * @type {BetaAppLocalizationRelationshipsApp}
     * @memberof BetaAppLocalizationRelationships
     */
    app?: BetaAppLocalizationRelationshipsApp;
}

/**
 * Check if a given object implements the BetaAppLocalizationRelationships interface.
 */
export function instanceOfBetaAppLocalizationRelationships(value: object): value is BetaAppLocalizationRelationships {
    return true;
}

export function BetaAppLocalizationRelationshipsFromJSON(json: any): BetaAppLocalizationRelationships {
    return BetaAppLocalizationRelationshipsFromJSONTyped(json, false);
}

export function BetaAppLocalizationRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetaAppLocalizationRelationships {
    if (json == null) {
        return json;
    }
    return {
        
        'app': json['app'] == null ? undefined : BetaAppLocalizationRelationshipsAppFromJSON(json['app']),
    };
}

export function BetaAppLocalizationRelationshipsToJSON(json: any): BetaAppLocalizationRelationships {
    return BetaAppLocalizationRelationshipsToJSONTyped(json, false);
}

export function BetaAppLocalizationRelationshipsToJSONTyped(value?: BetaAppLocalizationRelationships | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app': BetaAppLocalizationRelationshipsAppToJSON(value['app']),
    };
}

