
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BetaGroupAttributes } from './BetaGroupAttributes';
import {
    BetaGroupAttributesFromJSON,
    BetaGroupAttributesFromJSONTyped,
    BetaGroupAttributesToJSON,
    BetaGroupAttributesToJSONTyped,
} from './BetaGroupAttributes';
import type { BetaGroupRelationships } from './BetaGroupRelationships';
import {
    BetaGroupRelationshipsFromJSON,
    BetaGroupRelationshipsFromJSONTyped,
    BetaGroupRelationshipsToJSON,
    BetaGroupRelationshipsToJSONTyped,
} from './BetaGroupRelationships';
import type { ResourceLinks } from './ResourceLinks';
import {
    ResourceLinksFromJSON,
    ResourceLinksFromJSONTyped,
    ResourceLinksToJSON,
    ResourceLinksToJSONTyped,
} from './ResourceLinks';

/**
 * 
 * @export
 * @interface BetaGroup
 */
export interface BetaGroup {
    /**
     * 
     * @type {string}
     * @memberof BetaGroup
     */
    type: BetaGroupTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof BetaGroup
     */
    id: string;
    /**
     * 
     * @type {BetaGroupAttributes}
     * @memberof BetaGroup
     */
    attributes?: BetaGroupAttributes;
    /**
     * 
     * @type {BetaGroupRelationships}
     * @memberof BetaGroup
     */
    relationships?: BetaGroupRelationships;
    /**
     * 
     * @type {ResourceLinks}
     * @memberof BetaGroup
     */
    links?: ResourceLinks;
}


/**
 * @export
 */
export const BetaGroupTypeEnum = {
    BetaGroups: 'betaGroups'
} as const;
export type BetaGroupTypeEnum = typeof BetaGroupTypeEnum[keyof typeof BetaGroupTypeEnum];


/**
 * Check if a given object implements the BetaGroup interface.
 */
export function instanceOfBetaGroup(value: object): value is BetaGroup {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function BetaGroupFromJSON(json: any): BetaGroup {
    return BetaGroupFromJSONTyped(json, false);
}

export function BetaGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetaGroup {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': json['attributes'] == null ? undefined : BetaGroupAttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : BetaGroupRelationshipsFromJSON(json['relationships']),
        'links': json['links'] == null ? undefined : ResourceLinksFromJSON(json['links']),
    };
}

export function BetaGroupToJSON(json: any): BetaGroup {
    return BetaGroupToJSONTyped(json, false);
}

export function BetaGroupToJSONTyped(value?: BetaGroup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
        'attributes': BetaGroupAttributesToJSON(value['attributes']),
        'relationships': BetaGroupRelationshipsToJSON(value['relationships']),
        'links': ResourceLinksToJSON(value['links']),
    };
}

