/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BetaGroupCreateRequestDataAttributes
 */
export interface BetaGroupCreateRequestDataAttributes {
    /**
     * 
     * @type {string}
     * @memberof BetaGroupCreateRequestDataAttributes
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof BetaGroupCreateRequestDataAttributes
     */
    isInternalGroup?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BetaGroupCreateRequestDataAttributes
     */
    hasAccessToAllBuilds?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BetaGroupCreateRequestDataAttributes
     */
    publicLinkEnabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BetaGroupCreateRequestDataAttributes
     */
    publicLinkLimitEnabled?: boolean;
    /**
     * 
     * @type {number}
     * @memberof BetaGroupCreateRequestDataAttributes
     */
    publicLinkLimit?: number;
    /**
     * 
     * @type {boolean}
     * @memberof BetaGroupCreateRequestDataAttributes
     */
    feedbackEnabled?: boolean;
}

/**
 * Check if a given object implements the BetaGroupCreateRequestDataAttributes interface.
 */
export function instanceOfBetaGroupCreateRequestDataAttributes(value: object): value is BetaGroupCreateRequestDataAttributes {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function BetaGroupCreateRequestDataAttributesFromJSON(json: any): BetaGroupCreateRequestDataAttributes {
    return BetaGroupCreateRequestDataAttributesFromJSONTyped(json, false);
}

export function BetaGroupCreateRequestDataAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetaGroupCreateRequestDataAttributes {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'isInternalGroup': json['isInternalGroup'] == null ? undefined : json['isInternalGroup'],
        'hasAccessToAllBuilds': json['hasAccessToAllBuilds'] == null ? undefined : json['hasAccessToAllBuilds'],
        'publicLinkEnabled': json['publicLinkEnabled'] == null ? undefined : json['publicLinkEnabled'],
        'publicLinkLimitEnabled': json['publicLinkLimitEnabled'] == null ? undefined : json['publicLinkLimitEnabled'],
        'publicLinkLimit': json['publicLinkLimit'] == null ? undefined : json['publicLinkLimit'],
        'feedbackEnabled': json['feedbackEnabled'] == null ? undefined : json['feedbackEnabled'],
    };
}

export function BetaGroupCreateRequestDataAttributesToJSON(json: any): BetaGroupCreateRequestDataAttributes {
    return BetaGroupCreateRequestDataAttributesToJSONTyped(json, false);
}

export function BetaGroupCreateRequestDataAttributesToJSONTyped(value?: BetaGroupCreateRequestDataAttributes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'isInternalGroup': value['isInternalGroup'],
        'hasAccessToAllBuilds': value['hasAccessToAllBuilds'],
        'publicLinkEnabled': value['publicLinkEnabled'],
        'publicLinkLimitEnabled': value['publicLinkLimitEnabled'],
        'publicLinkLimit': value['publicLinkLimit'],
        'feedbackEnabled': value['feedbackEnabled'],
    };
}

