
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BetaAppClipInvocationUpdateRequestData } from './BetaAppClipInvocationUpdateRequestData';
import {
    BetaAppClipInvocationUpdateRequestDataFromJSON,
    BetaAppClipInvocationUpdateRequestDataFromJSONTyped,
    BetaAppClipInvocationUpdateRequestDataToJSON,
    BetaAppClipInvocationUpdateRequestDataToJSONTyped,
} from './BetaAppClipInvocationUpdateRequestData';

/**
 * 
 * @export
 * @interface BetaAppClipInvocationUpdateRequest
 */
export interface BetaAppClipInvocationUpdateRequest {
    /**
     * 
     * @type {BetaAppClipInvocationUpdateRequestData}
     * @memberof BetaAppClipInvocationUpdateRequest
     */
    data: BetaAppClipInvocationUpdateRequestData;
}

/**
 * Check if a given object implements the BetaAppClipInvocationUpdateRequest interface.
 */
export function instanceOfBetaAppClipInvocationUpdateRequest(value: object): value is BetaAppClipInvocationUpdateRequest {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function BetaAppClipInvocationUpdateRequestFromJSON(json: any): BetaAppClipInvocationUpdateRequest {
    return BetaAppClipInvocationUpdateRequestFromJSONTyped(json, false);
}

export function BetaAppClipInvocationUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetaAppClipInvocationUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'data': BetaAppClipInvocationUpdateRequestDataFromJSON(json['data']),
    };
}

export function BetaAppClipInvocationUpdateRequestToJSON(json: any): BetaAppClipInvocationUpdateRequest {
    return BetaAppClipInvocationUpdateRequestToJSONTyped(json, false);
}

export function BetaAppClipInvocationUpdateRequestToJSONTyped(value?: BetaAppClipInvocationUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': BetaAppClipInvocationUpdateRequestDataToJSON(value['data']),
    };
}

