/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BetaTesterCreateRequestDataAttributes
 */
export interface BetaTesterCreateRequestDataAttributes {
    /**
     * 
     * @type {string}
     * @memberof BetaTesterCreateRequestDataAttributes
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof BetaTesterCreateRequestDataAttributes
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof BetaTesterCreateRequestDataAttributes
     */
    email: string;
}

/**
 * Check if a given object implements the BetaTesterCreateRequestDataAttributes interface.
 */
export function instanceOfBetaTesterCreateRequestDataAttributes(value: object): value is BetaTesterCreateRequestDataAttributes {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function BetaTesterCreateRequestDataAttributesFromJSON(json: any): BetaTesterCreateRequestDataAttributes {
    return BetaTesterCreateRequestDataAttributesFromJSONTyped(json, false);
}

export function BetaTesterCreateRequestDataAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetaTesterCreateRequestDataAttributes {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'email': json['email'],
    };
}

export function BetaTesterCreateRequestDataAttributesToJSON(json: any): BetaTesterCreateRequestDataAttributes {
    return BetaTesterCreateRequestDataAttributesToJSONTyped(json, false);
}

export function BetaTesterCreateRequestDataAttributesToJSONTyped(value?: BetaTesterCreateRequestDataAttributes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'email': value['email'],
    };
}

