/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BetaAppClipInvocationLocalization } from './BetaAppClipInvocationLocalization';
import {
    BetaAppClipInvocationLocalizationFromJSON,
    BetaAppClipInvocationLocalizationFromJSONTyped,
    BetaAppClipInvocationLocalizationToJSON,
    BetaAppClipInvocationLocalizationToJSONTyped,
} from './BetaAppClipInvocationLocalization';
import type { PagingInformation } from './PagingInformation';
import {
    PagingInformationFromJSON,
    PagingInformationFromJSONTyped,
    PagingInformationToJSON,
    PagingInformationToJSONTyped,
} from './PagingInformation';
import type { BetaAppClipInvocation } from './BetaAppClipInvocation';
import {
    BetaAppClipInvocationFromJSON,
    BetaAppClipInvocationFromJSONTyped,
    BetaAppClipInvocationToJSON,
    BetaAppClipInvocationToJSONTyped,
} from './BetaAppClipInvocation';
import type { PagedDocumentLinks } from './PagedDocumentLinks';
import {
    PagedDocumentLinksFromJSON,
    PagedDocumentLinksFromJSONTyped,
    PagedDocumentLinksToJSON,
    PagedDocumentLinksToJSONTyped,
} from './PagedDocumentLinks';

/**
 * 
 * @export
 * @interface BetaAppClipInvocationsResponse
 */
export interface BetaAppClipInvocationsResponse {
    /**
     * 
     * @type {Array<BetaAppClipInvocation>}
     * @memberof BetaAppClipInvocationsResponse
     */
    data: Array<BetaAppClipInvocation>;
    /**
     * 
     * @type {Array<BetaAppClipInvocationLocalization>}
     * @memberof BetaAppClipInvocationsResponse
     */
    included?: Array<BetaAppClipInvocationLocalization>;
    /**
     * 
     * @type {PagedDocumentLinks}
     * @memberof BetaAppClipInvocationsResponse
     */
    links: PagedDocumentLinks;
    /**
     * 
     * @type {PagingInformation}
     * @memberof BetaAppClipInvocationsResponse
     */
    meta?: PagingInformation;
}

/**
 * Check if a given object implements the BetaAppClipInvocationsResponse interface.
 */
export function instanceOfBetaAppClipInvocationsResponse(value: object): value is BetaAppClipInvocationsResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('links' in value) || value['links'] === undefined) return false;
    return true;
}

export function BetaAppClipInvocationsResponseFromJSON(json: any): BetaAppClipInvocationsResponse {
    return BetaAppClipInvocationsResponseFromJSONTyped(json, false);
}

export function BetaAppClipInvocationsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetaAppClipInvocationsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(BetaAppClipInvocationFromJSON)),
        'included': json['included'] == null ? undefined : ((json['included'] as Array<any>).map(BetaAppClipInvocationLocalizationFromJSON)),
        'links': PagedDocumentLinksFromJSON(json['links']),
        'meta': json['meta'] == null ? undefined : PagingInformationFromJSON(json['meta']),
    };
}

export function BetaAppClipInvocationsResponseToJSON(json: any): BetaAppClipInvocationsResponse {
    return BetaAppClipInvocationsResponseToJSONTyped(json, false);
}

export function BetaAppClipInvocationsResponseToJSONTyped(value?: BetaAppClipInvocationsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(BetaAppClipInvocationToJSON)),
        'included': value['included'] == null ? undefined : ((value['included'] as Array<any>).map(BetaAppClipInvocationLocalizationToJSON)),
        'links': PagedDocumentLinksToJSON(value['links']),
        'meta': PagingInformationToJSON(value['meta']),
    };
}

