/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourceLinks } from './ResourceLinks';
import {
    ResourceLinksFromJSON,
    ResourceLinksFromJSONTyped,
    ResourceLinksToJSON,
    ResourceLinksToJSONTyped,
} from './ResourceLinks';
import type { BuildBundleFileSizeAttributes } from './BuildBundleFileSizeAttributes';
import {
    BuildBundleFileSizeAttributesFromJSON,
    BuildBundleFileSizeAttributesFromJSONTyped,
    BuildBundleFileSizeAttributesToJSON,
    BuildBundleFileSizeAttributesToJSONTyped,
} from './BuildBundleFileSizeAttributes';

/**
 * 
 * @export
 * @interface BuildBundleFileSize
 */
export interface BuildBundleFileSize {
    /**
     * 
     * @type {string}
     * @memberof BuildBundleFileSize
     */
    type: BuildBundleFileSizeTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof BuildBundleFileSize
     */
    id: string;
    /**
     * 
     * @type {BuildBundleFileSizeAttributes}
     * @memberof BuildBundleFileSize
     */
    attributes?: BuildBundleFileSizeAttributes;
    /**
     * 
     * @type {ResourceLinks}
     * @memberof BuildBundleFileSize
     */
    links?: ResourceLinks;
}


/**
 * @export
 */
export const BuildBundleFileSizeTypeEnum = {
    BuildBundleFileSizes: 'buildBundleFileSizes'
} as const;
export type BuildBundleFileSizeTypeEnum = typeof BuildBundleFileSizeTypeEnum[keyof typeof BuildBundleFileSizeTypeEnum];


/**
 * Check if a given object implements the BuildBundleFileSize interface.
 */
export function instanceOfBuildBundleFileSize(value: object): value is BuildBundleFileSize {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function BuildBundleFileSizeFromJSON(json: any): BuildBundleFileSize {
    return BuildBundleFileSizeFromJSONTyped(json, false);
}

export function BuildBundleFileSizeFromJSONTyped(json: any, ignoreDiscriminator: boolean): BuildBundleFileSize {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': json['attributes'] == null ? undefined : BuildBundleFileSizeAttributesFromJSON(json['attributes']),
        'links': json['links'] == null ? undefined : ResourceLinksFromJSON(json['links']),
    };
}

export function BuildBundleFileSizeToJSON(json: any): BuildBundleFileSize {
    return BuildBundleFileSizeToJSONTyped(json, false);
}

export function BuildBundleFileSizeToJSONTyped(value?: BuildBundleFileSize | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
        'attributes': BuildBundleFileSizeAttributesToJSON(value['attributes']),
        'links': ResourceLinksToJSON(value['links']),
    };
}

