/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PagingInformation } from './PagingInformation';
import {
    PagingInformationFromJSON,
    PagingInformationFromJSONTyped,
    PagingInformationToJSON,
    PagingInformationToJSONTyped,
} from './PagingInformation';
import type { BuildIcon } from './BuildIcon';
import {
    BuildIconFromJSON,
    BuildIconFromJSONTyped,
    BuildIconToJSON,
    BuildIconToJSONTyped,
} from './BuildIcon';
import type { PagedDocumentLinks } from './PagedDocumentLinks';
import {
    PagedDocumentLinksFromJSON,
    PagedDocumentLinksFromJSONTyped,
    PagedDocumentLinksToJSON,
    PagedDocumentLinksToJSONTyped,
} from './PagedDocumentLinks';

/**
 * 
 * @export
 * @interface BuildIconsResponse
 */
export interface BuildIconsResponse {
    /**
     * 
     * @type {Array<BuildIcon>}
     * @memberof BuildIconsResponse
     */
    data: Array<BuildIcon>;
    /**
     * 
     * @type {PagedDocumentLinks}
     * @memberof BuildIconsResponse
     */
    links: PagedDocumentLinks;
    /**
     * 
     * @type {PagingInformation}
     * @memberof BuildIconsResponse
     */
    meta?: PagingInformation;
}

/**
 * Check if a given object implements the BuildIconsResponse interface.
 */
export function instanceOfBuildIconsResponse(value: object): value is BuildIconsResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('links' in value) || value['links'] === undefined) return false;
    return true;
}

export function BuildIconsResponseFromJSON(json: any): BuildIconsResponse {
    return BuildIconsResponseFromJSONTyped(json, false);
}

export function BuildIconsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BuildIconsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(BuildIconFromJSON)),
        'links': PagedDocumentLinksFromJSON(json['links']),
        'meta': json['meta'] == null ? undefined : PagingInformationFromJSON(json['meta']),
    };
}

export function BuildIconsResponseToJSON(json: any): BuildIconsResponse {
    return BuildIconsResponseToJSONTyped(json, false);
}

export function BuildIconsResponseToJSONTyped(value?: BuildIconsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(BuildIconToJSON)),
        'links': PagedDocumentLinksToJSON(value['links']),
        'meta': PagingInformationToJSON(value['meta']),
    };
}

