/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const BundleIdPlatform = {
    Ios: 'IOS',
    MacOs: 'MAC_OS',
    Universal: 'UNIVERSAL'
} as const;
export type BundleIdPlatform = typeof BundleIdPlatform[keyof typeof BundleIdPlatform];


export function instanceOfBundleIdPlatform(value: any): boolean {
    for (const key in BundleIdPlatform) {
        if (Object.prototype.hasOwnProperty.call(BundleIdPlatform, key)) {
            if (BundleIdPlatform[key as keyof typeof BundleIdPlatform] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BundleIdPlatformFromJSON(json: any): BundleIdPlatform {
    return BundleIdPlatformFromJSONTyped(json, false);
}

export function BundleIdPlatformFromJSONTyped(json: any, ignoreDiscriminator: boolean): BundleIdPlatform {
    return json as BundleIdPlatform;
}

export function BundleIdPlatformToJSON(value?: BundleIdPlatform | null): any {
    return value as any;
}

export function BundleIdPlatformToJSONTyped(value: any, ignoreDiscriminator: boolean): BundleIdPlatform {
    return value as BundleIdPlatform;
}

