/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PagingInformation } from './PagingInformation';
import {
    PagingInformationFromJSON,
    PagingInformationFromJSONTyped,
    PagingInformationToJSON,
    PagingInformationToJSONTyped,
} from './PagingInformation';
import type { RelationshipLinks } from './RelationshipLinks';
import {
    RelationshipLinksFromJSON,
    RelationshipLinksFromJSONTyped,
    RelationshipLinksToJSON,
    RelationshipLinksToJSONTyped,
} from './RelationshipLinks';
import type { BundleIdRelationshipsProfilesDataInner } from './BundleIdRelationshipsProfilesDataInner';
import {
    BundleIdRelationshipsProfilesDataInnerFromJSON,
    BundleIdRelationshipsProfilesDataInnerFromJSONTyped,
    BundleIdRelationshipsProfilesDataInnerToJSON,
    BundleIdRelationshipsProfilesDataInnerToJSONTyped,
} from './BundleIdRelationshipsProfilesDataInner';

/**
 * 
 * @export
 * @interface BundleIdRelationshipsProfiles
 */
export interface BundleIdRelationshipsProfiles {
    /**
     * 
     * @type {RelationshipLinks}
     * @memberof BundleIdRelationshipsProfiles
     */
    links?: RelationshipLinks;
    /**
     * 
     * @type {PagingInformation}
     * @memberof BundleIdRelationshipsProfiles
     */
    meta?: PagingInformation;
    /**
     * 
     * @type {Array<BundleIdRelationshipsProfilesDataInner>}
     * @memberof BundleIdRelationshipsProfiles
     */
    data?: Array<BundleIdRelationshipsProfilesDataInner>;
}

/**
 * Check if a given object implements the BundleIdRelationshipsProfiles interface.
 */
export function instanceOfBundleIdRelationshipsProfiles(value: object): value is BundleIdRelationshipsProfiles {
    return true;
}

export function BundleIdRelationshipsProfilesFromJSON(json: any): BundleIdRelationshipsProfiles {
    return BundleIdRelationshipsProfilesFromJSONTyped(json, false);
}

export function BundleIdRelationshipsProfilesFromJSONTyped(json: any, ignoreDiscriminator: boolean): BundleIdRelationshipsProfiles {
    if (json == null) {
        return json;
    }
    return {
        
        'links': json['links'] == null ? undefined : RelationshipLinksFromJSON(json['links']),
        'meta': json['meta'] == null ? undefined : PagingInformationFromJSON(json['meta']),
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(BundleIdRelationshipsProfilesDataInnerFromJSON)),
    };
}

export function BundleIdRelationshipsProfilesToJSON(json: any): BundleIdRelationshipsProfiles {
    return BundleIdRelationshipsProfilesToJSONTyped(json, false);
}

export function BundleIdRelationshipsProfilesToJSONTyped(value?: BundleIdRelationshipsProfiles | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'links': RelationshipLinksToJSON(value['links']),
        'meta': PagingInformationToJSON(value['meta']),
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(BundleIdRelationshipsProfilesDataInnerToJSON)),
    };
}

