/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BundleIdCapability } from './BundleIdCapability';
import {
    BundleIdCapabilityFromJSON,
    BundleIdCapabilityFromJSONTyped,
    BundleIdCapabilityToJSON,
    BundleIdCapabilityToJSONTyped,
} from './BundleIdCapability';
import type { DocumentLinks } from './DocumentLinks';
import {
    DocumentLinksFromJSON,
    DocumentLinksFromJSONTyped,
    DocumentLinksToJSON,
    DocumentLinksToJSONTyped,
} from './DocumentLinks';

/**
 * 
 * @export
 * @interface BundleIdCapabilityResponse
 */
export interface BundleIdCapabilityResponse {
    /**
     * 
     * @type {BundleIdCapability}
     * @memberof BundleIdCapabilityResponse
     */
    data: BundleIdCapability;
    /**
     * 
     * @type {DocumentLinks}
     * @memberof BundleIdCapabilityResponse
     */
    links: DocumentLinks;
}

/**
 * Check if a given object implements the BundleIdCapabilityResponse interface.
 */
export function instanceOfBundleIdCapabilityResponse(value: object): value is BundleIdCapabilityResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('links' in value) || value['links'] === undefined) return false;
    return true;
}

export function BundleIdCapabilityResponseFromJSON(json: any): BundleIdCapabilityResponse {
    return BundleIdCapabilityResponseFromJSONTyped(json, false);
}

export function BundleIdCapabilityResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BundleIdCapabilityResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': BundleIdCapabilityFromJSON(json['data']),
        'links': DocumentLinksFromJSON(json['links']),
    };
}

export function BundleIdCapabilityResponseToJSON(json: any): BundleIdCapabilityResponse {
    return BundleIdCapabilityResponseToJSONTyped(json, false);
}

export function BundleIdCapabilityResponseToJSONTyped(value?: BundleIdCapabilityResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': BundleIdCapabilityToJSON(value['data']),
        'links': DocumentLinksToJSON(value['links']),
    };
}

