
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BundleIdCapabilityAttributes } from './BundleIdCapabilityAttributes';
import {
    BundleIdCapabilityAttributesFromJSON,
    BundleIdCapabilityAttributesFromJSONTyped,
    BundleIdCapabilityAttributesToJSON,
    BundleIdCapabilityAttributesToJSONTyped,
} from './BundleIdCapabilityAttributes';

/**
 * 
 * @export
 * @interface BundleIdCapabilityUpdateRequestData
 */
export interface BundleIdCapabilityUpdateRequestData {
    /**
     * 
     * @type {string}
     * @memberof BundleIdCapabilityUpdateRequestData
     */
    type: BundleIdCapabilityUpdateRequestDataTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof BundleIdCapabilityUpdateRequestData
     */
    id: string;
    /**
     * 
     * @type {BundleIdCapabilityAttributes}
     * @memberof BundleIdCapabilityUpdateRequestData
     */
    attributes?: BundleIdCapabilityAttributes;
}


/**
 * @export
 */
export const BundleIdCapabilityUpdateRequestDataTypeEnum = {
    BundleIdCapabilities: 'bundleIdCapabilities'
} as const;
export type BundleIdCapabilityUpdateRequestDataTypeEnum = typeof BundleIdCapabilityUpdateRequestDataTypeEnum[keyof typeof BundleIdCapabilityUpdateRequestDataTypeEnum];


/**
 * Check if a given object implements the BundleIdCapabilityUpdateRequestData interface.
 */
export function instanceOfBundleIdCapabilityUpdateRequestData(value: object): value is BundleIdCapabilityUpdateRequestData {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function BundleIdCapabilityUpdateRequestDataFromJSON(json: any): BundleIdCapabilityUpdateRequestData {
    return BundleIdCapabilityUpdateRequestDataFromJSONTyped(json, false);
}

export function BundleIdCapabilityUpdateRequestDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): BundleIdCapabilityUpdateRequestData {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': json['attributes'] == null ? undefined : BundleIdCapabilityAttributesFromJSON(json['attributes']),
    };
}

export function BundleIdCapabilityUpdateRequestDataToJSON(json: any): BundleIdCapabilityUpdateRequestData {
    return BundleIdCapabilityUpdateRequestDataToJSONTyped(json, false);
}

export function BundleIdCapabilityUpdateRequestDataToJSONTyped(value?: BundleIdCapabilityUpdateRequestData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
        'attributes': BundleIdCapabilityAttributesToJSON(value['attributes']),
    };
}

