
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CiBuildRunRelationshipsPullRequestData } from './CiBuildRunRelationshipsPullRequestData';
import {
    CiBuildRunRelationshipsPullRequestDataFromJSON,
    CiBuildRunRelationshipsPullRequestDataFromJSONTyped,
    CiBuildRunRelationshipsPullRequestDataToJSON,
    CiBuildRunRelationshipsPullRequestDataToJSONTyped,
} from './CiBuildRunRelationshipsPullRequestData';

/**
 * 
 * @export
 * @interface CiBuildRunRelationshipsPullRequest
 */
export interface CiBuildRunRelationshipsPullRequest {
    /**
     * 
     * @type {CiBuildRunRelationshipsPullRequestData}
     * @memberof CiBuildRunRelationshipsPullRequest
     */
    data?: CiBuildRunRelationshipsPullRequestData;
}

/**
 * Check if a given object implements the CiBuildRunRelationshipsPullRequest interface.
 */
export function instanceOfCiBuildRunRelationshipsPullRequest(value: object): value is CiBuildRunRelationshipsPullRequest {
    return true;
}

export function CiBuildRunRelationshipsPullRequestFromJSON(json: any): CiBuildRunRelationshipsPullRequest {
    return CiBuildRunRelationshipsPullRequestFromJSONTyped(json, false);
}

export function CiBuildRunRelationshipsPullRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CiBuildRunRelationshipsPullRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : CiBuildRunRelationshipsPullRequestDataFromJSON(json['data']),
    };
}

export function CiBuildRunRelationshipsPullRequestToJSON(json: any): CiBuildRunRelationshipsPullRequest {
    return CiBuildRunRelationshipsPullRequestToJSONTyped(json, false);
}

export function CiBuildRunRelationshipsPullRequestToJSONTyped(value?: CiBuildRunRelationshipsPullRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': CiBuildRunRelationshipsPullRequestDataToJSON(value['data']),
    };
}

