/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CiMacOsVersionRelationshipsXcodeVersions } from './CiMacOsVersionRelationshipsXcodeVersions';
import {
    CiMacOsVersionRelationshipsXcodeVersionsFromJSON,
    CiMacOsVersionRelationshipsXcodeVersionsFromJSONTyped,
    CiMacOsVersionRelationshipsXcodeVersionsToJSON,
    CiMacOsVersionRelationshipsXcodeVersionsToJSONTyped,
} from './CiMacOsVersionRelationshipsXcodeVersions';

/**
 * 
 * @export
 * @interface CiMacOsVersionRelationships
 */
export interface CiMacOsVersionRelationships {
    /**
     * 
     * @type {CiMacOsVersionRelationshipsXcodeVersions}
     * @memberof CiMacOsVersionRelationships
     */
    xcodeVersions?: CiMacOsVersionRelationshipsXcodeVersions;
}

/**
 * Check if a given object implements the CiMacOsVersionRelationships interface.
 */
export function instanceOfCiMacOsVersionRelationships(value: object): value is CiMacOsVersionRelationships {
    return true;
}

export function CiMacOsVersionRelationshipsFromJSON(json: any): CiMacOsVersionRelationships {
    return CiMacOsVersionRelationshipsFromJSONTyped(json, false);
}

export function CiMacOsVersionRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CiMacOsVersionRelationships {
    if (json == null) {
        return json;
    }
    return {
        
        'xcodeVersions': json['xcodeVersions'] == null ? undefined : CiMacOsVersionRelationshipsXcodeVersionsFromJSON(json['xcodeVersions']),
    };
}

export function CiMacOsVersionRelationshipsToJSON(json: any): CiMacOsVersionRelationships {
    return CiMacOsVersionRelationshipsToJSONTyped(json, false);
}

export function CiMacOsVersionRelationshipsToJSONTyped(value?: CiMacOsVersionRelationships | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'xcodeVersions': CiMacOsVersionRelationshipsXcodeVersionsToJSON(value['xcodeVersions']),
    };
}

