
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PagingInformation } from './PagingInformation';
import {
    PagingInformationFromJSON,
    PagingInformationFromJSONTyped,
    PagingInformationToJSON,
    PagingInformationToJSONTyped,
} from './PagingInformation';
import type { RelationshipLinks } from './RelationshipLinks';
import {
    RelationshipLinksFromJSON,
    RelationshipLinksFromJSONTyped,
    RelationshipLinksToJSON,
    RelationshipLinksToJSONTyped,
} from './RelationshipLinks';
import type { CiWorkflowRelationshipsMacOsVersionData } from './CiWorkflowRelationshipsMacOsVersionData';
import {
    CiWorkflowRelationshipsMacOsVersionDataFromJSON,
    CiWorkflowRelationshipsMacOsVersionDataFromJSONTyped,
    CiWorkflowRelationshipsMacOsVersionDataToJSON,
    CiWorkflowRelationshipsMacOsVersionDataToJSONTyped,
} from './CiWorkflowRelationshipsMacOsVersionData';

/**
 * 
 * @export
 * @interface CiXcodeVersionRelationshipsMacOsVersions
 */
export interface CiXcodeVersionRelationshipsMacOsVersions {
    /**
     * 
     * @type {RelationshipLinks}
     * @memberof CiXcodeVersionRelationshipsMacOsVersions
     */
    links?: RelationshipLinks;
    /**
     * 
     * @type {PagingInformation}
     * @memberof CiXcodeVersionRelationshipsMacOsVersions
     */
    meta?: PagingInformation;
    /**
     * 
     * @type {Array<CiWorkflowRelationshipsMacOsVersionData>}
     * @memberof CiXcodeVersionRelationshipsMacOsVersions
     */
    data?: Array<CiWorkflowRelationshipsMacOsVersionData>;
}

/**
 * Check if a given object implements the CiXcodeVersionRelationshipsMacOsVersions interface.
 */
export function instanceOfCiXcodeVersionRelationshipsMacOsVersions(value: object): value is CiXcodeVersionRelationshipsMacOsVersions {
    return true;
}

export function CiXcodeVersionRelationshipsMacOsVersionsFromJSON(json: any): CiXcodeVersionRelationshipsMacOsVersions {
    return CiXcodeVersionRelationshipsMacOsVersionsFromJSONTyped(json, false);
}

export function CiXcodeVersionRelationshipsMacOsVersionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CiXcodeVersionRelationshipsMacOsVersions {
    if (json == null) {
        return json;
    }
    return {
        
        'links': json['links'] == null ? undefined : RelationshipLinksFromJSON(json['links']),
        'meta': json['meta'] == null ? undefined : PagingInformationFromJSON(json['meta']),
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(CiWorkflowRelationshipsMacOsVersionDataFromJSON)),
    };
}

export function CiXcodeVersionRelationshipsMacOsVersionsToJSON(json: any): CiXcodeVersionRelationshipsMacOsVersions {
    return CiXcodeVersionRelationshipsMacOsVersionsToJSONTyped(json, false);
}

export function CiXcodeVersionRelationshipsMacOsVersionsToJSONTyped(value?: CiXcodeVersionRelationshipsMacOsVersions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'links': RelationshipLinksToJSON(value['links']),
        'meta': PagingInformationToJSON(value['meta']),
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(CiWorkflowRelationshipsMacOsVersionDataToJSON)),
    };
}

