
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CiXcodeVersionRelationshipsMacOsVersions } from './CiXcodeVersionRelationshipsMacOsVersions';
import {
    CiXcodeVersionRelationshipsMacOsVersionsFromJSON,
    CiXcodeVersionRelationshipsMacOsVersionsFromJSONTyped,
    CiXcodeVersionRelationshipsMacOsVersionsToJSON,
    CiXcodeVersionRelationshipsMacOsVersionsToJSONTyped,
} from './CiXcodeVersionRelationshipsMacOsVersions';

/**
 * 
 * @export
 * @interface CiXcodeVersionRelationships
 */
export interface CiXcodeVersionRelationships {
    /**
     * 
     * @type {CiXcodeVersionRelationshipsMacOsVersions}
     * @memberof CiXcodeVersionRelationships
     */
    macOsVersions?: CiXcodeVersionRelationshipsMacOsVersions;
}

/**
 * Check if a given object implements the CiXcodeVersionRelationships interface.
 */
export function instanceOfCiXcodeVersionRelationships(value: object): value is CiXcodeVersionRelationships {
    return true;
}

export function CiXcodeVersionRelationshipsFromJSON(json: any): CiXcodeVersionRelationships {
    return CiXcodeVersionRelationshipsFromJSONTyped(json, false);
}

export function CiXcodeVersionRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CiXcodeVersionRelationships {
    if (json == null) {
        return json;
    }
    return {
        
        'macOsVersions': json['macOsVersions'] == null ? undefined : CiXcodeVersionRelationshipsMacOsVersionsFromJSON(json['macOsVersions']),
    };
}

export function CiXcodeVersionRelationshipsToJSON(json: any): CiXcodeVersionRelationships {
    return CiXcodeVersionRelationshipsToJSONTyped(json, false);
}

export function CiXcodeVersionRelationshipsToJSONTyped(value?: CiXcodeVersionRelationships | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'macOsVersions': CiXcodeVersionRelationshipsMacOsVersionsToJSON(value['macOsVersions']),
    };
}

