
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData
 */
export interface DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData {
    /**
     * 
     * @type {string}
     * @memberof DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData
     */
    bundleId?: string;
    /**
     * 
     * @type {string}
     * @memberof DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData
     */
    event?: string;
    /**
     * 
     * @type {string}
     * @memberof DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData
     */
    osVersion?: string;
    /**
     * 
     * @type {string}
     * @memberof DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData
     */
    appVersion?: string;
    /**
     * 
     * @type {string}
     * @memberof DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData
     */
    writesCaused?: string;
    /**
     * 
     * @type {string}
     * @memberof DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData
     */
    deviceType?: string;
    /**
     * 
     * @type {string}
     * @memberof DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData
     */
    platformArchitecture?: string;
    /**
     * 
     * @type {string}
     * @memberof DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData
     */
    eventDetail?: string;
    /**
     * 
     * @type {string}
     * @memberof DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData
     */
    buildVersion?: string;
}

/**
 * Check if a given object implements the DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData interface.
 */
export function instanceOfDiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData(value: object): value is DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData {
    return true;
}

export function DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaDataFromJSON(json: any): DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData {
    return DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaDataFromJSONTyped(json, false);
}

export function DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData {
    if (json == null) {
        return json;
    }
    return {
        
        'bundleId': json['bundleId'] == null ? undefined : json['bundleId'],
        'event': json['event'] == null ? undefined : json['event'],
        'osVersion': json['osVersion'] == null ? undefined : json['osVersion'],
        'appVersion': json['appVersion'] == null ? undefined : json['appVersion'],
        'writesCaused': json['writesCaused'] == null ? undefined : json['writesCaused'],
        'deviceType': json['deviceType'] == null ? undefined : json['deviceType'],
        'platformArchitecture': json['platformArchitecture'] == null ? undefined : json['platformArchitecture'],
        'eventDetail': json['eventDetail'] == null ? undefined : json['eventDetail'],
        'buildVersion': json['buildVersion'] == null ? undefined : json['buildVersion'],
    };
}

export function DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaDataToJSON(json: any): DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData {
    return DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaDataToJSONTyped(json, false);
}

export function DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaDataToJSONTyped(value?: DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bundleId': value['bundleId'],
        'event': value['event'],
        'osVersion': value['osVersion'],
        'appVersion': value['appVersion'],
        'writesCaused': value['writesCaused'],
        'deviceType': value['deviceType'],
        'platformArchitecture': value['platformArchitecture'],
        'eventDetail': value['eventDetail'],
        'buildVersion': value['buildVersion'],
    };
}

