
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameCenterAchievementImageRelationshipsGameCenterAchievementLocalization } from './GameCenterAchievementImageRelationshipsGameCenterAchievementLocalization';
import {
    GameCenterAchievementImageRelationshipsGameCenterAchievementLocalizationFromJSON,
    GameCenterAchievementImageRelationshipsGameCenterAchievementLocalizationFromJSONTyped,
    GameCenterAchievementImageRelationshipsGameCenterAchievementLocalizationToJSON,
    GameCenterAchievementImageRelationshipsGameCenterAchievementLocalizationToJSONTyped,
} from './GameCenterAchievementImageRelationshipsGameCenterAchievementLocalization';

/**
 * 
 * @export
 * @interface GameCenterAchievementImageRelationships
 */
export interface GameCenterAchievementImageRelationships {
    /**
     * 
     * @type {GameCenterAchievementImageRelationshipsGameCenterAchievementLocalization}
     * @memberof GameCenterAchievementImageRelationships
     */
    gameCenterAchievementLocalization?: GameCenterAchievementImageRelationshipsGameCenterAchievementLocalization;
}

/**
 * Check if a given object implements the GameCenterAchievementImageRelationships interface.
 */
export function instanceOfGameCenterAchievementImageRelationships(value: object): value is GameCenterAchievementImageRelationships {
    return true;
}

export function GameCenterAchievementImageRelationshipsFromJSON(json: any): GameCenterAchievementImageRelationships {
    return GameCenterAchievementImageRelationshipsFromJSONTyped(json, false);
}

export function GameCenterAchievementImageRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameCenterAchievementImageRelationships {
    if (json == null) {
        return json;
    }
    return {
        
        'gameCenterAchievementLocalization': json['gameCenterAchievementLocalization'] == null ? undefined : GameCenterAchievementImageRelationshipsGameCenterAchievementLocalizationFromJSON(json['gameCenterAchievementLocalization']),
    };
}

export function GameCenterAchievementImageRelationshipsToJSON(json: any): GameCenterAchievementImageRelationships {
    return GameCenterAchievementImageRelationshipsToJSONTyped(json, false);
}

export function GameCenterAchievementImageRelationshipsToJSONTyped(value?: GameCenterAchievementImageRelationships | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'gameCenterAchievementLocalization': GameCenterAchievementImageRelationshipsGameCenterAchievementLocalizationToJSON(value['gameCenterAchievementLocalization']),
    };
}

