/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameCenterLeaderboardLocalizationRelationships } from './GameCenterLeaderboardLocalizationRelationships';
import {
    GameCenterLeaderboardLocalizationRelationshipsFromJSON,
    GameCenterLeaderboardLocalizationRelationshipsFromJSONTyped,
    GameCenterLeaderboardLocalizationRelationshipsToJSON,
    GameCenterLeaderboardLocalizationRelationshipsToJSONTyped,
} from './GameCenterLeaderboardLocalizationRelationships';
import type { GameCenterLeaderboardLocalizationAttributes } from './GameCenterLeaderboardLocalizationAttributes';
import {
    GameCenterLeaderboardLocalizationAttributesFromJSON,
    GameCenterLeaderboardLocalizationAttributesFromJSONTyped,
    GameCenterLeaderboardLocalizationAttributesToJSON,
    GameCenterLeaderboardLocalizationAttributesToJSONTyped,
} from './GameCenterLeaderboardLocalizationAttributes';
import type { ResourceLinks } from './ResourceLinks';
import {
    ResourceLinksFromJSON,
    ResourceLinksFromJSONTyped,
    ResourceLinksToJSON,
    ResourceLinksToJSONTyped,
} from './ResourceLinks';

/**
 * 
 * @export
 * @interface GameCenterLeaderboardLocalization
 */
export interface GameCenterLeaderboardLocalization {
    /**
     * 
     * @type {string}
     * @memberof GameCenterLeaderboardLocalization
     */
    type: GameCenterLeaderboardLocalizationTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof GameCenterLeaderboardLocalization
     */
    id: string;
    /**
     * 
     * @type {GameCenterLeaderboardLocalizationAttributes}
     * @memberof GameCenterLeaderboardLocalization
     */
    attributes?: GameCenterLeaderboardLocalizationAttributes;
    /**
     * 
     * @type {GameCenterLeaderboardLocalizationRelationships}
     * @memberof GameCenterLeaderboardLocalization
     */
    relationships?: GameCenterLeaderboardLocalizationRelationships;
    /**
     * 
     * @type {ResourceLinks}
     * @memberof GameCenterLeaderboardLocalization
     */
    links?: ResourceLinks;
}


/**
 * @export
 */
export const GameCenterLeaderboardLocalizationTypeEnum = {
    GameCenterLeaderboardLocalizations: 'gameCenterLeaderboardLocalizations'
} as const;
export type GameCenterLeaderboardLocalizationTypeEnum = typeof GameCenterLeaderboardLocalizationTypeEnum[keyof typeof GameCenterLeaderboardLocalizationTypeEnum];


/**
 * Check if a given object implements the GameCenterLeaderboardLocalization interface.
 */
export function instanceOfGameCenterLeaderboardLocalization(value: object): value is GameCenterLeaderboardLocalization {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function GameCenterLeaderboardLocalizationFromJSON(json: any): GameCenterLeaderboardLocalization {
    return GameCenterLeaderboardLocalizationFromJSONTyped(json, false);
}

export function GameCenterLeaderboardLocalizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameCenterLeaderboardLocalization {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': json['attributes'] == null ? undefined : GameCenterLeaderboardLocalizationAttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : GameCenterLeaderboardLocalizationRelationshipsFromJSON(json['relationships']),
        'links': json['links'] == null ? undefined : ResourceLinksFromJSON(json['links']),
    };
}

export function GameCenterLeaderboardLocalizationToJSON(json: any): GameCenterLeaderboardLocalization {
    return GameCenterLeaderboardLocalizationToJSONTyped(json, false);
}

export function GameCenterLeaderboardLocalizationToJSONTyped(value?: GameCenterLeaderboardLocalization | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
        'attributes': GameCenterLeaderboardLocalizationAttributesToJSON(value['attributes']),
        'relationships': GameCenterLeaderboardLocalizationRelationshipsToJSON(value['relationships']),
        'links': ResourceLinksToJSON(value['links']),
    };
}

