
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInner
 */
export interface GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInner {
    /**
     * 
     * @type {string}
     * @memberof GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInner
     */
    type: GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInnerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInner
     */
    id: string;
}


/**
 * @export
 */
export const GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInnerTypeEnum = {
    GameCenterLeaderboardSets: 'gameCenterLeaderboardSets'
} as const;
export type GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInnerTypeEnum = typeof GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInnerTypeEnum[keyof typeof GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInnerTypeEnum];


/**
 * Check if a given object implements the GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInner interface.
 */
export function instanceOfGameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInner(value: object): value is GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInner {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInnerFromJSON(json: any): GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInner {
    return GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInnerFromJSONTyped(json, false);
}

export function GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
    };
}

export function GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInnerToJSON(json: any): GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInner {
    return GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInnerToJSONTyped(json, false);
}

export function GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInnerToJSONTyped(value?: GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
    };
}

