/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameCenterDetailRelationshipsGameCenterLeaderboardsDataInner } from './GameCenterDetailRelationshipsGameCenterLeaderboardsDataInner';
import {
    GameCenterDetailRelationshipsGameCenterLeaderboardsDataInnerFromJSON,
    GameCenterDetailRelationshipsGameCenterLeaderboardsDataInnerFromJSONTyped,
    GameCenterDetailRelationshipsGameCenterLeaderboardsDataInnerToJSON,
    GameCenterDetailRelationshipsGameCenterLeaderboardsDataInnerToJSONTyped,
} from './GameCenterDetailRelationshipsGameCenterLeaderboardsDataInner';

/**
 * 
 * @export
 * @interface GameCenterGroupGameCenterLeaderboardsLinkagesRequest
 */
export interface GameCenterGroupGameCenterLeaderboardsLinkagesRequest {
    /**
     * 
     * @type {Array<GameCenterDetailRelationshipsGameCenterLeaderboardsDataInner>}
     * @memberof GameCenterGroupGameCenterLeaderboardsLinkagesRequest
     */
    data: Array<GameCenterDetailRelationshipsGameCenterLeaderboardsDataInner>;
}

/**
 * Check if a given object implements the GameCenterGroupGameCenterLeaderboardsLinkagesRequest interface.
 */
export function instanceOfGameCenterGroupGameCenterLeaderboardsLinkagesRequest(value: object): value is GameCenterGroupGameCenterLeaderboardsLinkagesRequest {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GameCenterGroupGameCenterLeaderboardsLinkagesRequestFromJSON(json: any): GameCenterGroupGameCenterLeaderboardsLinkagesRequest {
    return GameCenterGroupGameCenterLeaderboardsLinkagesRequestFromJSONTyped(json, false);
}

export function GameCenterGroupGameCenterLeaderboardsLinkagesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameCenterGroupGameCenterLeaderboardsLinkagesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(GameCenterDetailRelationshipsGameCenterLeaderboardsDataInnerFromJSON)),
    };
}

export function GameCenterGroupGameCenterLeaderboardsLinkagesRequestToJSON(json: any): GameCenterGroupGameCenterLeaderboardsLinkagesRequest {
    return GameCenterGroupGameCenterLeaderboardsLinkagesRequestToJSONTyped(json, false);
}

export function GameCenterGroupGameCenterLeaderboardsLinkagesRequestToJSONTyped(value?: GameCenterGroupGameCenterLeaderboardsLinkagesRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(GameCenterDetailRelationshipsGameCenterLeaderboardsDataInnerToJSON)),
    };
}

