/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameCenterPlayerAchievementSubmissionCreateRequestDataAttributes } from './GameCenterPlayerAchievementSubmissionCreateRequestDataAttributes';
import {
    GameCenterPlayerAchievementSubmissionCreateRequestDataAttributesFromJSON,
    GameCenterPlayerAchievementSubmissionCreateRequestDataAttributesFromJSONTyped,
    GameCenterPlayerAchievementSubmissionCreateRequestDataAttributesToJSON,
    GameCenterPlayerAchievementSubmissionCreateRequestDataAttributesToJSONTyped,
} from './GameCenterPlayerAchievementSubmissionCreateRequestDataAttributes';

/**
 * 
 * @export
 * @interface GameCenterPlayerAchievementSubmissionCreateRequestData
 */
export interface GameCenterPlayerAchievementSubmissionCreateRequestData {
    /**
     * 
     * @type {string}
     * @memberof GameCenterPlayerAchievementSubmissionCreateRequestData
     */
    type: GameCenterPlayerAchievementSubmissionCreateRequestDataTypeEnum;
    /**
     * 
     * @type {GameCenterPlayerAchievementSubmissionCreateRequestDataAttributes}
     * @memberof GameCenterPlayerAchievementSubmissionCreateRequestData
     */
    attributes: GameCenterPlayerAchievementSubmissionCreateRequestDataAttributes;
}


/**
 * @export
 */
export const GameCenterPlayerAchievementSubmissionCreateRequestDataTypeEnum = {
    GameCenterPlayerAchievementSubmissions: 'gameCenterPlayerAchievementSubmissions'
} as const;
export type GameCenterPlayerAchievementSubmissionCreateRequestDataTypeEnum = typeof GameCenterPlayerAchievementSubmissionCreateRequestDataTypeEnum[keyof typeof GameCenterPlayerAchievementSubmissionCreateRequestDataTypeEnum];


/**
 * Check if a given object implements the GameCenterPlayerAchievementSubmissionCreateRequestData interface.
 */
export function instanceOfGameCenterPlayerAchievementSubmissionCreateRequestData(value: object): value is GameCenterPlayerAchievementSubmissionCreateRequestData {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    return true;
}

export function GameCenterPlayerAchievementSubmissionCreateRequestDataFromJSON(json: any): GameCenterPlayerAchievementSubmissionCreateRequestData {
    return GameCenterPlayerAchievementSubmissionCreateRequestDataFromJSONTyped(json, false);
}

export function GameCenterPlayerAchievementSubmissionCreateRequestDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameCenterPlayerAchievementSubmissionCreateRequestData {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'attributes': GameCenterPlayerAchievementSubmissionCreateRequestDataAttributesFromJSON(json['attributes']),
    };
}

export function GameCenterPlayerAchievementSubmissionCreateRequestDataToJSON(json: any): GameCenterPlayerAchievementSubmissionCreateRequestData {
    return GameCenterPlayerAchievementSubmissionCreateRequestDataToJSONTyped(json, false);
}

export function GameCenterPlayerAchievementSubmissionCreateRequestDataToJSONTyped(value?: GameCenterPlayerAchievementSubmissionCreateRequestData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'attributes': GameCenterPlayerAchievementSubmissionCreateRequestDataAttributesToJSON(value['attributes']),
    };
}

