/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PagingInformation } from './PagingInformation';
import {
    PagingInformationFromJSON,
    PagingInformationFromJSONTyped,
    PagingInformationToJSON,
    PagingInformationToJSONTyped,
} from './PagingInformation';
import type { GameCenterMatchmakingBooleanRuleResultsV1MetricResponseDataInner } from './GameCenterMatchmakingBooleanRuleResultsV1MetricResponseDataInner';
import {
    GameCenterMatchmakingBooleanRuleResultsV1MetricResponseDataInnerFromJSON,
    GameCenterMatchmakingBooleanRuleResultsV1MetricResponseDataInnerFromJSONTyped,
    GameCenterMatchmakingBooleanRuleResultsV1MetricResponseDataInnerToJSON,
    GameCenterMatchmakingBooleanRuleResultsV1MetricResponseDataInnerToJSONTyped,
} from './GameCenterMatchmakingBooleanRuleResultsV1MetricResponseDataInner';
import type { PagedDocumentLinks } from './PagedDocumentLinks';
import {
    PagedDocumentLinksFromJSON,
    PagedDocumentLinksFromJSONTyped,
    PagedDocumentLinksToJSON,
    PagedDocumentLinksToJSONTyped,
} from './PagedDocumentLinks';

/**
 * 
 * @export
 * @interface GameCenterMatchmakingBooleanRuleResultsV1MetricResponse
 */
export interface GameCenterMatchmakingBooleanRuleResultsV1MetricResponse {
    /**
     * 
     * @type {Array<GameCenterMatchmakingBooleanRuleResultsV1MetricResponseDataInner>}
     * @memberof GameCenterMatchmakingBooleanRuleResultsV1MetricResponse
     */
    data: Array<GameCenterMatchmakingBooleanRuleResultsV1MetricResponseDataInner>;
    /**
     * 
     * @type {PagedDocumentLinks}
     * @memberof GameCenterMatchmakingBooleanRuleResultsV1MetricResponse
     */
    links: PagedDocumentLinks;
    /**
     * 
     * @type {PagingInformation}
     * @memberof GameCenterMatchmakingBooleanRuleResultsV1MetricResponse
     */
    meta?: PagingInformation;
}

/**
 * Check if a given object implements the GameCenterMatchmakingBooleanRuleResultsV1MetricResponse interface.
 */
export function instanceOfGameCenterMatchmakingBooleanRuleResultsV1MetricResponse(value: object): value is GameCenterMatchmakingBooleanRuleResultsV1MetricResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('links' in value) || value['links'] === undefined) return false;
    return true;
}

export function GameCenterMatchmakingBooleanRuleResultsV1MetricResponseFromJSON(json: any): GameCenterMatchmakingBooleanRuleResultsV1MetricResponse {
    return GameCenterMatchmakingBooleanRuleResultsV1MetricResponseFromJSONTyped(json, false);
}

export function GameCenterMatchmakingBooleanRuleResultsV1MetricResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameCenterMatchmakingBooleanRuleResultsV1MetricResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(GameCenterMatchmakingBooleanRuleResultsV1MetricResponseDataInnerFromJSON)),
        'links': PagedDocumentLinksFromJSON(json['links']),
        'meta': json['meta'] == null ? undefined : PagingInformationFromJSON(json['meta']),
    };
}

export function GameCenterMatchmakingBooleanRuleResultsV1MetricResponseToJSON(json: any): GameCenterMatchmakingBooleanRuleResultsV1MetricResponse {
    return GameCenterMatchmakingBooleanRuleResultsV1MetricResponseToJSONTyped(json, false);
}

export function GameCenterMatchmakingBooleanRuleResultsV1MetricResponseToJSONTyped(value?: GameCenterMatchmakingBooleanRuleResultsV1MetricResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(GameCenterMatchmakingBooleanRuleResultsV1MetricResponseDataInnerToJSON)),
        'links': PagedDocumentLinksToJSON(value['links']),
        'meta': PagingInformationToJSON(value['meta']),
    };
}

