
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImageData } from './GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImageData';
import {
    GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImageDataFromJSON,
    GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImageDataFromJSONTyped,
    GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImageDataToJSON,
    GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImageDataToJSONTyped,
} from './GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImageData';
import type { RelationshipLinks } from './RelationshipLinks';
import {
    RelationshipLinksFromJSON,
    RelationshipLinksFromJSONTyped,
    RelationshipLinksToJSON,
    RelationshipLinksToJSONTyped,
} from './RelationshipLinks';

/**
 * 
 * @export
 * @interface GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImage
 */
export interface GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImage {
    /**
     * 
     * @type {RelationshipLinks}
     * @memberof GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImage
     */
    links?: RelationshipLinks;
    /**
     * 
     * @type {GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImageData}
     * @memberof GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImage
     */
    data?: GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImageData;
}

/**
 * Check if a given object implements the GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImage interface.
 */
export function instanceOfGameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImage(value: object): value is GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImage {
    return true;
}

export function GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImageFromJSON(json: any): GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImage {
    return GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImageFromJSONTyped(json, false);
}

export function GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImage {
    if (json == null) {
        return json;
    }
    return {
        
        'links': json['links'] == null ? undefined : RelationshipLinksFromJSON(json['links']),
        'data': json['data'] == null ? undefined : GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImageDataFromJSON(json['data']),
    };
}

export function GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImageToJSON(json: any): GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImage {
    return GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImageToJSONTyped(json, false);
}

export function GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImageToJSONTyped(value?: GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'links': RelationshipLinksToJSON(value['links']),
        'data': GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImageDataToJSON(value['data']),
    };
}

