
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributes } from './GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributes';
import {
    GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributesFromJSON,
    GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributesFromJSONTyped,
    GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributesToJSON,
    GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributesToJSONTyped,
} from './GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributes';

/**
 * 
 * @export
 * @interface GameCenterMatchmakingTestPlayerPropertyInlineCreate
 */
export interface GameCenterMatchmakingTestPlayerPropertyInlineCreate {
    /**
     * 
     * @type {string}
     * @memberof GameCenterMatchmakingTestPlayerPropertyInlineCreate
     */
    type: GameCenterMatchmakingTestPlayerPropertyInlineCreateTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof GameCenterMatchmakingTestPlayerPropertyInlineCreate
     */
    id?: string;
    /**
     * 
     * @type {GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributes}
     * @memberof GameCenterMatchmakingTestPlayerPropertyInlineCreate
     */
    attributes: GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributes;
}


/**
 * @export
 */
export const GameCenterMatchmakingTestPlayerPropertyInlineCreateTypeEnum = {
    GameCenterMatchmakingTestPlayerProperties: 'gameCenterMatchmakingTestPlayerProperties'
} as const;
export type GameCenterMatchmakingTestPlayerPropertyInlineCreateTypeEnum = typeof GameCenterMatchmakingTestPlayerPropertyInlineCreateTypeEnum[keyof typeof GameCenterMatchmakingTestPlayerPropertyInlineCreateTypeEnum];


/**
 * Check if a given object implements the GameCenterMatchmakingTestPlayerPropertyInlineCreate interface.
 */
export function instanceOfGameCenterMatchmakingTestPlayerPropertyInlineCreate(value: object): value is GameCenterMatchmakingTestPlayerPropertyInlineCreate {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    return true;
}

export function GameCenterMatchmakingTestPlayerPropertyInlineCreateFromJSON(json: any): GameCenterMatchmakingTestPlayerPropertyInlineCreate {
    return GameCenterMatchmakingTestPlayerPropertyInlineCreateFromJSONTyped(json, false);
}

export function GameCenterMatchmakingTestPlayerPropertyInlineCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameCenterMatchmakingTestPlayerPropertyInlineCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'] == null ? undefined : json['id'],
        'attributes': GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributesFromJSON(json['attributes']),
    };
}

export function GameCenterMatchmakingTestPlayerPropertyInlineCreateToJSON(json: any): GameCenterMatchmakingTestPlayerPropertyInlineCreate {
    return GameCenterMatchmakingTestPlayerPropertyInlineCreateToJSONTyped(json, false);
}

export function GameCenterMatchmakingTestPlayerPropertyInlineCreateToJSONTyped(value?: GameCenterMatchmakingTestPlayerPropertyInlineCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
        'attributes': GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributesToJSON(value['attributes']),
    };
}

