
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Property } from './Property';
import {
    PropertyFromJSON,
    PropertyFromJSONTyped,
    PropertyToJSON,
    PropertyToJSONTyped,
} from './Property';

/**
 * 
 * @export
 * @interface GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributes
 */
export interface GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributes {
    /**
     * 
     * @type {string}
     * @memberof GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributes
     */
    playerId: string;
    /**
     * 
     * @type {Array<Property>}
     * @memberof GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributes
     */
    properties?: Array<Property>;
}

/**
 * Check if a given object implements the GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributes interface.
 */
export function instanceOfGameCenterMatchmakingTestPlayerPropertyInlineCreateAttributes(value: object): value is GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributes {
    if (!('playerId' in value) || value['playerId'] === undefined) return false;
    return true;
}

export function GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributesFromJSON(json: any): GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributes {
    return GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributesFromJSONTyped(json, false);
}

export function GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributes {
    if (json == null) {
        return json;
    }
    return {
        
        'playerId': json['playerId'],
        'properties': json['properties'] == null ? undefined : ((json['properties'] as Array<any>).map(PropertyFromJSON)),
    };
}

export function GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributesToJSON(json: any): GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributes {
    return GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributesToJSONTyped(json, false);
}

export function GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributesToJSONTyped(value?: GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'playerId': value['playerId'],
        'properties': value['properties'] == null ? undefined : ((value['properties'] as Array<any>).map(PropertyToJSON)),
    };
}

