/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GameCenterLeaderboardSetCreateRequestDataAttributes
 */
export interface GameCenterLeaderboardSetCreateRequestDataAttributes {
    /**
     * 
     * @type {string}
     * @memberof GameCenterLeaderboardSetCreateRequestDataAttributes
     */
    referenceName: string;
    /**
     * 
     * @type {string}
     * @memberof GameCenterLeaderboardSetCreateRequestDataAttributes
     */
    vendorIdentifier: string;
}

/**
 * Check if a given object implements the GameCenterLeaderboardSetCreateRequestDataAttributes interface.
 */
export function instanceOfGameCenterLeaderboardSetCreateRequestDataAttributes(value: object): value is GameCenterLeaderboardSetCreateRequestDataAttributes {
    if (!('referenceName' in value) || value['referenceName'] === undefined) return false;
    if (!('vendorIdentifier' in value) || value['vendorIdentifier'] === undefined) return false;
    return true;
}

export function GameCenterLeaderboardSetCreateRequestDataAttributesFromJSON(json: any): GameCenterLeaderboardSetCreateRequestDataAttributes {
    return GameCenterLeaderboardSetCreateRequestDataAttributesFromJSONTyped(json, false);
}

export function GameCenterLeaderboardSetCreateRequestDataAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameCenterLeaderboardSetCreateRequestDataAttributes {
    if (json == null) {
        return json;
    }
    return {
        
        'referenceName': json['referenceName'],
        'vendorIdentifier': json['vendorIdentifier'],
    };
}

export function GameCenterLeaderboardSetCreateRequestDataAttributesToJSON(json: any): GameCenterLeaderboardSetCreateRequestDataAttributes {
    return GameCenterLeaderboardSetCreateRequestDataAttributesToJSONTyped(json, false);
}

export function GameCenterLeaderboardSetCreateRequestDataAttributesToJSONTyped(value?: GameCenterLeaderboardSetCreateRequestDataAttributes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'referenceName': value['referenceName'],
        'vendorIdentifier': value['vendorIdentifier'],
    };
}

