/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameCenterAchievementCreateRequestData } from './GameCenterAchievementCreateRequestData';
import {
    GameCenterAchievementCreateRequestDataFromJSON,
    GameCenterAchievementCreateRequestDataFromJSONTyped,
    GameCenterAchievementCreateRequestDataToJSON,
    GameCenterAchievementCreateRequestDataToJSONTyped,
} from './GameCenterAchievementCreateRequestData';

/**
 * 
 * @export
 * @interface GameCenterAchievementCreateRequest
 */
export interface GameCenterAchievementCreateRequest {
    /**
     * 
     * @type {GameCenterAchievementCreateRequestData}
     * @memberof GameCenterAchievementCreateRequest
     */
    data: GameCenterAchievementCreateRequestData;
}

/**
 * Check if a given object implements the GameCenterAchievementCreateRequest interface.
 */
export function instanceOfGameCenterAchievementCreateRequest(value: object): value is GameCenterAchievementCreateRequest {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GameCenterAchievementCreateRequestFromJSON(json: any): GameCenterAchievementCreateRequest {
    return GameCenterAchievementCreateRequestFromJSONTyped(json, false);
}

export function GameCenterAchievementCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameCenterAchievementCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'data': GameCenterAchievementCreateRequestDataFromJSON(json['data']),
    };
}

export function GameCenterAchievementCreateRequestToJSON(json: any): GameCenterAchievementCreateRequest {
    return GameCenterAchievementCreateRequestToJSONTyped(json, false);
}

export function GameCenterAchievementCreateRequestToJSONTyped(value?: GameCenterAchievementCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': GameCenterAchievementCreateRequestDataToJSON(value['data']),
    };
}

