/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInner } from './GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInner';
import {
    GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInnerFromJSON,
    GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInnerFromJSONTyped,
    GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInnerToJSON,
    GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInnerToJSONTyped,
} from './GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInner';

/**
 * 
 * @export
 * @interface GameCenterLeaderboardSetGroupLeaderboardSetLinkageRequest
 */
export interface GameCenterLeaderboardSetGroupLeaderboardSetLinkageRequest {
    /**
     * 
     * @type {GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInner}
     * @memberof GameCenterLeaderboardSetGroupLeaderboardSetLinkageRequest
     */
    data: GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInner;
}

/**
 * Check if a given object implements the GameCenterLeaderboardSetGroupLeaderboardSetLinkageRequest interface.
 */
export function instanceOfGameCenterLeaderboardSetGroupLeaderboardSetLinkageRequest(value: object): value is GameCenterLeaderboardSetGroupLeaderboardSetLinkageRequest {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GameCenterLeaderboardSetGroupLeaderboardSetLinkageRequestFromJSON(json: any): GameCenterLeaderboardSetGroupLeaderboardSetLinkageRequest {
    return GameCenterLeaderboardSetGroupLeaderboardSetLinkageRequestFromJSONTyped(json, false);
}

export function GameCenterLeaderboardSetGroupLeaderboardSetLinkageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameCenterLeaderboardSetGroupLeaderboardSetLinkageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'data': GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInnerFromJSON(json['data']),
    };
}

export function GameCenterLeaderboardSetGroupLeaderboardSetLinkageRequestToJSON(json: any): GameCenterLeaderboardSetGroupLeaderboardSetLinkageRequest {
    return GameCenterLeaderboardSetGroupLeaderboardSetLinkageRequestToJSONTyped(json, false);
}

export function GameCenterLeaderboardSetGroupLeaderboardSetLinkageRequestToJSONTyped(value?: GameCenterLeaderboardSetGroupLeaderboardSetLinkageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInnerToJSON(value['data']),
    };
}

