/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PagingInformation } from './PagingInformation';
import {
    PagingInformationFromJSON,
    PagingInformationFromJSONTyped,
    PagingInformationToJSON,
    PagingInformationToJSONTyped,
} from './PagingInformation';
import type { GameCenterMatchmakingNumberRuleResultsV1MetricResponseDataInner } from './GameCenterMatchmakingNumberRuleResultsV1MetricResponseDataInner';
import {
    GameCenterMatchmakingNumberRuleResultsV1MetricResponseDataInnerFromJSON,
    GameCenterMatchmakingNumberRuleResultsV1MetricResponseDataInnerFromJSONTyped,
    GameCenterMatchmakingNumberRuleResultsV1MetricResponseDataInnerToJSON,
    GameCenterMatchmakingNumberRuleResultsV1MetricResponseDataInnerToJSONTyped,
} from './GameCenterMatchmakingNumberRuleResultsV1MetricResponseDataInner';
import type { PagedDocumentLinks } from './PagedDocumentLinks';
import {
    PagedDocumentLinksFromJSON,
    PagedDocumentLinksFromJSONTyped,
    PagedDocumentLinksToJSON,
    PagedDocumentLinksToJSONTyped,
} from './PagedDocumentLinks';

/**
 * 
 * @export
 * @interface GameCenterMatchmakingNumberRuleResultsV1MetricResponse
 */
export interface GameCenterMatchmakingNumberRuleResultsV1MetricResponse {
    /**
     * 
     * @type {Array<GameCenterMatchmakingNumberRuleResultsV1MetricResponseDataInner>}
     * @memberof GameCenterMatchmakingNumberRuleResultsV1MetricResponse
     */
    data: Array<GameCenterMatchmakingNumberRuleResultsV1MetricResponseDataInner>;
    /**
     * 
     * @type {PagedDocumentLinks}
     * @memberof GameCenterMatchmakingNumberRuleResultsV1MetricResponse
     */
    links: PagedDocumentLinks;
    /**
     * 
     * @type {PagingInformation}
     * @memberof GameCenterMatchmakingNumberRuleResultsV1MetricResponse
     */
    meta?: PagingInformation;
}

/**
 * Check if a given object implements the GameCenterMatchmakingNumberRuleResultsV1MetricResponse interface.
 */
export function instanceOfGameCenterMatchmakingNumberRuleResultsV1MetricResponse(value: object): value is GameCenterMatchmakingNumberRuleResultsV1MetricResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('links' in value) || value['links'] === undefined) return false;
    return true;
}

export function GameCenterMatchmakingNumberRuleResultsV1MetricResponseFromJSON(json: any): GameCenterMatchmakingNumberRuleResultsV1MetricResponse {
    return GameCenterMatchmakingNumberRuleResultsV1MetricResponseFromJSONTyped(json, false);
}

export function GameCenterMatchmakingNumberRuleResultsV1MetricResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameCenterMatchmakingNumberRuleResultsV1MetricResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(GameCenterMatchmakingNumberRuleResultsV1MetricResponseDataInnerFromJSON)),
        'links': PagedDocumentLinksFromJSON(json['links']),
        'meta': json['meta'] == null ? undefined : PagingInformationFromJSON(json['meta']),
    };
}

export function GameCenterMatchmakingNumberRuleResultsV1MetricResponseToJSON(json: any): GameCenterMatchmakingNumberRuleResultsV1MetricResponse {
    return GameCenterMatchmakingNumberRuleResultsV1MetricResponseToJSONTyped(json, false);
}

export function GameCenterMatchmakingNumberRuleResultsV1MetricResponseToJSONTyped(value?: GameCenterMatchmakingNumberRuleResultsV1MetricResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(GameCenterMatchmakingNumberRuleResultsV1MetricResponseDataInnerToJSON)),
        'links': PagedDocumentLinksToJSON(value['links']),
        'meta': PagingInformationToJSON(value['meta']),
    };
}

