/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameCenterDetailCreateRequestDataAttributes } from './GameCenterDetailCreateRequestDataAttributes';
import {
    GameCenterDetailCreateRequestDataAttributesFromJSON,
    GameCenterDetailCreateRequestDataAttributesFromJSONTyped,
    GameCenterDetailCreateRequestDataAttributesToJSON,
    GameCenterDetailCreateRequestDataAttributesToJSONTyped,
} from './GameCenterDetailCreateRequestDataAttributes';
import type { AnalyticsReportRequestCreateRequestDataRelationships } from './AnalyticsReportRequestCreateRequestDataRelationships';
import {
    AnalyticsReportRequestCreateRequestDataRelationshipsFromJSON,
    AnalyticsReportRequestCreateRequestDataRelationshipsFromJSONTyped,
    AnalyticsReportRequestCreateRequestDataRelationshipsToJSON,
    AnalyticsReportRequestCreateRequestDataRelationshipsToJSONTyped,
} from './AnalyticsReportRequestCreateRequestDataRelationships';

/**
 * 
 * @export
 * @interface GameCenterDetailCreateRequestData
 */
export interface GameCenterDetailCreateRequestData {
    /**
     * 
     * @type {string}
     * @memberof GameCenterDetailCreateRequestData
     */
    type: GameCenterDetailCreateRequestDataTypeEnum;
    /**
     * 
     * @type {GameCenterDetailCreateRequestDataAttributes}
     * @memberof GameCenterDetailCreateRequestData
     */
    attributes?: GameCenterDetailCreateRequestDataAttributes;
    /**
     * 
     * @type {AnalyticsReportRequestCreateRequestDataRelationships}
     * @memberof GameCenterDetailCreateRequestData
     */
    relationships: AnalyticsReportRequestCreateRequestDataRelationships;
}


/**
 * @export
 */
export const GameCenterDetailCreateRequestDataTypeEnum = {
    GameCenterDetails: 'gameCenterDetails'
} as const;
export type GameCenterDetailCreateRequestDataTypeEnum = typeof GameCenterDetailCreateRequestDataTypeEnum[keyof typeof GameCenterDetailCreateRequestDataTypeEnum];


/**
 * Check if a given object implements the GameCenterDetailCreateRequestData interface.
 */
export function instanceOfGameCenterDetailCreateRequestData(value: object): value is GameCenterDetailCreateRequestData {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('relationships' in value) || value['relationships'] === undefined) return false;
    return true;
}

export function GameCenterDetailCreateRequestDataFromJSON(json: any): GameCenterDetailCreateRequestData {
    return GameCenterDetailCreateRequestDataFromJSONTyped(json, false);
}

export function GameCenterDetailCreateRequestDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameCenterDetailCreateRequestData {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'attributes': json['attributes'] == null ? undefined : GameCenterDetailCreateRequestDataAttributesFromJSON(json['attributes']),
        'relationships': AnalyticsReportRequestCreateRequestDataRelationshipsFromJSON(json['relationships']),
    };
}

export function GameCenterDetailCreateRequestDataToJSON(json: any): GameCenterDetailCreateRequestData {
    return GameCenterDetailCreateRequestDataToJSONTyped(json, false);
}

export function GameCenterDetailCreateRequestDataToJSONTyped(value?: GameCenterDetailCreateRequestData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'attributes': GameCenterDetailCreateRequestDataAttributesToJSON(value['attributes']),
        'relationships': AnalyticsReportRequestCreateRequestDataRelationshipsToJSON(value['relationships']),
    };
}

