/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameCenterLeaderboardEntrySubmission } from './GameCenterLeaderboardEntrySubmission';
import {
    GameCenterLeaderboardEntrySubmissionFromJSON,
    GameCenterLeaderboardEntrySubmissionFromJSONTyped,
    GameCenterLeaderboardEntrySubmissionToJSON,
    GameCenterLeaderboardEntrySubmissionToJSONTyped,
} from './GameCenterLeaderboardEntrySubmission';
import type { DocumentLinks } from './DocumentLinks';
import {
    DocumentLinksFromJSON,
    DocumentLinksFromJSONTyped,
    DocumentLinksToJSON,
    DocumentLinksToJSONTyped,
} from './DocumentLinks';

/**
 * 
 * @export
 * @interface GameCenterLeaderboardEntrySubmissionResponse
 */
export interface GameCenterLeaderboardEntrySubmissionResponse {
    /**
     * 
     * @type {GameCenterLeaderboardEntrySubmission}
     * @memberof GameCenterLeaderboardEntrySubmissionResponse
     */
    data: GameCenterLeaderboardEntrySubmission;
    /**
     * 
     * @type {DocumentLinks}
     * @memberof GameCenterLeaderboardEntrySubmissionResponse
     */
    links: DocumentLinks;
}

/**
 * Check if a given object implements the GameCenterLeaderboardEntrySubmissionResponse interface.
 */
export function instanceOfGameCenterLeaderboardEntrySubmissionResponse(value: object): value is GameCenterLeaderboardEntrySubmissionResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('links' in value) || value['links'] === undefined) return false;
    return true;
}

export function GameCenterLeaderboardEntrySubmissionResponseFromJSON(json: any): GameCenterLeaderboardEntrySubmissionResponse {
    return GameCenterLeaderboardEntrySubmissionResponseFromJSONTyped(json, false);
}

export function GameCenterLeaderboardEntrySubmissionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameCenterLeaderboardEntrySubmissionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': GameCenterLeaderboardEntrySubmissionFromJSON(json['data']),
        'links': DocumentLinksFromJSON(json['links']),
    };
}

export function GameCenterLeaderboardEntrySubmissionResponseToJSON(json: any): GameCenterLeaderboardEntrySubmissionResponse {
    return GameCenterLeaderboardEntrySubmissionResponseToJSONTyped(json, false);
}

export function GameCenterLeaderboardEntrySubmissionResponseToJSONTyped(value?: GameCenterLeaderboardEntrySubmissionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': GameCenterLeaderboardEntrySubmissionToJSON(value['data']),
        'links': DocumentLinksToJSON(value['links']),
    };
}

