
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameCenterMatchmakingQueueRequestsV1MetricResponseDataInner } from './GameCenterMatchmakingQueueRequestsV1MetricResponseDataInner';
import {
    GameCenterMatchmakingQueueRequestsV1MetricResponseDataInnerFromJSON,
    GameCenterMatchmakingQueueRequestsV1MetricResponseDataInnerFromJSONTyped,
    GameCenterMatchmakingQueueRequestsV1MetricResponseDataInnerToJSON,
    GameCenterMatchmakingQueueRequestsV1MetricResponseDataInnerToJSONTyped,
} from './GameCenterMatchmakingQueueRequestsV1MetricResponseDataInner';
import type { PagingInformation } from './PagingInformation';
import {
    PagingInformationFromJSON,
    PagingInformationFromJSONTyped,
    PagingInformationToJSON,
    PagingInformationToJSONTyped,
} from './PagingInformation';
import type { PagedDocumentLinks } from './PagedDocumentLinks';
import {
    PagedDocumentLinksFromJSON,
    PagedDocumentLinksFromJSONTyped,
    PagedDocumentLinksToJSON,
    PagedDocumentLinksToJSONTyped,
} from './PagedDocumentLinks';

/**
 * 
 * @export
 * @interface GameCenterMatchmakingQueueRequestsV1MetricResponse
 */
export interface GameCenterMatchmakingQueueRequestsV1MetricResponse {
    /**
     * 
     * @type {Array<GameCenterMatchmakingQueueRequestsV1MetricResponseDataInner>}
     * @memberof GameCenterMatchmakingQueueRequestsV1MetricResponse
     */
    data: Array<GameCenterMatchmakingQueueRequestsV1MetricResponseDataInner>;
    /**
     * 
     * @type {PagedDocumentLinks}
     * @memberof GameCenterMatchmakingQueueRequestsV1MetricResponse
     */
    links: PagedDocumentLinks;
    /**
     * 
     * @type {PagingInformation}
     * @memberof GameCenterMatchmakingQueueRequestsV1MetricResponse
     */
    meta?: PagingInformation;
}

/**
 * Check if a given object implements the GameCenterMatchmakingQueueRequestsV1MetricResponse interface.
 */
export function instanceOfGameCenterMatchmakingQueueRequestsV1MetricResponse(value: object): value is GameCenterMatchmakingQueueRequestsV1MetricResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('links' in value) || value['links'] === undefined) return false;
    return true;
}

export function GameCenterMatchmakingQueueRequestsV1MetricResponseFromJSON(json: any): GameCenterMatchmakingQueueRequestsV1MetricResponse {
    return GameCenterMatchmakingQueueRequestsV1MetricResponseFromJSONTyped(json, false);
}

export function GameCenterMatchmakingQueueRequestsV1MetricResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameCenterMatchmakingQueueRequestsV1MetricResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(GameCenterMatchmakingQueueRequestsV1MetricResponseDataInnerFromJSON)),
        'links': PagedDocumentLinksFromJSON(json['links']),
        'meta': json['meta'] == null ? undefined : PagingInformationFromJSON(json['meta']),
    };
}

export function GameCenterMatchmakingQueueRequestsV1MetricResponseToJSON(json: any): GameCenterMatchmakingQueueRequestsV1MetricResponse {
    return GameCenterMatchmakingQueueRequestsV1MetricResponseToJSONTyped(json, false);
}

export function GameCenterMatchmakingQueueRequestsV1MetricResponseToJSONTyped(value?: GameCenterMatchmakingQueueRequestsV1MetricResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(GameCenterMatchmakingQueueRequestsV1MetricResponseDataInnerToJSON)),
        'links': PagedDocumentLinksToJSON(value['links']),
        'meta': PagingInformationToJSON(value['meta']),
    };
}

