
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameCenterMatchmakingRuleSetCreateRequestDataAttributes } from './GameCenterMatchmakingRuleSetCreateRequestDataAttributes';
import {
    GameCenterMatchmakingRuleSetCreateRequestDataAttributesFromJSON,
    GameCenterMatchmakingRuleSetCreateRequestDataAttributesFromJSONTyped,
    GameCenterMatchmakingRuleSetCreateRequestDataAttributesToJSON,
    GameCenterMatchmakingRuleSetCreateRequestDataAttributesToJSONTyped,
} from './GameCenterMatchmakingRuleSetCreateRequestDataAttributes';

/**
 * 
 * @export
 * @interface GameCenterMatchmakingRuleSetCreateRequestData
 */
export interface GameCenterMatchmakingRuleSetCreateRequestData {
    /**
     * 
     * @type {string}
     * @memberof GameCenterMatchmakingRuleSetCreateRequestData
     */
    type: GameCenterMatchmakingRuleSetCreateRequestDataTypeEnum;
    /**
     * 
     * @type {GameCenterMatchmakingRuleSetCreateRequestDataAttributes}
     * @memberof GameCenterMatchmakingRuleSetCreateRequestData
     */
    attributes: GameCenterMatchmakingRuleSetCreateRequestDataAttributes;
}


/**
 * @export
 */
export const GameCenterMatchmakingRuleSetCreateRequestDataTypeEnum = {
    GameCenterMatchmakingRuleSets: 'gameCenterMatchmakingRuleSets'
} as const;
export type GameCenterMatchmakingRuleSetCreateRequestDataTypeEnum = typeof GameCenterMatchmakingRuleSetCreateRequestDataTypeEnum[keyof typeof GameCenterMatchmakingRuleSetCreateRequestDataTypeEnum];


/**
 * Check if a given object implements the GameCenterMatchmakingRuleSetCreateRequestData interface.
 */
export function instanceOfGameCenterMatchmakingRuleSetCreateRequestData(value: object): value is GameCenterMatchmakingRuleSetCreateRequestData {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    return true;
}

export function GameCenterMatchmakingRuleSetCreateRequestDataFromJSON(json: any): GameCenterMatchmakingRuleSetCreateRequestData {
    return GameCenterMatchmakingRuleSetCreateRequestDataFromJSONTyped(json, false);
}

export function GameCenterMatchmakingRuleSetCreateRequestDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameCenterMatchmakingRuleSetCreateRequestData {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'attributes': GameCenterMatchmakingRuleSetCreateRequestDataAttributesFromJSON(json['attributes']),
    };
}

export function GameCenterMatchmakingRuleSetCreateRequestDataToJSON(json: any): GameCenterMatchmakingRuleSetCreateRequestData {
    return GameCenterMatchmakingRuleSetCreateRequestDataToJSONTyped(json, false);
}

export function GameCenterMatchmakingRuleSetCreateRequestDataToJSONTyped(value?: GameCenterMatchmakingRuleSetCreateRequestData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'attributes': GameCenterMatchmakingRuleSetCreateRequestDataAttributesToJSON(value['attributes']),
    };
}

