
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppRelationshipsPromotedPurchasesDataInner } from './AppRelationshipsPromotedPurchasesDataInner';
import {
    AppRelationshipsPromotedPurchasesDataInnerFromJSON,
    AppRelationshipsPromotedPurchasesDataInnerFromJSONTyped,
    AppRelationshipsPromotedPurchasesDataInnerToJSON,
    AppRelationshipsPromotedPurchasesDataInnerToJSONTyped,
} from './AppRelationshipsPromotedPurchasesDataInner';
import type { RelationshipLinks } from './RelationshipLinks';
import {
    RelationshipLinksFromJSON,
    RelationshipLinksFromJSONTyped,
    RelationshipLinksToJSON,
    RelationshipLinksToJSONTyped,
} from './RelationshipLinks';

/**
 * 
 * @export
 * @interface InAppPurchaseV2RelationshipsPromotedPurchase
 */
export interface InAppPurchaseV2RelationshipsPromotedPurchase {
    /**
     * 
     * @type {RelationshipLinks}
     * @memberof InAppPurchaseV2RelationshipsPromotedPurchase
     */
    links?: RelationshipLinks;
    /**
     * 
     * @type {AppRelationshipsPromotedPurchasesDataInner}
     * @memberof InAppPurchaseV2RelationshipsPromotedPurchase
     */
    data?: AppRelationshipsPromotedPurchasesDataInner;
}

/**
 * Check if a given object implements the InAppPurchaseV2RelationshipsPromotedPurchase interface.
 */
export function instanceOfInAppPurchaseV2RelationshipsPromotedPurchase(value: object): value is InAppPurchaseV2RelationshipsPromotedPurchase {
    return true;
}

export function InAppPurchaseV2RelationshipsPromotedPurchaseFromJSON(json: any): InAppPurchaseV2RelationshipsPromotedPurchase {
    return InAppPurchaseV2RelationshipsPromotedPurchaseFromJSONTyped(json, false);
}

export function InAppPurchaseV2RelationshipsPromotedPurchaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InAppPurchaseV2RelationshipsPromotedPurchase {
    if (json == null) {
        return json;
    }
    return {
        
        'links': json['links'] == null ? undefined : RelationshipLinksFromJSON(json['links']),
        'data': json['data'] == null ? undefined : AppRelationshipsPromotedPurchasesDataInnerFromJSON(json['data']),
    };
}

export function InAppPurchaseV2RelationshipsPromotedPurchaseToJSON(json: any): InAppPurchaseV2RelationshipsPromotedPurchase {
    return InAppPurchaseV2RelationshipsPromotedPurchaseToJSONTyped(json, false);
}

export function InAppPurchaseV2RelationshipsPromotedPurchaseToJSONTyped(value?: InAppPurchaseV2RelationshipsPromotedPurchase | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'links': RelationshipLinksToJSON(value['links']),
        'data': AppRelationshipsPromotedPurchasesDataInnerToJSON(value['data']),
    };
}

