
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InAppPurchaseV2Attributes } from './InAppPurchaseV2Attributes';
import {
    InAppPurchaseV2AttributesFromJSON,
    InAppPurchaseV2AttributesFromJSONTyped,
    InAppPurchaseV2AttributesToJSON,
    InAppPurchaseV2AttributesToJSONTyped,
} from './InAppPurchaseV2Attributes';
import type { InAppPurchaseV2Relationships } from './InAppPurchaseV2Relationships';
import {
    InAppPurchaseV2RelationshipsFromJSON,
    InAppPurchaseV2RelationshipsFromJSONTyped,
    InAppPurchaseV2RelationshipsToJSON,
    InAppPurchaseV2RelationshipsToJSONTyped,
} from './InAppPurchaseV2Relationships';
import type { ResourceLinks } from './ResourceLinks';
import {
    ResourceLinksFromJSON,
    ResourceLinksFromJSONTyped,
    ResourceLinksToJSON,
    ResourceLinksToJSONTyped,
} from './ResourceLinks';

/**
 * 
 * @export
 * @interface InAppPurchaseV2
 */
export interface InAppPurchaseV2 {
    /**
     * 
     * @type {string}
     * @memberof InAppPurchaseV2
     */
    type: InAppPurchaseV2TypeEnum;
    /**
     * 
     * @type {string}
     * @memberof InAppPurchaseV2
     */
    id: string;
    /**
     * 
     * @type {InAppPurchaseV2Attributes}
     * @memberof InAppPurchaseV2
     */
    attributes?: InAppPurchaseV2Attributes;
    /**
     * 
     * @type {InAppPurchaseV2Relationships}
     * @memberof InAppPurchaseV2
     */
    relationships?: InAppPurchaseV2Relationships;
    /**
     * 
     * @type {ResourceLinks}
     * @memberof InAppPurchaseV2
     */
    links?: ResourceLinks;
}


/**
 * @export
 */
export const InAppPurchaseV2TypeEnum = {
    InAppPurchases: 'inAppPurchases'
} as const;
export type InAppPurchaseV2TypeEnum = typeof InAppPurchaseV2TypeEnum[keyof typeof InAppPurchaseV2TypeEnum];


/**
 * Check if a given object implements the InAppPurchaseV2 interface.
 */
export function instanceOfInAppPurchaseV2(value: object): value is InAppPurchaseV2 {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function InAppPurchaseV2FromJSON(json: any): InAppPurchaseV2 {
    return InAppPurchaseV2FromJSONTyped(json, false);
}

export function InAppPurchaseV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): InAppPurchaseV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': json['attributes'] == null ? undefined : InAppPurchaseV2AttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : InAppPurchaseV2RelationshipsFromJSON(json['relationships']),
        'links': json['links'] == null ? undefined : ResourceLinksFromJSON(json['links']),
    };
}

export function InAppPurchaseV2ToJSON(json: any): InAppPurchaseV2 {
    return InAppPurchaseV2ToJSONTyped(json, false);
}

export function InAppPurchaseV2ToJSONTyped(value?: InAppPurchaseV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
        'attributes': InAppPurchaseV2AttributesToJSON(value['attributes']),
        'relationships': InAppPurchaseV2RelationshipsToJSON(value['relationships']),
        'links': ResourceLinksToJSON(value['links']),
    };
}

