
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InAppPurchasePriceScheduleRelationshipsManualPricesDataInner } from './InAppPurchasePriceScheduleRelationshipsManualPricesDataInner';
import {
    InAppPurchasePriceScheduleRelationshipsManualPricesDataInnerFromJSON,
    InAppPurchasePriceScheduleRelationshipsManualPricesDataInnerFromJSONTyped,
    InAppPurchasePriceScheduleRelationshipsManualPricesDataInnerToJSON,
    InAppPurchasePriceScheduleRelationshipsManualPricesDataInnerToJSONTyped,
} from './InAppPurchasePriceScheduleRelationshipsManualPricesDataInner';

/**
 * 
 * @export
 * @interface InAppPurchasePriceScheduleCreateRequestDataRelationshipsManualPrices
 */
export interface InAppPurchasePriceScheduleCreateRequestDataRelationshipsManualPrices {
    /**
     * 
     * @type {Array<InAppPurchasePriceScheduleRelationshipsManualPricesDataInner>}
     * @memberof InAppPurchasePriceScheduleCreateRequestDataRelationshipsManualPrices
     */
    data: Array<InAppPurchasePriceScheduleRelationshipsManualPricesDataInner>;
}

/**
 * Check if a given object implements the InAppPurchasePriceScheduleCreateRequestDataRelationshipsManualPrices interface.
 */
export function instanceOfInAppPurchasePriceScheduleCreateRequestDataRelationshipsManualPrices(value: object): value is InAppPurchasePriceScheduleCreateRequestDataRelationshipsManualPrices {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function InAppPurchasePriceScheduleCreateRequestDataRelationshipsManualPricesFromJSON(json: any): InAppPurchasePriceScheduleCreateRequestDataRelationshipsManualPrices {
    return InAppPurchasePriceScheduleCreateRequestDataRelationshipsManualPricesFromJSONTyped(json, false);
}

export function InAppPurchasePriceScheduleCreateRequestDataRelationshipsManualPricesFromJSONTyped(json: any, ignoreDiscriminator: boolean): InAppPurchasePriceScheduleCreateRequestDataRelationshipsManualPrices {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(InAppPurchasePriceScheduleRelationshipsManualPricesDataInnerFromJSON)),
    };
}

export function InAppPurchasePriceScheduleCreateRequestDataRelationshipsManualPricesToJSON(json: any): InAppPurchasePriceScheduleCreateRequestDataRelationshipsManualPrices {
    return InAppPurchasePriceScheduleCreateRequestDataRelationshipsManualPricesToJSONTyped(json, false);
}

export function InAppPurchasePriceScheduleCreateRequestDataRelationshipsManualPricesToJSONTyped(value?: InAppPurchasePriceScheduleCreateRequestDataRelationshipsManualPrices | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(InAppPurchasePriceScheduleRelationshipsManualPricesDataInnerToJSON)),
    };
}

