/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InAppPurchaseAppStoreReviewScreenshotCreateRequestDataRelationshipsInAppPurchaseV2 } from './InAppPurchaseAppStoreReviewScreenshotCreateRequestDataRelationshipsInAppPurchaseV2';
import {
    InAppPurchaseAppStoreReviewScreenshotCreateRequestDataRelationshipsInAppPurchaseV2FromJSON,
    InAppPurchaseAppStoreReviewScreenshotCreateRequestDataRelationshipsInAppPurchaseV2FromJSONTyped,
    InAppPurchaseAppStoreReviewScreenshotCreateRequestDataRelationshipsInAppPurchaseV2ToJSON,
    InAppPurchaseAppStoreReviewScreenshotCreateRequestDataRelationshipsInAppPurchaseV2ToJSONTyped,
} from './InAppPurchaseAppStoreReviewScreenshotCreateRequestDataRelationshipsInAppPurchaseV2';

/**
 * 
 * @export
 * @interface InAppPurchaseImageCreateRequestDataRelationships
 */
export interface InAppPurchaseImageCreateRequestDataRelationships {
    /**
     * 
     * @type {InAppPurchaseAppStoreReviewScreenshotCreateRequestDataRelationshipsInAppPurchaseV2}
     * @memberof InAppPurchaseImageCreateRequestDataRelationships
     */
    inAppPurchase: InAppPurchaseAppStoreReviewScreenshotCreateRequestDataRelationshipsInAppPurchaseV2;
}

/**
 * Check if a given object implements the InAppPurchaseImageCreateRequestDataRelationships interface.
 */
export function instanceOfInAppPurchaseImageCreateRequestDataRelationships(value: object): value is InAppPurchaseImageCreateRequestDataRelationships {
    if (!('inAppPurchase' in value) || value['inAppPurchase'] === undefined) return false;
    return true;
}

export function InAppPurchaseImageCreateRequestDataRelationshipsFromJSON(json: any): InAppPurchaseImageCreateRequestDataRelationships {
    return InAppPurchaseImageCreateRequestDataRelationshipsFromJSONTyped(json, false);
}

export function InAppPurchaseImageCreateRequestDataRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): InAppPurchaseImageCreateRequestDataRelationships {
    if (json == null) {
        return json;
    }
    return {
        
        'inAppPurchase': InAppPurchaseAppStoreReviewScreenshotCreateRequestDataRelationshipsInAppPurchaseV2FromJSON(json['inAppPurchase']),
    };
}

export function InAppPurchaseImageCreateRequestDataRelationshipsToJSON(json: any): InAppPurchaseImageCreateRequestDataRelationships {
    return InAppPurchaseImageCreateRequestDataRelationshipsToJSONTyped(json, false);
}

export function InAppPurchaseImageCreateRequestDataRelationshipsToJSONTyped(value?: InAppPurchaseImageCreateRequestDataRelationships | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'inAppPurchase': InAppPurchaseAppStoreReviewScreenshotCreateRequestDataRelationshipsInAppPurchaseV2ToJSON(value['inAppPurchase']),
    };
}

