
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PrereleaseVersion } from './PrereleaseVersion';
import {
    PrereleaseVersionFromJSON,
    PrereleaseVersionFromJSONTyped,
    PrereleaseVersionToJSON,
    PrereleaseVersionToJSONTyped,
} from './PrereleaseVersion';
import type { DocumentLinks } from './DocumentLinks';
import {
    DocumentLinksFromJSON,
    DocumentLinksFromJSONTyped,
    DocumentLinksToJSON,
    DocumentLinksToJSONTyped,
} from './DocumentLinks';

/**
 * 
 * @export
 * @interface PrereleaseVersionWithoutIncludesResponse
 */
export interface PrereleaseVersionWithoutIncludesResponse {
    /**
     * 
     * @type {PrereleaseVersion}
     * @memberof PrereleaseVersionWithoutIncludesResponse
     */
    data: PrereleaseVersion;
    /**
     * 
     * @type {DocumentLinks}
     * @memberof PrereleaseVersionWithoutIncludesResponse
     */
    links: DocumentLinks;
}

/**
 * Check if a given object implements the PrereleaseVersionWithoutIncludesResponse interface.
 */
export function instanceOfPrereleaseVersionWithoutIncludesResponse(value: object): value is PrereleaseVersionWithoutIncludesResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('links' in value) || value['links'] === undefined) return false;
    return true;
}

export function PrereleaseVersionWithoutIncludesResponseFromJSON(json: any): PrereleaseVersionWithoutIncludesResponse {
    return PrereleaseVersionWithoutIncludesResponseFromJSONTyped(json, false);
}

export function PrereleaseVersionWithoutIncludesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrereleaseVersionWithoutIncludesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': PrereleaseVersionFromJSON(json['data']),
        'links': DocumentLinksFromJSON(json['links']),
    };
}

export function PrereleaseVersionWithoutIncludesResponseToJSON(json: any): PrereleaseVersionWithoutIncludesResponse {
    return PrereleaseVersionWithoutIncludesResponseToJSONTyped(json, false);
}

export function PrereleaseVersionWithoutIncludesResponseToJSONTyped(value?: PrereleaseVersionWithoutIncludesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': PrereleaseVersionToJSON(value['data']),
        'links': DocumentLinksToJSON(value['links']),
    };
}

