/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppRelationshipsPromotedPurchasesDataInner } from './AppRelationshipsPromotedPurchasesDataInner';
import {
    AppRelationshipsPromotedPurchasesDataInnerFromJSON,
    AppRelationshipsPromotedPurchasesDataInnerFromJSONTyped,
    AppRelationshipsPromotedPurchasesDataInnerToJSON,
    AppRelationshipsPromotedPurchasesDataInnerToJSONTyped,
} from './AppRelationshipsPromotedPurchasesDataInner';

/**
 * 
 * @export
 * @interface PromotedPurchaseImageCreateRequestDataRelationshipsPromotedPurchase
 */
export interface PromotedPurchaseImageCreateRequestDataRelationshipsPromotedPurchase {
    /**
     * 
     * @type {AppRelationshipsPromotedPurchasesDataInner}
     * @memberof PromotedPurchaseImageCreateRequestDataRelationshipsPromotedPurchase
     */
    data: AppRelationshipsPromotedPurchasesDataInner;
}

/**
 * Check if a given object implements the PromotedPurchaseImageCreateRequestDataRelationshipsPromotedPurchase interface.
 */
export function instanceOfPromotedPurchaseImageCreateRequestDataRelationshipsPromotedPurchase(value: object): value is PromotedPurchaseImageCreateRequestDataRelationshipsPromotedPurchase {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function PromotedPurchaseImageCreateRequestDataRelationshipsPromotedPurchaseFromJSON(json: any): PromotedPurchaseImageCreateRequestDataRelationshipsPromotedPurchase {
    return PromotedPurchaseImageCreateRequestDataRelationshipsPromotedPurchaseFromJSONTyped(json, false);
}

export function PromotedPurchaseImageCreateRequestDataRelationshipsPromotedPurchaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromotedPurchaseImageCreateRequestDataRelationshipsPromotedPurchase {
    if (json == null) {
        return json;
    }
    return {
        
        'data': AppRelationshipsPromotedPurchasesDataInnerFromJSON(json['data']),
    };
}

export function PromotedPurchaseImageCreateRequestDataRelationshipsPromotedPurchaseToJSON(json: any): PromotedPurchaseImageCreateRequestDataRelationshipsPromotedPurchase {
    return PromotedPurchaseImageCreateRequestDataRelationshipsPromotedPurchaseToJSONTyped(json, false);
}

export function PromotedPurchaseImageCreateRequestDataRelationshipsPromotedPurchaseToJSONTyped(value?: PromotedPurchaseImageCreateRequestDataRelationshipsPromotedPurchase | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': AppRelationshipsPromotedPurchasesDataInnerToJSON(value['data']),
    };
}

