
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourceLinks
 */
export interface ResourceLinks {
    /**
     * 
     * @type {string}
     * @memberof ResourceLinks
     */
    self?: string;
}

/**
 * Check if a given object implements the ResourceLinks interface.
 */
export function instanceOfResourceLinks(value: object): value is ResourceLinks {
    return true;
}

export function ResourceLinksFromJSON(json: any): ResourceLinks {
    return ResourceLinksFromJSONTyped(json, false);
}

export function ResourceLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceLinks {
    if (json == null) {
        return json;
    }
    return {
        
        'self': json['self'] == null ? undefined : json['self'],
    };
}

export function ResourceLinksToJSON(json: any): ResourceLinks {
    return ResourceLinksToJSONTyped(json, false);
}

export function ResourceLinksToJSONTyped(value?: ResourceLinks | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'self': value['self'],
    };
}

