
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AnalyticsReportRequestCreateRequestDataRelationships } from './AnalyticsReportRequestCreateRequestDataRelationships';
import {
    AnalyticsReportRequestCreateRequestDataRelationshipsFromJSON,
    AnalyticsReportRequestCreateRequestDataRelationshipsFromJSONTyped,
    AnalyticsReportRequestCreateRequestDataRelationshipsToJSON,
    AnalyticsReportRequestCreateRequestDataRelationshipsToJSONTyped,
} from './AnalyticsReportRequestCreateRequestDataRelationships';
import type { ReviewSubmissionCreateRequestDataAttributes } from './ReviewSubmissionCreateRequestDataAttributes';
import {
    ReviewSubmissionCreateRequestDataAttributesFromJSON,
    ReviewSubmissionCreateRequestDataAttributesFromJSONTyped,
    ReviewSubmissionCreateRequestDataAttributesToJSON,
    ReviewSubmissionCreateRequestDataAttributesToJSONTyped,
} from './ReviewSubmissionCreateRequestDataAttributes';

/**
 * 
 * @export
 * @interface ReviewSubmissionCreateRequestData
 */
export interface ReviewSubmissionCreateRequestData {
    /**
     * 
     * @type {string}
     * @memberof ReviewSubmissionCreateRequestData
     */
    type: ReviewSubmissionCreateRequestDataTypeEnum;
    /**
     * 
     * @type {ReviewSubmissionCreateRequestDataAttributes}
     * @memberof ReviewSubmissionCreateRequestData
     */
    attributes: ReviewSubmissionCreateRequestDataAttributes;
    /**
     * 
     * @type {AnalyticsReportRequestCreateRequestDataRelationships}
     * @memberof ReviewSubmissionCreateRequestData
     */
    relationships: AnalyticsReportRequestCreateRequestDataRelationships;
}


/**
 * @export
 */
export const ReviewSubmissionCreateRequestDataTypeEnum = {
    ReviewSubmissions: 'reviewSubmissions'
} as const;
export type ReviewSubmissionCreateRequestDataTypeEnum = typeof ReviewSubmissionCreateRequestDataTypeEnum[keyof typeof ReviewSubmissionCreateRequestDataTypeEnum];


/**
 * Check if a given object implements the ReviewSubmissionCreateRequestData interface.
 */
export function instanceOfReviewSubmissionCreateRequestData(value: object): value is ReviewSubmissionCreateRequestData {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    if (!('relationships' in value) || value['relationships'] === undefined) return false;
    return true;
}

export function ReviewSubmissionCreateRequestDataFromJSON(json: any): ReviewSubmissionCreateRequestData {
    return ReviewSubmissionCreateRequestDataFromJSONTyped(json, false);
}

export function ReviewSubmissionCreateRequestDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewSubmissionCreateRequestData {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'attributes': ReviewSubmissionCreateRequestDataAttributesFromJSON(json['attributes']),
        'relationships': AnalyticsReportRequestCreateRequestDataRelationshipsFromJSON(json['relationships']),
    };
}

export function ReviewSubmissionCreateRequestDataToJSON(json: any): ReviewSubmissionCreateRequestData {
    return ReviewSubmissionCreateRequestDataToJSONTyped(json, false);
}

export function ReviewSubmissionCreateRequestDataToJSONTyped(value?: ReviewSubmissionCreateRequestData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'attributes': ReviewSubmissionCreateRequestDataAttributesToJSON(value['attributes']),
        'relationships': AnalyticsReportRequestCreateRequestDataRelationshipsToJSON(value['relationships']),
    };
}

