
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PagingInformation } from './PagingInformation';
import {
    PagingInformationFromJSON,
    PagingInformationFromJSONTyped,
    PagingInformationToJSON,
    PagingInformationToJSONTyped,
} from './PagingInformation';
import type { ReviewSubmissionItemsResponseIncludedInner } from './ReviewSubmissionItemsResponseIncludedInner';
import {
    ReviewSubmissionItemsResponseIncludedInnerFromJSON,
    ReviewSubmissionItemsResponseIncludedInnerFromJSONTyped,
    ReviewSubmissionItemsResponseIncludedInnerToJSON,
    ReviewSubmissionItemsResponseIncludedInnerToJSONTyped,
} from './ReviewSubmissionItemsResponseIncludedInner';
import type { ReviewSubmissionItem } from './ReviewSubmissionItem';
import {
    ReviewSubmissionItemFromJSON,
    ReviewSubmissionItemFromJSONTyped,
    ReviewSubmissionItemToJSON,
    ReviewSubmissionItemToJSONTyped,
} from './ReviewSubmissionItem';
import type { PagedDocumentLinks } from './PagedDocumentLinks';
import {
    PagedDocumentLinksFromJSON,
    PagedDocumentLinksFromJSONTyped,
    PagedDocumentLinksToJSON,
    PagedDocumentLinksToJSONTyped,
} from './PagedDocumentLinks';

/**
 * 
 * @export
 * @interface ReviewSubmissionItemsResponse
 */
export interface ReviewSubmissionItemsResponse {
    /**
     * 
     * @type {Array<ReviewSubmissionItem>}
     * @memberof ReviewSubmissionItemsResponse
     */
    data: Array<ReviewSubmissionItem>;
    /**
     * 
     * @type {Array<ReviewSubmissionItemsResponseIncludedInner>}
     * @memberof ReviewSubmissionItemsResponse
     */
    included?: Array<ReviewSubmissionItemsResponseIncludedInner>;
    /**
     * 
     * @type {PagedDocumentLinks}
     * @memberof ReviewSubmissionItemsResponse
     */
    links: PagedDocumentLinks;
    /**
     * 
     * @type {PagingInformation}
     * @memberof ReviewSubmissionItemsResponse
     */
    meta?: PagingInformation;
}

/**
 * Check if a given object implements the ReviewSubmissionItemsResponse interface.
 */
export function instanceOfReviewSubmissionItemsResponse(value: object): value is ReviewSubmissionItemsResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('links' in value) || value['links'] === undefined) return false;
    return true;
}

export function ReviewSubmissionItemsResponseFromJSON(json: any): ReviewSubmissionItemsResponse {
    return ReviewSubmissionItemsResponseFromJSONTyped(json, false);
}

export function ReviewSubmissionItemsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewSubmissionItemsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ReviewSubmissionItemFromJSON)),
        'included': json['included'] == null ? undefined : ((json['included'] as Array<any>).map(ReviewSubmissionItemsResponseIncludedInnerFromJSON)),
        'links': PagedDocumentLinksFromJSON(json['links']),
        'meta': json['meta'] == null ? undefined : PagingInformationFromJSON(json['meta']),
    };
}

export function ReviewSubmissionItemsResponseToJSON(json: any): ReviewSubmissionItemsResponse {
    return ReviewSubmissionItemsResponseToJSONTyped(json, false);
}

export function ReviewSubmissionItemsResponseToJSONTyped(value?: ReviewSubmissionItemsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(ReviewSubmissionItemToJSON)),
        'included': value['included'] == null ? undefined : ((value['included'] as Array<any>).map(ReviewSubmissionItemsResponseIncludedInnerToJSON)),
        'links': PagedDocumentLinksToJSON(value['links']),
        'meta': PagingInformationToJSON(value['meta']),
    };
}

