
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReviewSubmissionItemRelationships } from './ReviewSubmissionItemRelationships';
import {
    ReviewSubmissionItemRelationshipsFromJSON,
    ReviewSubmissionItemRelationshipsFromJSONTyped,
    ReviewSubmissionItemRelationshipsToJSON,
    ReviewSubmissionItemRelationshipsToJSONTyped,
} from './ReviewSubmissionItemRelationships';
import type { ReviewSubmissionItemAttributes } from './ReviewSubmissionItemAttributes';
import {
    ReviewSubmissionItemAttributesFromJSON,
    ReviewSubmissionItemAttributesFromJSONTyped,
    ReviewSubmissionItemAttributesToJSON,
    ReviewSubmissionItemAttributesToJSONTyped,
} from './ReviewSubmissionItemAttributes';
import type { ResourceLinks } from './ResourceLinks';
import {
    ResourceLinksFromJSON,
    ResourceLinksFromJSONTyped,
    ResourceLinksToJSON,
    ResourceLinksToJSONTyped,
} from './ResourceLinks';

/**
 * 
 * @export
 * @interface ReviewSubmissionItem
 */
export interface ReviewSubmissionItem {
    /**
     * 
     * @type {string}
     * @memberof ReviewSubmissionItem
     */
    type: ReviewSubmissionItemTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ReviewSubmissionItem
     */
    id: string;
    /**
     * 
     * @type {ReviewSubmissionItemAttributes}
     * @memberof ReviewSubmissionItem
     */
    attributes?: ReviewSubmissionItemAttributes;
    /**
     * 
     * @type {ReviewSubmissionItemRelationships}
     * @memberof ReviewSubmissionItem
     */
    relationships?: ReviewSubmissionItemRelationships;
    /**
     * 
     * @type {ResourceLinks}
     * @memberof ReviewSubmissionItem
     */
    links?: ResourceLinks;
}


/**
 * @export
 */
export const ReviewSubmissionItemTypeEnum = {
    ReviewSubmissionItems: 'reviewSubmissionItems'
} as const;
export type ReviewSubmissionItemTypeEnum = typeof ReviewSubmissionItemTypeEnum[keyof typeof ReviewSubmissionItemTypeEnum];


/**
 * Check if a given object implements the ReviewSubmissionItem interface.
 */
export function instanceOfReviewSubmissionItem(value: object): value is ReviewSubmissionItem {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ReviewSubmissionItemFromJSON(json: any): ReviewSubmissionItem {
    return ReviewSubmissionItemFromJSONTyped(json, false);
}

export function ReviewSubmissionItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewSubmissionItem {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': json['attributes'] == null ? undefined : ReviewSubmissionItemAttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : ReviewSubmissionItemRelationshipsFromJSON(json['relationships']),
        'links': json['links'] == null ? undefined : ResourceLinksFromJSON(json['links']),
    };
}

export function ReviewSubmissionItemToJSON(json: any): ReviewSubmissionItem {
    return ReviewSubmissionItemToJSONTyped(json, false);
}

export function ReviewSubmissionItemToJSONTyped(value?: ReviewSubmissionItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
        'attributes': ReviewSubmissionItemAttributesToJSON(value['attributes']),
        'relationships': ReviewSubmissionItemRelationshipsToJSON(value['relationships']),
        'links': ResourceLinksToJSON(value['links']),
    };
}

