
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TerritoryCode } from './TerritoryCode';
import {
    TerritoryCodeFromJSON,
    TerritoryCodeFromJSONTyped,
    TerritoryCodeToJSON,
    TerritoryCodeToJSONTyped,
} from './TerritoryCode';

/**
 * 
 * @export
 * @interface SandboxTesterV2UpdateRequestDataAttributes
 */
export interface SandboxTesterV2UpdateRequestDataAttributes {
    /**
     * 
     * @type {TerritoryCode}
     * @memberof SandboxTesterV2UpdateRequestDataAttributes
     */
    territory?: TerritoryCode;
    /**
     * 
     * @type {boolean}
     * @memberof SandboxTesterV2UpdateRequestDataAttributes
     */
    interruptPurchases?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SandboxTesterV2UpdateRequestDataAttributes
     */
    subscriptionRenewalRate?: SandboxTesterV2UpdateRequestDataAttributesSubscriptionRenewalRateEnum;
}


/**
 * @export
 */
export const SandboxTesterV2UpdateRequestDataAttributesSubscriptionRenewalRateEnum = {
    OneHour: 'MONTHLY_RENEWAL_EVERY_ONE_HOUR',
    ThirtyMinutes: 'MONTHLY_RENEWAL_EVERY_THIRTY_MINUTES',
    FifteenMinutes: 'MONTHLY_RENEWAL_EVERY_FIFTEEN_MINUTES',
    FiveMinutes: 'MONTHLY_RENEWAL_EVERY_FIVE_MINUTES',
    ThreeMinutes: 'MONTHLY_RENEWAL_EVERY_THREE_MINUTES'
} as const;
export type SandboxTesterV2UpdateRequestDataAttributesSubscriptionRenewalRateEnum = typeof SandboxTesterV2UpdateRequestDataAttributesSubscriptionRenewalRateEnum[keyof typeof SandboxTesterV2UpdateRequestDataAttributesSubscriptionRenewalRateEnum];


/**
 * Check if a given object implements the SandboxTesterV2UpdateRequestDataAttributes interface.
 */
export function instanceOfSandboxTesterV2UpdateRequestDataAttributes(value: object): value is SandboxTesterV2UpdateRequestDataAttributes {
    return true;
}

export function SandboxTesterV2UpdateRequestDataAttributesFromJSON(json: any): SandboxTesterV2UpdateRequestDataAttributes {
    return SandboxTesterV2UpdateRequestDataAttributesFromJSONTyped(json, false);
}

export function SandboxTesterV2UpdateRequestDataAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): SandboxTesterV2UpdateRequestDataAttributes {
    if (json == null) {
        return json;
    }
    return {
        
        'territory': json['territory'] == null ? undefined : TerritoryCodeFromJSON(json['territory']),
        'interruptPurchases': json['interruptPurchases'] == null ? undefined : json['interruptPurchases'],
        'subscriptionRenewalRate': json['subscriptionRenewalRate'] == null ? undefined : json['subscriptionRenewalRate'],
    };
}

export function SandboxTesterV2UpdateRequestDataAttributesToJSON(json: any): SandboxTesterV2UpdateRequestDataAttributes {
    return SandboxTesterV2UpdateRequestDataAttributesToJSONTyped(json, false);
}

export function SandboxTesterV2UpdateRequestDataAttributesToJSONTyped(value?: SandboxTesterV2UpdateRequestDataAttributes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'territory': TerritoryCodeToJSON(value['territory']),
        'interruptPurchases': value['interruptPurchases'],
        'subscriptionRenewalRate': value['subscriptionRenewalRate'],
    };
}

