
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ScmRepository } from './ScmRepository';
import {
    ScmRepositoryFromJSON,
    ScmRepositoryFromJSONTyped,
    ScmRepositoryToJSON,
    ScmRepositoryToJSONTyped,
} from './ScmRepository';
import type { ScmPullRequest } from './ScmPullRequest';
import {
    ScmPullRequestFromJSON,
    ScmPullRequestFromJSONTyped,
    ScmPullRequestToJSON,
    ScmPullRequestToJSONTyped,
} from './ScmPullRequest';
import type { DocumentLinks } from './DocumentLinks';
import {
    DocumentLinksFromJSON,
    DocumentLinksFromJSONTyped,
    DocumentLinksToJSON,
    DocumentLinksToJSONTyped,
} from './DocumentLinks';

/**
 * 
 * @export
 * @interface ScmPullRequestResponse
 */
export interface ScmPullRequestResponse {
    /**
     * 
     * @type {ScmPullRequest}
     * @memberof ScmPullRequestResponse
     */
    data: ScmPullRequest;
    /**
     * 
     * @type {Array<ScmRepository>}
     * @memberof ScmPullRequestResponse
     */
    included?: Array<ScmRepository>;
    /**
     * 
     * @type {DocumentLinks}
     * @memberof ScmPullRequestResponse
     */
    links: DocumentLinks;
}

/**
 * Check if a given object implements the ScmPullRequestResponse interface.
 */
export function instanceOfScmPullRequestResponse(value: object): value is ScmPullRequestResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('links' in value) || value['links'] === undefined) return false;
    return true;
}

export function ScmPullRequestResponseFromJSON(json: any): ScmPullRequestResponse {
    return ScmPullRequestResponseFromJSONTyped(json, false);
}

export function ScmPullRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScmPullRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ScmPullRequestFromJSON(json['data']),
        'included': json['included'] == null ? undefined : ((json['included'] as Array<any>).map(ScmRepositoryFromJSON)),
        'links': DocumentLinksFromJSON(json['links']),
    };
}

export function ScmPullRequestResponseToJSON(json: any): ScmPullRequestResponse {
    return ScmPullRequestResponseToJSONTyped(json, false);
}

export function ScmPullRequestResponseToJSONTyped(value?: ScmPullRequestResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ScmPullRequestToJSON(value['data']),
        'included': value['included'] == null ? undefined : ((value['included'] as Array<any>).map(ScmRepositoryToJSON)),
        'links': DocumentLinksToJSON(value['links']),
    };
}

