
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PagingInformation } from './PagingInformation';
import {
    PagingInformationFromJSON,
    PagingInformationFromJSONTyped,
    PagingInformationToJSON,
    PagingInformationToJSONTyped,
} from './PagingInformation';
import type { SubscriptionOfferCodesResponseIncludedInner } from './SubscriptionOfferCodesResponseIncludedInner';
import {
    SubscriptionOfferCodesResponseIncludedInnerFromJSON,
    SubscriptionOfferCodesResponseIncludedInnerFromJSONTyped,
    SubscriptionOfferCodesResponseIncludedInnerToJSON,
    SubscriptionOfferCodesResponseIncludedInnerToJSONTyped,
} from './SubscriptionOfferCodesResponseIncludedInner';
import type { PagedDocumentLinks } from './PagedDocumentLinks';
import {
    PagedDocumentLinksFromJSON,
    PagedDocumentLinksFromJSONTyped,
    PagedDocumentLinksToJSON,
    PagedDocumentLinksToJSONTyped,
} from './PagedDocumentLinks';
import type { SubscriptionOfferCode } from './SubscriptionOfferCode';
import {
    SubscriptionOfferCodeFromJSON,
    SubscriptionOfferCodeFromJSONTyped,
    SubscriptionOfferCodeToJSON,
    SubscriptionOfferCodeToJSONTyped,
} from './SubscriptionOfferCode';

/**
 * 
 * @export
 * @interface SubscriptionOfferCodesResponse
 */
export interface SubscriptionOfferCodesResponse {
    /**
     * 
     * @type {Array<SubscriptionOfferCode>}
     * @memberof SubscriptionOfferCodesResponse
     */
    data: Array<SubscriptionOfferCode>;
    /**
     * 
     * @type {Array<SubscriptionOfferCodesResponseIncludedInner>}
     * @memberof SubscriptionOfferCodesResponse
     */
    included?: Array<SubscriptionOfferCodesResponseIncludedInner>;
    /**
     * 
     * @type {PagedDocumentLinks}
     * @memberof SubscriptionOfferCodesResponse
     */
    links: PagedDocumentLinks;
    /**
     * 
     * @type {PagingInformation}
     * @memberof SubscriptionOfferCodesResponse
     */
    meta?: PagingInformation;
}

/**
 * Check if a given object implements the SubscriptionOfferCodesResponse interface.
 */
export function instanceOfSubscriptionOfferCodesResponse(value: object): value is SubscriptionOfferCodesResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('links' in value) || value['links'] === undefined) return false;
    return true;
}

export function SubscriptionOfferCodesResponseFromJSON(json: any): SubscriptionOfferCodesResponse {
    return SubscriptionOfferCodesResponseFromJSONTyped(json, false);
}

export function SubscriptionOfferCodesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionOfferCodesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(SubscriptionOfferCodeFromJSON)),
        'included': json['included'] == null ? undefined : ((json['included'] as Array<any>).map(SubscriptionOfferCodesResponseIncludedInnerFromJSON)),
        'links': PagedDocumentLinksFromJSON(json['links']),
        'meta': json['meta'] == null ? undefined : PagingInformationFromJSON(json['meta']),
    };
}

export function SubscriptionOfferCodesResponseToJSON(json: any): SubscriptionOfferCodesResponse {
    return SubscriptionOfferCodesResponseToJSONTyped(json, false);
}

export function SubscriptionOfferCodesResponseToJSONTyped(value?: SubscriptionOfferCodesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(SubscriptionOfferCodeToJSON)),
        'included': value['included'] == null ? undefined : ((value['included'] as Array<any>).map(SubscriptionOfferCodesResponseIncludedInnerToJSON)),
        'links': PagedDocumentLinksToJSON(value['links']),
        'meta': PagingInformationToJSON(value['meta']),
    };
}

