
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubscriptionIntroductoryOfferUpdateRequestDataAttributes } from './SubscriptionIntroductoryOfferUpdateRequestDataAttributes';
import {
    SubscriptionIntroductoryOfferUpdateRequestDataAttributesFromJSON,
    SubscriptionIntroductoryOfferUpdateRequestDataAttributesFromJSONTyped,
    SubscriptionIntroductoryOfferUpdateRequestDataAttributesToJSON,
    SubscriptionIntroductoryOfferUpdateRequestDataAttributesToJSONTyped,
} from './SubscriptionIntroductoryOfferUpdateRequestDataAttributes';

/**
 * 
 * @export
 * @interface SubscriptionIntroductoryOfferUpdateRequestData
 */
export interface SubscriptionIntroductoryOfferUpdateRequestData {
    /**
     * 
     * @type {string}
     * @memberof SubscriptionIntroductoryOfferUpdateRequestData
     */
    type: SubscriptionIntroductoryOfferUpdateRequestDataTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionIntroductoryOfferUpdateRequestData
     */
    id: string;
    /**
     * 
     * @type {SubscriptionIntroductoryOfferUpdateRequestDataAttributes}
     * @memberof SubscriptionIntroductoryOfferUpdateRequestData
     */
    attributes?: SubscriptionIntroductoryOfferUpdateRequestDataAttributes;
}


/**
 * @export
 */
export const SubscriptionIntroductoryOfferUpdateRequestDataTypeEnum = {
    SubscriptionIntroductoryOffers: 'subscriptionIntroductoryOffers'
} as const;
export type SubscriptionIntroductoryOfferUpdateRequestDataTypeEnum = typeof SubscriptionIntroductoryOfferUpdateRequestDataTypeEnum[keyof typeof SubscriptionIntroductoryOfferUpdateRequestDataTypeEnum];


/**
 * Check if a given object implements the SubscriptionIntroductoryOfferUpdateRequestData interface.
 */
export function instanceOfSubscriptionIntroductoryOfferUpdateRequestData(value: object): value is SubscriptionIntroductoryOfferUpdateRequestData {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function SubscriptionIntroductoryOfferUpdateRequestDataFromJSON(json: any): SubscriptionIntroductoryOfferUpdateRequestData {
    return SubscriptionIntroductoryOfferUpdateRequestDataFromJSONTyped(json, false);
}

export function SubscriptionIntroductoryOfferUpdateRequestDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionIntroductoryOfferUpdateRequestData {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': json['attributes'] == null ? undefined : SubscriptionIntroductoryOfferUpdateRequestDataAttributesFromJSON(json['attributes']),
    };
}

export function SubscriptionIntroductoryOfferUpdateRequestDataToJSON(json: any): SubscriptionIntroductoryOfferUpdateRequestData {
    return SubscriptionIntroductoryOfferUpdateRequestDataToJSONTyped(json, false);
}

export function SubscriptionIntroductoryOfferUpdateRequestDataToJSONTyped(value?: SubscriptionIntroductoryOfferUpdateRequestData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
        'attributes': SubscriptionIntroductoryOfferUpdateRequestDataAttributesToJSON(value['attributes']),
    };
}

