/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubscriptionRelationshipsIntroductoryOffersDataInner } from './SubscriptionRelationshipsIntroductoryOffersDataInner';
import {
    SubscriptionRelationshipsIntroductoryOffersDataInnerFromJSON,
    SubscriptionRelationshipsIntroductoryOffersDataInnerFromJSONTyped,
    SubscriptionRelationshipsIntroductoryOffersDataInnerToJSON,
    SubscriptionRelationshipsIntroductoryOffersDataInnerToJSONTyped,
} from './SubscriptionRelationshipsIntroductoryOffersDataInner';

/**
 * 
 * @export
 * @interface SubscriptionUpdateRequestDataRelationshipsIntroductoryOffers
 */
export interface SubscriptionUpdateRequestDataRelationshipsIntroductoryOffers {
    /**
     * 
     * @type {Array<SubscriptionRelationshipsIntroductoryOffersDataInner>}
     * @memberof SubscriptionUpdateRequestDataRelationshipsIntroductoryOffers
     */
    data?: Array<SubscriptionRelationshipsIntroductoryOffersDataInner>;
}

/**
 * Check if a given object implements the SubscriptionUpdateRequestDataRelationshipsIntroductoryOffers interface.
 */
export function instanceOfSubscriptionUpdateRequestDataRelationshipsIntroductoryOffers(value: object): value is SubscriptionUpdateRequestDataRelationshipsIntroductoryOffers {
    return true;
}

export function SubscriptionUpdateRequestDataRelationshipsIntroductoryOffersFromJSON(json: any): SubscriptionUpdateRequestDataRelationshipsIntroductoryOffers {
    return SubscriptionUpdateRequestDataRelationshipsIntroductoryOffersFromJSONTyped(json, false);
}

export function SubscriptionUpdateRequestDataRelationshipsIntroductoryOffersFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionUpdateRequestDataRelationshipsIntroductoryOffers {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(SubscriptionRelationshipsIntroductoryOffersDataInnerFromJSON)),
    };
}

export function SubscriptionUpdateRequestDataRelationshipsIntroductoryOffersToJSON(json: any): SubscriptionUpdateRequestDataRelationshipsIntroductoryOffers {
    return SubscriptionUpdateRequestDataRelationshipsIntroductoryOffersToJSONTyped(json, false);
}

export function SubscriptionUpdateRequestDataRelationshipsIntroductoryOffersToJSONTyped(value?: SubscriptionUpdateRequestDataRelationshipsIntroductoryOffers | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(SubscriptionRelationshipsIntroductoryOffersDataInnerToJSON)),
    };
}

