/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubscriptionGracePeriod } from './SubscriptionGracePeriod';
import {
    SubscriptionGracePeriodFromJSON,
    SubscriptionGracePeriodFromJSONTyped,
    SubscriptionGracePeriodToJSON,
    SubscriptionGracePeriodToJSONTyped,
} from './SubscriptionGracePeriod';
import type { DocumentLinks } from './DocumentLinks';
import {
    DocumentLinksFromJSON,
    DocumentLinksFromJSONTyped,
    DocumentLinksToJSON,
    DocumentLinksToJSONTyped,
} from './DocumentLinks';

/**
 * 
 * @export
 * @interface SubscriptionGracePeriodResponse
 */
export interface SubscriptionGracePeriodResponse {
    /**
     * 
     * @type {SubscriptionGracePeriod}
     * @memberof SubscriptionGracePeriodResponse
     */
    data: SubscriptionGracePeriod;
    /**
     * 
     * @type {DocumentLinks}
     * @memberof SubscriptionGracePeriodResponse
     */
    links: DocumentLinks;
}

/**
 * Check if a given object implements the SubscriptionGracePeriodResponse interface.
 */
export function instanceOfSubscriptionGracePeriodResponse(value: object): value is SubscriptionGracePeriodResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('links' in value) || value['links'] === undefined) return false;
    return true;
}

export function SubscriptionGracePeriodResponseFromJSON(json: any): SubscriptionGracePeriodResponse {
    return SubscriptionGracePeriodResponseFromJSONTyped(json, false);
}

export function SubscriptionGracePeriodResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionGracePeriodResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': SubscriptionGracePeriodFromJSON(json['data']),
        'links': DocumentLinksFromJSON(json['links']),
    };
}

export function SubscriptionGracePeriodResponseToJSON(json: any): SubscriptionGracePeriodResponse {
    return SubscriptionGracePeriodResponseToJSONTyped(json, false);
}

export function SubscriptionGracePeriodResponseToJSONTyped(value?: SubscriptionGracePeriodResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': SubscriptionGracePeriodToJSON(value['data']),
        'links': DocumentLinksToJSON(value['links']),
    };
}

