
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubscriptionIntroductoryOfferInlineCreateAttributes } from './SubscriptionIntroductoryOfferInlineCreateAttributes';
import {
    SubscriptionIntroductoryOfferInlineCreateAttributesFromJSON,
    SubscriptionIntroductoryOfferInlineCreateAttributesFromJSONTyped,
    SubscriptionIntroductoryOfferInlineCreateAttributesToJSON,
    SubscriptionIntroductoryOfferInlineCreateAttributesToJSONTyped,
} from './SubscriptionIntroductoryOfferInlineCreateAttributes';
import type { SubscriptionIntroductoryOfferCreateRequestDataRelationships } from './SubscriptionIntroductoryOfferCreateRequestDataRelationships';
import {
    SubscriptionIntroductoryOfferCreateRequestDataRelationshipsFromJSON,
    SubscriptionIntroductoryOfferCreateRequestDataRelationshipsFromJSONTyped,
    SubscriptionIntroductoryOfferCreateRequestDataRelationshipsToJSON,
    SubscriptionIntroductoryOfferCreateRequestDataRelationshipsToJSONTyped,
} from './SubscriptionIntroductoryOfferCreateRequestDataRelationships';

/**
 * 
 * @export
 * @interface SubscriptionIntroductoryOfferCreateRequestData
 */
export interface SubscriptionIntroductoryOfferCreateRequestData {
    /**
     * 
     * @type {string}
     * @memberof SubscriptionIntroductoryOfferCreateRequestData
     */
    type: SubscriptionIntroductoryOfferCreateRequestDataTypeEnum;
    /**
     * 
     * @type {SubscriptionIntroductoryOfferInlineCreateAttributes}
     * @memberof SubscriptionIntroductoryOfferCreateRequestData
     */
    attributes: SubscriptionIntroductoryOfferInlineCreateAttributes;
    /**
     * 
     * @type {SubscriptionIntroductoryOfferCreateRequestDataRelationships}
     * @memberof SubscriptionIntroductoryOfferCreateRequestData
     */
    relationships: SubscriptionIntroductoryOfferCreateRequestDataRelationships;
}


/**
 * @export
 */
export const SubscriptionIntroductoryOfferCreateRequestDataTypeEnum = {
    SubscriptionIntroductoryOffers: 'subscriptionIntroductoryOffers'
} as const;
export type SubscriptionIntroductoryOfferCreateRequestDataTypeEnum = typeof SubscriptionIntroductoryOfferCreateRequestDataTypeEnum[keyof typeof SubscriptionIntroductoryOfferCreateRequestDataTypeEnum];


/**
 * Check if a given object implements the SubscriptionIntroductoryOfferCreateRequestData interface.
 */
export function instanceOfSubscriptionIntroductoryOfferCreateRequestData(value: object): value is SubscriptionIntroductoryOfferCreateRequestData {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    if (!('relationships' in value) || value['relationships'] === undefined) return false;
    return true;
}

export function SubscriptionIntroductoryOfferCreateRequestDataFromJSON(json: any): SubscriptionIntroductoryOfferCreateRequestData {
    return SubscriptionIntroductoryOfferCreateRequestDataFromJSONTyped(json, false);
}

export function SubscriptionIntroductoryOfferCreateRequestDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionIntroductoryOfferCreateRequestData {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'attributes': SubscriptionIntroductoryOfferInlineCreateAttributesFromJSON(json['attributes']),
        'relationships': SubscriptionIntroductoryOfferCreateRequestDataRelationshipsFromJSON(json['relationships']),
    };
}

export function SubscriptionIntroductoryOfferCreateRequestDataToJSON(json: any): SubscriptionIntroductoryOfferCreateRequestData {
    return SubscriptionIntroductoryOfferCreateRequestDataToJSONTyped(json, false);
}

export function SubscriptionIntroductoryOfferCreateRequestDataToJSONTyped(value?: SubscriptionIntroductoryOfferCreateRequestData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'attributes': SubscriptionIntroductoryOfferInlineCreateAttributesToJSON(value['attributes']),
        'relationships': SubscriptionIntroductoryOfferCreateRequestDataRelationshipsToJSON(value['relationships']),
    };
}

