/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourceLinks } from './ResourceLinks';
import {
    ResourceLinksFromJSON,
    ResourceLinksFromJSONTyped,
    ResourceLinksToJSON,
    ResourceLinksToJSONTyped,
} from './ResourceLinks';

/**
 * 
 * @export
 * @interface SubscriptionOfferCodeOneTimeUseCodeValue
 */
export interface SubscriptionOfferCodeOneTimeUseCodeValue {
    /**
     * 
     * @type {string}
     * @memberof SubscriptionOfferCodeOneTimeUseCodeValue
     */
    type: SubscriptionOfferCodeOneTimeUseCodeValueTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionOfferCodeOneTimeUseCodeValue
     */
    id: string;
    /**
     * 
     * @type {ResourceLinks}
     * @memberof SubscriptionOfferCodeOneTimeUseCodeValue
     */
    links?: ResourceLinks;
}


/**
 * @export
 */
export const SubscriptionOfferCodeOneTimeUseCodeValueTypeEnum = {
    SubscriptionOfferCodeOneTimeUseCodeValues: 'subscriptionOfferCodeOneTimeUseCodeValues'
} as const;
export type SubscriptionOfferCodeOneTimeUseCodeValueTypeEnum = typeof SubscriptionOfferCodeOneTimeUseCodeValueTypeEnum[keyof typeof SubscriptionOfferCodeOneTimeUseCodeValueTypeEnum];


/**
 * Check if a given object implements the SubscriptionOfferCodeOneTimeUseCodeValue interface.
 */
export function instanceOfSubscriptionOfferCodeOneTimeUseCodeValue(value: object): value is SubscriptionOfferCodeOneTimeUseCodeValue {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function SubscriptionOfferCodeOneTimeUseCodeValueFromJSON(json: any): SubscriptionOfferCodeOneTimeUseCodeValue {
    return SubscriptionOfferCodeOneTimeUseCodeValueFromJSONTyped(json, false);
}

export function SubscriptionOfferCodeOneTimeUseCodeValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionOfferCodeOneTimeUseCodeValue {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'links': json['links'] == null ? undefined : ResourceLinksFromJSON(json['links']),
    };
}

export function SubscriptionOfferCodeOneTimeUseCodeValueToJSON(json: any): SubscriptionOfferCodeOneTimeUseCodeValue {
    return SubscriptionOfferCodeOneTimeUseCodeValueToJSONTyped(json, false);
}

export function SubscriptionOfferCodeOneTimeUseCodeValueToJSONTyped(value?: SubscriptionOfferCodeOneTimeUseCodeValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
        'links': ResourceLinksToJSON(value['links']),
    };
}

