/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubscriptionPricePointInlineCreate } from './SubscriptionPricePointInlineCreate';
import {
    SubscriptionPricePointInlineCreateFromJSON,
    SubscriptionPricePointInlineCreateFromJSONTyped,
    SubscriptionPricePointInlineCreateToJSON,
    SubscriptionPricePointInlineCreateToJSONTyped,
} from './SubscriptionPricePointInlineCreate';
import type { SubscriptionIntroductoryOfferCreateRequestData } from './SubscriptionIntroductoryOfferCreateRequestData';
import {
    SubscriptionIntroductoryOfferCreateRequestDataFromJSON,
    SubscriptionIntroductoryOfferCreateRequestDataFromJSONTyped,
    SubscriptionIntroductoryOfferCreateRequestDataToJSON,
    SubscriptionIntroductoryOfferCreateRequestDataToJSONTyped,
} from './SubscriptionIntroductoryOfferCreateRequestData';

/**
 * 
 * @export
 * @interface SubscriptionIntroductoryOfferCreateRequest
 */
export interface SubscriptionIntroductoryOfferCreateRequest {
    /**
     * 
     * @type {SubscriptionIntroductoryOfferCreateRequestData}
     * @memberof SubscriptionIntroductoryOfferCreateRequest
     */
    data: SubscriptionIntroductoryOfferCreateRequestData;
    /**
     * 
     * @type {Array<SubscriptionPricePointInlineCreate>}
     * @memberof SubscriptionIntroductoryOfferCreateRequest
     */
    included?: Array<SubscriptionPricePointInlineCreate>;
}

/**
 * Check if a given object implements the SubscriptionIntroductoryOfferCreateRequest interface.
 */
export function instanceOfSubscriptionIntroductoryOfferCreateRequest(value: object): value is SubscriptionIntroductoryOfferCreateRequest {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function SubscriptionIntroductoryOfferCreateRequestFromJSON(json: any): SubscriptionIntroductoryOfferCreateRequest {
    return SubscriptionIntroductoryOfferCreateRequestFromJSONTyped(json, false);
}

export function SubscriptionIntroductoryOfferCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionIntroductoryOfferCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'data': SubscriptionIntroductoryOfferCreateRequestDataFromJSON(json['data']),
        'included': json['included'] == null ? undefined : ((json['included'] as Array<any>).map(SubscriptionPricePointInlineCreateFromJSON)),
    };
}

export function SubscriptionIntroductoryOfferCreateRequestToJSON(json: any): SubscriptionIntroductoryOfferCreateRequest {
    return SubscriptionIntroductoryOfferCreateRequestToJSONTyped(json, false);
}

export function SubscriptionIntroductoryOfferCreateRequestToJSONTyped(value?: SubscriptionIntroductoryOfferCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': SubscriptionIntroductoryOfferCreateRequestDataToJSON(value['data']),
        'included': value['included'] == null ? undefined : ((value['included'] as Array<any>).map(SubscriptionPricePointInlineCreateToJSON)),
    };
}

