/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubscriptionPriceCreateRequestData } from './SubscriptionPriceCreateRequestData';
import {
    SubscriptionPriceCreateRequestDataFromJSON,
    SubscriptionPriceCreateRequestDataFromJSONTyped,
    SubscriptionPriceCreateRequestDataToJSON,
    SubscriptionPriceCreateRequestDataToJSONTyped,
} from './SubscriptionPriceCreateRequestData';

/**
 * 
 * @export
 * @interface SubscriptionPriceCreateRequest
 */
export interface SubscriptionPriceCreateRequest {
    /**
     * 
     * @type {SubscriptionPriceCreateRequestData}
     * @memberof SubscriptionPriceCreateRequest
     */
    data: SubscriptionPriceCreateRequestData;
}

/**
 * Check if a given object implements the SubscriptionPriceCreateRequest interface.
 */
export function instanceOfSubscriptionPriceCreateRequest(value: object): value is SubscriptionPriceCreateRequest {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function SubscriptionPriceCreateRequestFromJSON(json: any): SubscriptionPriceCreateRequest {
    return SubscriptionPriceCreateRequestFromJSONTyped(json, false);
}

export function SubscriptionPriceCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionPriceCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'data': SubscriptionPriceCreateRequestDataFromJSON(json['data']),
    };
}

export function SubscriptionPriceCreateRequestToJSON(json: any): SubscriptionPriceCreateRequest {
    return SubscriptionPriceCreateRequestToJSONTyped(json, false);
}

export function SubscriptionPriceCreateRequestToJSONTyped(value?: SubscriptionPriceCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': SubscriptionPriceCreateRequestDataToJSON(value['data']),
    };
}

