
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PagingInformation } from './PagingInformation';
import {
    PagingInformationFromJSON,
    PagingInformationFromJSONTyped,
    PagingInformationToJSON,
    PagingInformationToJSONTyped,
} from './PagingInformation';
import type { SubscriptionGroupsResponseIncludedInner } from './SubscriptionGroupsResponseIncludedInner';
import {
    SubscriptionGroupsResponseIncludedInnerFromJSON,
    SubscriptionGroupsResponseIncludedInnerFromJSONTyped,
    SubscriptionGroupsResponseIncludedInnerToJSON,
    SubscriptionGroupsResponseIncludedInnerToJSONTyped,
} from './SubscriptionGroupsResponseIncludedInner';
import type { SubscriptionGroup } from './SubscriptionGroup';
import {
    SubscriptionGroupFromJSON,
    SubscriptionGroupFromJSONTyped,
    SubscriptionGroupToJSON,
    SubscriptionGroupToJSONTyped,
} from './SubscriptionGroup';
import type { PagedDocumentLinks } from './PagedDocumentLinks';
import {
    PagedDocumentLinksFromJSON,
    PagedDocumentLinksFromJSONTyped,
    PagedDocumentLinksToJSON,
    PagedDocumentLinksToJSONTyped,
} from './PagedDocumentLinks';

/**
 * 
 * @export
 * @interface SubscriptionGroupsResponse
 */
export interface SubscriptionGroupsResponse {
    /**
     * 
     * @type {Array<SubscriptionGroup>}
     * @memberof SubscriptionGroupsResponse
     */
    data: Array<SubscriptionGroup>;
    /**
     * 
     * @type {Array<SubscriptionGroupsResponseIncludedInner>}
     * @memberof SubscriptionGroupsResponse
     */
    included?: Array<SubscriptionGroupsResponseIncludedInner>;
    /**
     * 
     * @type {PagedDocumentLinks}
     * @memberof SubscriptionGroupsResponse
     */
    links: PagedDocumentLinks;
    /**
     * 
     * @type {PagingInformation}
     * @memberof SubscriptionGroupsResponse
     */
    meta?: PagingInformation;
}

/**
 * Check if a given object implements the SubscriptionGroupsResponse interface.
 */
export function instanceOfSubscriptionGroupsResponse(value: object): value is SubscriptionGroupsResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('links' in value) || value['links'] === undefined) return false;
    return true;
}

export function SubscriptionGroupsResponseFromJSON(json: any): SubscriptionGroupsResponse {
    return SubscriptionGroupsResponseFromJSONTyped(json, false);
}

export function SubscriptionGroupsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionGroupsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(SubscriptionGroupFromJSON)),
        'included': json['included'] == null ? undefined : ((json['included'] as Array<any>).map(SubscriptionGroupsResponseIncludedInnerFromJSON)),
        'links': PagedDocumentLinksFromJSON(json['links']),
        'meta': json['meta'] == null ? undefined : PagingInformationFromJSON(json['meta']),
    };
}

export function SubscriptionGroupsResponseToJSON(json: any): SubscriptionGroupsResponse {
    return SubscriptionGroupsResponseToJSONTyped(json, false);
}

export function SubscriptionGroupsResponseToJSONTyped(value?: SubscriptionGroupsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(SubscriptionGroupToJSON)),
        'included': value['included'] == null ? undefined : ((value['included'] as Array<any>).map(SubscriptionGroupsResponseIncludedInnerToJSON)),
        'links': PagedDocumentLinksToJSON(value['links']),
        'meta': PagingInformationToJSON(value['meta']),
    };
}

