/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubscriptionOfferCodeCustomCodeCreateRequestData } from './SubscriptionOfferCodeCustomCodeCreateRequestData';
import {
    SubscriptionOfferCodeCustomCodeCreateRequestDataFromJSON,
    SubscriptionOfferCodeCustomCodeCreateRequestDataFromJSONTyped,
    SubscriptionOfferCodeCustomCodeCreateRequestDataToJSON,
    SubscriptionOfferCodeCustomCodeCreateRequestDataToJSONTyped,
} from './SubscriptionOfferCodeCustomCodeCreateRequestData';

/**
 * 
 * @export
 * @interface SubscriptionOfferCodeCustomCodeCreateRequest
 */
export interface SubscriptionOfferCodeCustomCodeCreateRequest {
    /**
     * 
     * @type {SubscriptionOfferCodeCustomCodeCreateRequestData}
     * @memberof SubscriptionOfferCodeCustomCodeCreateRequest
     */
    data: SubscriptionOfferCodeCustomCodeCreateRequestData;
}

/**
 * Check if a given object implements the SubscriptionOfferCodeCustomCodeCreateRequest interface.
 */
export function instanceOfSubscriptionOfferCodeCustomCodeCreateRequest(value: object): value is SubscriptionOfferCodeCustomCodeCreateRequest {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function SubscriptionOfferCodeCustomCodeCreateRequestFromJSON(json: any): SubscriptionOfferCodeCustomCodeCreateRequest {
    return SubscriptionOfferCodeCustomCodeCreateRequestFromJSONTyped(json, false);
}

export function SubscriptionOfferCodeCustomCodeCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionOfferCodeCustomCodeCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'data': SubscriptionOfferCodeCustomCodeCreateRequestDataFromJSON(json['data']),
    };
}

export function SubscriptionOfferCodeCustomCodeCreateRequestToJSON(json: any): SubscriptionOfferCodeCustomCodeCreateRequest {
    return SubscriptionOfferCodeCustomCodeCreateRequestToJSONTyped(json, false);
}

export function SubscriptionOfferCodeCustomCodeCreateRequestToJSONTyped(value?: SubscriptionOfferCodeCustomCodeCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': SubscriptionOfferCodeCustomCodeCreateRequestDataToJSON(value['data']),
    };
}

