
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubscriptionPromotionalOfferInlineCreateAttributes } from './SubscriptionPromotionalOfferInlineCreateAttributes';
import {
    SubscriptionPromotionalOfferInlineCreateAttributesFromJSON,
    SubscriptionPromotionalOfferInlineCreateAttributesFromJSONTyped,
    SubscriptionPromotionalOfferInlineCreateAttributesToJSON,
    SubscriptionPromotionalOfferInlineCreateAttributesToJSONTyped,
} from './SubscriptionPromotionalOfferInlineCreateAttributes';
import type { SubscriptionPromotionalOfferCreateRequestDataRelationships } from './SubscriptionPromotionalOfferCreateRequestDataRelationships';
import {
    SubscriptionPromotionalOfferCreateRequestDataRelationshipsFromJSON,
    SubscriptionPromotionalOfferCreateRequestDataRelationshipsFromJSONTyped,
    SubscriptionPromotionalOfferCreateRequestDataRelationshipsToJSON,
    SubscriptionPromotionalOfferCreateRequestDataRelationshipsToJSONTyped,
} from './SubscriptionPromotionalOfferCreateRequestDataRelationships';

/**
 * 
 * @export
 * @interface SubscriptionPromotionalOfferCreateRequestData
 */
export interface SubscriptionPromotionalOfferCreateRequestData {
    /**
     * 
     * @type {string}
     * @memberof SubscriptionPromotionalOfferCreateRequestData
     */
    type: SubscriptionPromotionalOfferCreateRequestDataTypeEnum;
    /**
     * 
     * @type {SubscriptionPromotionalOfferInlineCreateAttributes}
     * @memberof SubscriptionPromotionalOfferCreateRequestData
     */
    attributes: SubscriptionPromotionalOfferInlineCreateAttributes;
    /**
     * 
     * @type {SubscriptionPromotionalOfferCreateRequestDataRelationships}
     * @memberof SubscriptionPromotionalOfferCreateRequestData
     */
    relationships: SubscriptionPromotionalOfferCreateRequestDataRelationships;
}


/**
 * @export
 */
export const SubscriptionPromotionalOfferCreateRequestDataTypeEnum = {
    SubscriptionPromotionalOffers: 'subscriptionPromotionalOffers'
} as const;
export type SubscriptionPromotionalOfferCreateRequestDataTypeEnum = typeof SubscriptionPromotionalOfferCreateRequestDataTypeEnum[keyof typeof SubscriptionPromotionalOfferCreateRequestDataTypeEnum];


/**
 * Check if a given object implements the SubscriptionPromotionalOfferCreateRequestData interface.
 */
export function instanceOfSubscriptionPromotionalOfferCreateRequestData(value: object): value is SubscriptionPromotionalOfferCreateRequestData {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    if (!('relationships' in value) || value['relationships'] === undefined) return false;
    return true;
}

export function SubscriptionPromotionalOfferCreateRequestDataFromJSON(json: any): SubscriptionPromotionalOfferCreateRequestData {
    return SubscriptionPromotionalOfferCreateRequestDataFromJSONTyped(json, false);
}

export function SubscriptionPromotionalOfferCreateRequestDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionPromotionalOfferCreateRequestData {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'attributes': SubscriptionPromotionalOfferInlineCreateAttributesFromJSON(json['attributes']),
        'relationships': SubscriptionPromotionalOfferCreateRequestDataRelationshipsFromJSON(json['relationships']),
    };
}

export function SubscriptionPromotionalOfferCreateRequestDataToJSON(json: any): SubscriptionPromotionalOfferCreateRequestData {
    return SubscriptionPromotionalOfferCreateRequestDataToJSONTyped(json, false);
}

export function SubscriptionPromotionalOfferCreateRequestDataToJSONTyped(value?: SubscriptionPromotionalOfferCreateRequestData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'attributes': SubscriptionPromotionalOfferInlineCreateAttributesToJSON(value['attributes']),
        'relationships': SubscriptionPromotionalOfferCreateRequestDataRelationshipsToJSON(value['relationships']),
    };
}

